/* tslint:disable */
/* eslint-disable */
/**
 * Overmind Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BacktestingRequest,
  BacktestingResponse,
  HTTPValidationError,
  ModelInfo,
} from '../models/index';
import {
    BacktestingRequestFromJSON,
    BacktestingRequestToJSON,
    BacktestingResponseFromJSON,
    BacktestingResponseToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    ModelInfoFromJSON,
    ModelInfoToJSON,
} from '../models/index';

export interface ListAvailableModelsApiV1BacktestingModelsGetRequest {
    useCache?: boolean;
}

export interface RunBacktestingApiV1BacktestingRunPostRequest {
    backtestingRequest: BacktestingRequest;
    useCache?: boolean;
}

/**
 * 
 */
export class BacktestingApi extends runtime.BaseAPI {

    /**
     * Get a list of all available models for backtesting.  Returns a list of models with their provider and model name.
     * List Available Models
     */
    async listAvailableModelsApiV1BacktestingModelsGetRaw(requestParameters: ListAvailableModelsApiV1BacktestingModelsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ModelInfo>>> {
        const queryParameters: any = {};

        if (requestParameters['useCache'] != null) {
            queryParameters['use_cache'] = requestParameters['useCache'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/backtesting/models`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ModelInfoFromJSON));
    }

    /**
     * Get a list of all available models for backtesting.  Returns a list of models with their provider and model name.
     * List Available Models
     */
    async listAvailableModelsApiV1BacktestingModelsGet(requestParameters: ListAvailableModelsApiV1BacktestingModelsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ModelInfo>> {
        const response = await this.listAvailableModelsApiV1BacktestingModelsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Run model backtesting for a prompt template.  This endpoint will: 1. Validate models and prompt access 2. Check evaluation criteria exists 3. Count available spans for backtesting 4. Create a job with status \"pending\" 5. Job reconciler will pick up the job and execute the backtesting task  The backtesting runs as a background task and returns a job_id for tracking.
     * Run Backtesting
     */
    async runBacktestingApiV1BacktestingRunPostRaw(requestParameters: RunBacktestingApiV1BacktestingRunPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BacktestingResponse>> {
        if (requestParameters['backtestingRequest'] == null) {
            throw new runtime.RequiredError(
                'backtestingRequest',
                'Required parameter "backtestingRequest" was null or undefined when calling runBacktestingApiV1BacktestingRunPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['useCache'] != null) {
            queryParameters['use_cache'] = requestParameters['useCache'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/backtesting/run`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BacktestingRequestToJSON(requestParameters['backtestingRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BacktestingResponseFromJSON(jsonValue));
    }

    /**
     * Run model backtesting for a prompt template.  This endpoint will: 1. Validate models and prompt access 2. Check evaluation criteria exists 3. Count available spans for backtesting 4. Create a job with status \"pending\" 5. Job reconciler will pick up the job and execute the backtesting task  The backtesting runs as a background task and returns a job_id for tracking.
     * Run Backtesting
     */
    async runBacktestingApiV1BacktestingRunPost(requestParameters: RunBacktestingApiV1BacktestingRunPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BacktestingResponse> {
        const response = await this.runBacktestingApiV1BacktestingRunPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
