/* tslint:disable */
/* eslint-disable */
/**
 * Overmind Core
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AssignUserRoleRequest,
  HTTPValidationError,
  UserRoleResponse,
} from '../models/index';
import {
    AssignUserRoleRequestFromJSON,
    AssignUserRoleRequestToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    UserRoleResponseFromJSON,
    UserRoleResponseToJSON,
} from '../models/index';

export interface AssignUserRoleApiV1IamUsersUserIdRolesPostRequest {
    userId: string;
    assignUserRoleRequest: AssignUserRoleRequest;
}

export interface ListUserRolesApiV1IamUsersUserIdRolesGetRequest {
    userId: string;
    scopeType?: string | null;
    scopeId?: string | null;
}

export interface RemoveUserRoleApiV1IamUsersUserIdRolesUserRoleIdDeleteRequest {
    userId: string;
    userRoleId: string;
}

/**
 * 
 */
export class UserRolesApi extends runtime.BaseAPI {

    /**
     * Assign a project-scoped role to a user.  Caller must have ADMIN permission in the project.
     * Assign User Role
     */
    async assignUserRoleApiV1IamUsersUserIdRolesPostRaw(requestParameters: AssignUserRoleApiV1IamUsersUserIdRolesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserRoleResponse>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling assignUserRoleApiV1IamUsersUserIdRolesPost().'
            );
        }

        if (requestParameters['assignUserRoleRequest'] == null) {
            throw new runtime.RequiredError(
                'assignUserRoleRequest',
                'Required parameter "assignUserRoleRequest" was null or undefined when calling assignUserRoleApiV1IamUsersUserIdRolesPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/iam/users/{user_id}/roles`;
        urlPath = urlPath.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AssignUserRoleRequestToJSON(requestParameters['assignUserRoleRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserRoleResponseFromJSON(jsonValue));
    }

    /**
     * Assign a project-scoped role to a user.  Caller must have ADMIN permission in the project.
     * Assign User Role
     */
    async assignUserRoleApiV1IamUsersUserIdRolesPost(requestParameters: AssignUserRoleApiV1IamUsersUserIdRolesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserRoleResponse> {
        const response = await this.assignUserRoleApiV1IamUsersUserIdRolesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List all roles assigned to a user.
     * List User Roles
     */
    async listUserRolesApiV1IamUsersUserIdRolesGetRaw(requestParameters: ListUserRolesApiV1IamUsersUserIdRolesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<UserRoleResponse>>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling listUserRolesApiV1IamUsersUserIdRolesGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['scopeType'] != null) {
            queryParameters['scope_type'] = requestParameters['scopeType'];
        }

        if (requestParameters['scopeId'] != null) {
            queryParameters['scope_id'] = requestParameters['scopeId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/iam/users/{user_id}/roles`;
        urlPath = urlPath.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(UserRoleResponseFromJSON));
    }

    /**
     * List all roles assigned to a user.
     * List User Roles
     */
    async listUserRolesApiV1IamUsersUserIdRolesGet(requestParameters: ListUserRolesApiV1IamUsersUserIdRolesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<UserRoleResponse>> {
        const response = await this.listUserRolesApiV1IamUsersUserIdRolesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Remove a project-scoped role assignment from a user.
     * Remove User Role
     */
    async removeUserRoleApiV1IamUsersUserIdRolesUserRoleIdDeleteRaw(requestParameters: RemoveUserRoleApiV1IamUsersUserIdRolesUserRoleIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling removeUserRoleApiV1IamUsersUserIdRolesUserRoleIdDelete().'
            );
        }

        if (requestParameters['userRoleId'] == null) {
            throw new runtime.RequiredError(
                'userRoleId',
                'Required parameter "userRoleId" was null or undefined when calling removeUserRoleApiV1IamUsersUserIdRolesUserRoleIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/iam/users/{user_id}/roles/{user_role_id}`;
        urlPath = urlPath.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId'])));
        urlPath = urlPath.replace(`{${"user_role_id"}}`, encodeURIComponent(String(requestParameters['userRoleId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Remove a project-scoped role assignment from a user.
     * Remove User Role
     */
    async removeUserRoleApiV1IamUsersUserIdRolesUserRoleIdDelete(requestParameters: RemoveUserRoleApiV1IamUsersUserIdRolesUserRoleIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.removeUserRoleApiV1IamUsersUserIdRolesUserRoleIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
