/* tslint:disable */
/* eslint-disable */
/**
 * Overmind Core
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ChangePasswordRequest,
  HTTPValidationError,
  ImpersonateRequest,
  LoginRequest,
  OvermindApiV1EndpointsIamUsersLoginResponse,
  UserListResponse,
  UserResponse,
} from '../models/index';
import {
    ChangePasswordRequestFromJSON,
    ChangePasswordRequestToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    ImpersonateRequestFromJSON,
    ImpersonateRequestToJSON,
    LoginRequestFromJSON,
    LoginRequestToJSON,
    OvermindApiV1EndpointsIamUsersLoginResponseFromJSON,
    OvermindApiV1EndpointsIamUsersLoginResponseToJSON,
    UserListResponseFromJSON,
    UserListResponseToJSON,
    UserResponseFromJSON,
    UserResponseToJSON,
} from '../models/index';

export interface AddUserToProjectApiV1IamUsersProjectsProjectIdUsersUserIdPostRequest {
    projectId: string;
    userId: string;
}

export interface ChangePasswordApiV1IamUsersMePasswordPutRequest {
    changePasswordRequest: ChangePasswordRequest;
}

export interface ImpersonateApiV1IamUsersImpersonatePostRequest {
    impersonateRequest: ImpersonateRequest;
}

export interface ListProjectUsersApiV1IamUsersProjectsProjectIdGetRequest {
    projectId: string;
}

export interface LoginApiV1IamUsersLoginPostRequest {
    loginRequest: LoginRequest;
}

export interface RemoveUserFromProjectApiV1IamUsersProjectsProjectIdUsersUserIdDeleteRequest {
    projectId: string;
    userId: string;
}

/**
 * 
 */
export class UsersApi extends runtime.BaseAPI {

    /**
     * Add a user to a project (membership only, no role assignment).  User must have ADMIN permission in the project.
     * Add User To Project
     */
    async addUserToProjectApiV1IamUsersProjectsProjectIdUsersUserIdPostRaw(requestParameters: AddUserToProjectApiV1IamUsersProjectsProjectIdUsersUserIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling addUserToProjectApiV1IamUsersProjectsProjectIdUsersUserIdPost().'
            );
        }

        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling addUserToProjectApiV1IamUsersProjectsProjectIdUsersUserIdPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/iam/users/projects/{project_id}/users/{user_id}`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));
        urlPath = urlPath.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Add a user to a project (membership only, no role assignment).  User must have ADMIN permission in the project.
     * Add User To Project
     */
    async addUserToProjectApiV1IamUsersProjectsProjectIdUsersUserIdPost(requestParameters: AddUserToProjectApiV1IamUsersProjectsProjectIdUsersUserIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.addUserToProjectApiV1IamUsersProjectsProjectIdUsersUserIdPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Change Password
     */
    async changePasswordApiV1IamUsersMePasswordPutRaw(requestParameters: ChangePasswordApiV1IamUsersMePasswordPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['changePasswordRequest'] == null) {
            throw new runtime.RequiredError(
                'changePasswordRequest',
                'Required parameter "changePasswordRequest" was null or undefined when calling changePasswordApiV1IamUsersMePasswordPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/iam/users/me/password`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ChangePasswordRequestToJSON(requestParameters['changePasswordRequest']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Change Password
     */
    async changePasswordApiV1IamUsersMePasswordPut(requestParameters: ChangePasswordApiV1IamUsersMePasswordPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.changePasswordApiV1IamUsersMePasswordPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Deactivate the current user\'s account.  Only the user can deactivate their own account. This sets the user\'s is_active flag to False.
     * Deactivate Current User
     */
    async deactivateCurrentUserApiV1IamUsersMeDeleteRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/iam/users/me`;

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Deactivate the current user\'s account.  Only the user can deactivate their own account. This sets the user\'s is_active flag to False.
     * Deactivate Current User
     */
    async deactivateCurrentUserApiV1IamUsersMeDelete(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.deactivateCurrentUserApiV1IamUsersMeDeleteRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get current user\'s profile information.
     * Get Current User Profile
     */
    async getCurrentUserProfileApiV1IamUsersMeGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/iam/users/me`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserResponseFromJSON(jsonValue));
    }

    /**
     * Get current user\'s profile information.
     * Get Current User Profile
     */
    async getCurrentUserProfileApiV1IamUsersMeGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserResponse> {
        const response = await this.getCurrentUserProfileApiV1IamUsersMeGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Impersonate a user.  This endpoint does not require authentication.
     * Impersonate
     */
    async impersonateApiV1IamUsersImpersonatePostRaw(requestParameters: ImpersonateApiV1IamUsersImpersonatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['impersonateRequest'] == null) {
            throw new runtime.RequiredError(
                'impersonateRequest',
                'Required parameter "impersonateRequest" was null or undefined when calling impersonateApiV1IamUsersImpersonatePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/iam/users/impersonate`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ImpersonateRequestToJSON(requestParameters['impersonateRequest']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Impersonate a user.  This endpoint does not require authentication.
     * Impersonate
     */
    async impersonateApiV1IamUsersImpersonatePost(requestParameters: ImpersonateApiV1IamUsersImpersonatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.impersonateApiV1IamUsersImpersonatePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Invalidate User Cache
     */
    async invalidateUserCacheApiV1IamUsersInvalidateCachePostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/iam/users/invalidate-cache`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Invalidate User Cache
     */
    async invalidateUserCacheApiV1IamUsersInvalidateCachePost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.invalidateUserCacheApiV1IamUsersInvalidateCachePostRaw(initOverrides);
        return await response.value();
    }

    /**
     * List users in a project.  User must have VIEW_USERS permission in the project or organisation.
     * List Project Users
     */
    async listProjectUsersApiV1IamUsersProjectsProjectIdGetRaw(requestParameters: ListProjectUsersApiV1IamUsersProjectsProjectIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserListResponse>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling listProjectUsersApiV1IamUsersProjectsProjectIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/iam/users/projects/{project_id}`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserListResponseFromJSON(jsonValue));
    }

    /**
     * List users in a project.  User must have VIEW_USERS permission in the project or organisation.
     * List Project Users
     */
    async listProjectUsersApiV1IamUsersProjectsProjectIdGet(requestParameters: ListProjectUsersApiV1IamUsersProjectsProjectIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserListResponse> {
        const response = await this.listProjectUsersApiV1IamUsersProjectsProjectIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Login
     */
    async loginApiV1IamUsersLoginPostRaw(requestParameters: LoginApiV1IamUsersLoginPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OvermindApiV1EndpointsIamUsersLoginResponse>> {
        if (requestParameters['loginRequest'] == null) {
            throw new runtime.RequiredError(
                'loginRequest',
                'Required parameter "loginRequest" was null or undefined when calling loginApiV1IamUsersLoginPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/iam/users/login`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LoginRequestToJSON(requestParameters['loginRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OvermindApiV1EndpointsIamUsersLoginResponseFromJSON(jsonValue));
    }

    /**
     * Login
     */
    async loginApiV1IamUsersLoginPost(requestParameters: LoginApiV1IamUsersLoginPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OvermindApiV1EndpointsIamUsersLoginResponse> {
        const response = await this.loginApiV1IamUsersLoginPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Remove a user from a project.  User must have REMOVE_USERS permission in the project or organisation. Cannot remove yourself if you\'re the only admin.
     * Remove User From Project
     */
    async removeUserFromProjectApiV1IamUsersProjectsProjectIdUsersUserIdDeleteRaw(requestParameters: RemoveUserFromProjectApiV1IamUsersProjectsProjectIdUsersUserIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling removeUserFromProjectApiV1IamUsersProjectsProjectIdUsersUserIdDelete().'
            );
        }

        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling removeUserFromProjectApiV1IamUsersProjectsProjectIdUsersUserIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/iam/users/projects/{project_id}/users/{user_id}`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));
        urlPath = urlPath.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Remove a user from a project.  User must have REMOVE_USERS permission in the project or organisation. Cannot remove yourself if you\'re the only admin.
     * Remove User From Project
     */
    async removeUserFromProjectApiV1IamUsersProjectsProjectIdUsersUserIdDelete(requestParameters: RemoveUserFromProjectApiV1IamUsersProjectsProjectIdUsersUserIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.removeUserFromProjectApiV1IamUsersProjectsProjectIdUsersUserIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
