/* tslint:disable */
/* eslint-disable */
/**
 * Overbae API
 * Backend API for the Overclaw / Overmind platform.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PermissionEnum } from './PermissionEnum';
import {
    PermissionEnumFromJSON,
    PermissionEnumFromJSONTyped,
    PermissionEnumToJSON,
    PermissionEnumToJSONTyped,
} from './PermissionEnum';
import type { APITokenScopeScopeEnum } from './APITokenScopeScopeEnum';
import {
    APITokenScopeScopeEnumFromJSON,
    APITokenScopeScopeEnumFromJSONTyped,
    APITokenScopeScopeEnumToJSON,
    APITokenScopeScopeEnumToJSONTyped,
} from './APITokenScopeScopeEnum';

/**
 *
 * @export
 * @interface APITokenScope
 */
export interface APITokenScope {
    /**
     *
     * @type {APITokenScopeScopeEnum}
     * @memberof APITokenScope
     */
    scope: APITokenScopeScopeEnum;
    /**
     *
     * @type {Array<string>}
     * @memberof APITokenScope
     */
    resourceIds?: Array<string>;
    /**
     *
     * @type {Array<PermissionEnum>}
     * @memberof APITokenScope
     */
    permission?: Array<PermissionEnum>;
}



/**
 * Check if a given object implements the APITokenScope interface.
 */
export function instanceOfAPITokenScope(value: object): value is APITokenScope {
    if (!('scope' in value) || value['scope'] === undefined) return false;
    return true;
}

export function APITokenScopeFromJSON(json: any): APITokenScope {
    return APITokenScopeFromJSONTyped(json, false);
}

export function APITokenScopeFromJSONTyped(json: any, ignoreDiscriminator: boolean): APITokenScope {
    if (json == null) {
        return json;
    }
    return {

        'scope': APITokenScopeScopeEnumFromJSON(json['scope']),
        'resourceIds': json['resourceIds'] == null ? undefined : json['resourceIds'],
        'permission': json['permission'] == null ? undefined : ((json['permission'] as Array<any>).map(PermissionEnumFromJSON)),
    };
}

export function APITokenScopeToJSON(json: any): APITokenScope {
    return APITokenScopeToJSONTyped(json, false);
}

export function APITokenScopeToJSONTyped(value?: APITokenScope | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'scope': APITokenScopeScopeEnumToJSON(value['scope']),
        'resourceIds': value['resourceIds'],
        'permission': value['permission'] == null ? undefined : ((value['permission'] as Array<any>).map(PermissionEnumToJSON)),
    };
}
