/* tslint:disable */
/* eslint-disable */
/**
 * Overbae API
 * Backend API for the Overclaw / Overmind platform.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `unknown` - Unknown
 * * `v1` - v1 traces
 * * `v2` - v2 observations
 * @export
 */
export const ApiVersionEnum = {
    unknown: 'unknown',
    v1: 'v1',
    v2: 'v2'
} as const;
export type ApiVersionEnum = typeof ApiVersionEnum[keyof typeof ApiVersionEnum];


export function instanceOfApiVersionEnum(value: any): boolean {
    for (const key in ApiVersionEnum) {
        if (Object.prototype.hasOwnProperty.call(ApiVersionEnum, key)) {
            if (ApiVersionEnum[key as keyof typeof ApiVersionEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ApiVersionEnumFromJSON(json: any): ApiVersionEnum {
    return ApiVersionEnumFromJSONTyped(json, false);
}

export function ApiVersionEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiVersionEnum {
    return json as ApiVersionEnum;
}

export function ApiVersionEnumToJSON(value?: ApiVersionEnum | null): any {
    return value as any;
}

export function ApiVersionEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): ApiVersionEnum {
    return value as ApiVersionEnum;
}
