/* tslint:disable */
/* eslint-disable */
/**
 * Overbae API
 * Backend API for the Overclaw / Overmind platform.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BehaviourAuthoringStep } from './BehaviourAuthoringStep';
import {
    BehaviourAuthoringStepFromJSON,
    BehaviourAuthoringStepFromJSONTyped,
    BehaviourAuthoringStepToJSON,
    BehaviourAuthoringStepToJSONTyped,
} from './BehaviourAuthoringStep';
import type { BehaviourTool } from './BehaviourTool';
import {
    BehaviourToolFromJSON,
    BehaviourToolFromJSONTyped,
    BehaviourToolToJSON,
    BehaviourToolToJSONTyped,
} from './BehaviourTool';

/**
 *
 * @export
 * @interface BehaviourAuthoringContract
 */
export interface BehaviourAuthoringContract {
    /**
     *
     * @type {Array<string>}
     * @memberof BehaviourAuthoringContract
     */
    anchorSequence: Array<string>;
    /**
     *
     * @type {Array<BehaviourAuthoringStep>}
     * @memberof BehaviourAuthoringContract
     */
    steps: Array<BehaviourAuthoringStep>;
    /**
     *
     * @type {Array<BehaviourTool>}
     * @memberof BehaviourAuthoringContract
     */
    toolSet: Array<BehaviourTool>;
    /**
     *
     * @type {any}
     * @memberof BehaviourAuthoringContract
     */
    terminal: any | null;
}

/**
 * Check if a given object implements the BehaviourAuthoringContract interface.
 */
export function instanceOfBehaviourAuthoringContract(value: object): value is BehaviourAuthoringContract {
    if (!('anchorSequence' in value) || value['anchorSequence'] === undefined) return false;
    if (!('steps' in value) || value['steps'] === undefined) return false;
    if (!('toolSet' in value) || value['toolSet'] === undefined) return false;
    if (!('terminal' in value) || value['terminal'] === undefined) return false;
    return true;
}

export function BehaviourAuthoringContractFromJSON(json: any): BehaviourAuthoringContract {
    return BehaviourAuthoringContractFromJSONTyped(json, false);
}

export function BehaviourAuthoringContractFromJSONTyped(json: any, ignoreDiscriminator: boolean): BehaviourAuthoringContract {
    if (json == null) {
        return json;
    }
    return {

        'anchorSequence': json['anchor_sequence'],
        'steps': ((json['steps'] as Array<any>).map(BehaviourAuthoringStepFromJSON)),
        'toolSet': ((json['tool_set'] as Array<any>).map(BehaviourToolFromJSON)),
        'terminal': json['terminal'],
    };
}

export function BehaviourAuthoringContractToJSON(json: any): BehaviourAuthoringContract {
    return BehaviourAuthoringContractToJSONTyped(json, false);
}

export function BehaviourAuthoringContractToJSONTyped(value?: BehaviourAuthoringContract | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'anchor_sequence': value['anchorSequence'],
        'steps': ((value['steps'] as Array<any>).map(BehaviourAuthoringStepToJSON)),
        'tool_set': ((value['toolSet'] as Array<any>).map(BehaviourToolToJSON)),
        'terminal': value['terminal'],
    };
}
