/* tslint:disable */
/* eslint-disable */
/**
 * Overbae API
 * Backend API for the Overclaw / Overmind platform.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CapabilityFlowToolArgument } from './CapabilityFlowToolArgument';
import {
    CapabilityFlowToolArgumentFromJSON,
    CapabilityFlowToolArgumentFromJSONTyped,
    CapabilityFlowToolArgumentToJSON,
    CapabilityFlowToolArgumentToJSONTyped,
} from './CapabilityFlowToolArgument';

/**
 *
 * @export
 * @interface CapabilityFlowTool
 */
export interface CapabilityFlowTool {
    /**
     *
     * @type {string}
     * @memberof CapabilityFlowTool
     */
    name: string;
    /**
     *
     * @type {string}
     * @memberof CapabilityFlowTool
     */
    purpose: string;
    /**
     *
     * @type {string}
     * @memberof CapabilityFlowTool
     */
    args: string;
    /**
     *
     * @type {string}
     * @memberof CapabilityFlowTool
     */
    sideEffect?: string;
    /**
     *
     * @type {string}
     * @memberof CapabilityFlowTool
     */
    returns?: string;
    /**
     *
     * @type {Array<CapabilityFlowToolArgument>}
     * @memberof CapabilityFlowTool
     */
    arguments?: Array<CapabilityFlowToolArgument>;
    /**
     *
     * @type {string}
     * @memberof CapabilityFlowTool
     */
    integration?: string;
    /**
     *
     * @type {string}
     * @memberof CapabilityFlowTool
     */
    cluster?: string;
    /**
     *
     * @type {Array<string>}
     * @memberof CapabilityFlowTool
     */
    provenance?: Array<string>;
}

/**
 * Check if a given object implements the CapabilityFlowTool interface.
 */
export function instanceOfCapabilityFlowTool(value: object): value is CapabilityFlowTool {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('purpose' in value) || value['purpose'] === undefined) return false;
    if (!('args' in value) || value['args'] === undefined) return false;
    return true;
}

export function CapabilityFlowToolFromJSON(json: any): CapabilityFlowTool {
    return CapabilityFlowToolFromJSONTyped(json, false);
}

export function CapabilityFlowToolFromJSONTyped(json: any, ignoreDiscriminator: boolean): CapabilityFlowTool {
    if (json == null) {
        return json;
    }
    return {

        'name': json['name'],
        'purpose': json['purpose'],
        'args': json['args'],
        'sideEffect': json['side_effect'] == null ? undefined : json['side_effect'],
        'returns': json['returns'] == null ? undefined : json['returns'],
        'arguments': json['arguments'] == null ? undefined : ((json['arguments'] as Array<any>).map(CapabilityFlowToolArgumentFromJSON)),
        'integration': json['integration'] == null ? undefined : json['integration'],
        'cluster': json['cluster'] == null ? undefined : json['cluster'],
        'provenance': json['provenance'] == null ? undefined : json['provenance'],
    };
}

export function CapabilityFlowToolToJSON(json: any): CapabilityFlowTool {
    return CapabilityFlowToolToJSONTyped(json, false);
}

export function CapabilityFlowToolToJSONTyped(value?: CapabilityFlowTool | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'name': value['name'],
        'purpose': value['purpose'],
        'args': value['args'],
        'side_effect': value['sideEffect'],
        'returns': value['returns'],
        'arguments': value['arguments'] == null ? undefined : ((value['arguments'] as Array<any>).map(CapabilityFlowToolArgumentToJSON)),
        'integration': value['integration'],
        'cluster': value['cluster'],
        'provenance': value['provenance'],
    };
}
