/* tslint:disable */
/* eslint-disable */
/**
 * Overbae API
 * Backend API for the Overclaw / Overmind platform.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ChatGPTStartRequestRequest
 */
export interface ChatGPTStartRequestRequest {
    /**
     *
     * @type {string}
     * @memberof ChatGPTStartRequestRequest
     */
    accountId?: string | null;
}

/**
 * Check if a given object implements the ChatGPTStartRequestRequest interface.
 */
export function instanceOfChatGPTStartRequestRequest(value: object): value is ChatGPTStartRequestRequest {
    return true;
}

export function ChatGPTStartRequestRequestFromJSON(json: any): ChatGPTStartRequestRequest {
    return ChatGPTStartRequestRequestFromJSONTyped(json, false);
}

export function ChatGPTStartRequestRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatGPTStartRequestRequest {
    if (json == null) {
        return json;
    }
    return {

        'accountId': json['account_id'] == null ? undefined : json['account_id'],
    };
}

export function ChatGPTStartRequestRequestToJSON(json: any): ChatGPTStartRequestRequest {
    return ChatGPTStartRequestRequestToJSONTyped(json, false);
}

export function ChatGPTStartRequestRequestToJSONTyped(value?: ChatGPTStartRequestRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'account_id': value['accountId'],
    };
}
