/* tslint:disable */
/* eslint-disable */
/**
 * Overbae API
 * Backend API for the Overclaw / Overmind platform.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FundingSourceEnum } from './FundingSourceEnum';
import {
    FundingSourceEnumFromJSON,
    FundingSourceEnumFromJSONTyped,
    FundingSourceEnumToJSON,
    FundingSourceEnumToJSONTyped,
} from './FundingSourceEnum';
import type { IntentChoiceEnum } from './IntentChoiceEnum';
import {
    IntentChoiceEnumFromJSON,
    IntentChoiceEnumFromJSONTyped,
    IntentChoiceEnumToJSON,
    IntentChoiceEnumToJSONTyped,
} from './IntentChoiceEnum';
import type { ChatTurnStatusEnum } from './ChatTurnStatusEnum';
import {
    ChatTurnStatusEnumFromJSON,
    ChatTurnStatusEnumFromJSONTyped,
    ChatTurnStatusEnumToJSON,
    ChatTurnStatusEnumToJSONTyped,
} from './ChatTurnStatusEnum';
import type { ChatTurnRoleEnum } from './ChatTurnRoleEnum';
import {
    ChatTurnRoleEnumFromJSON,
    ChatTurnRoleEnumFromJSONTyped,
    ChatTurnRoleEnumToJSON,
    ChatTurnRoleEnumToJSONTyped,
} from './ChatTurnRoleEnum';

/**
 *
 * @export
 * @interface ChatTurn
 */
export interface ChatTurn {
    /**
     *
     * @type {FundingSourceEnum}
     * @memberof ChatTurn
     */
    fundingSource?: FundingSourceEnum;
    /**
     *
     * @type {string}
     * @memberof ChatTurn
     */
    model?: string;
    /**
     *
     * @type {string}
     * @memberof ChatTurn
     */
    engine?: string;
    /**
     *
     * @type {string}
     * @memberof ChatTurn
     */
    id?: string;
    /**
     *
     * @type {ChatTurnRoleEnum}
     * @memberof ChatTurn
     */
    role: ChatTurnRoleEnum;
    /**
     *
     * @type {string}
     * @memberof ChatTurn
     */
    text: string;
    /**
     *
     * @type {string}
     * @memberof ChatTurn
     */
    error?: string;
    /**
     *
     * @type {Array<any>}
     * @memberof ChatTurn
     */
    cells?: Array<any>;
    /**
     *
     * @type {Array<any>}
     * @memberof ChatTurn
     */
    steps?: Array<any>;
    /**
     *
     * @type {number}
     * @memberof ChatTurn
     */
    ms?: number;
    /**
     *
     * @type {ChatTurnStatusEnum}
     * @memberof ChatTurn
     */
    status?: ChatTurnStatusEnum;
    /**
     *
     * @type {IntentChoiceEnum}
     * @memberof ChatTurn
     */
    intentChoice?: IntentChoiceEnum;
    /**
     *
     * @type {any}
     * @memberof ChatTurn
     */
    progress?: any | null;
    /**
     *
     * @type {string}
     * @memberof ChatTurn
     */
    at: string;
}



/**
 * Check if a given object implements the ChatTurn interface.
 */
export function instanceOfChatTurn(value: object): value is ChatTurn {
    if (!('role' in value) || value['role'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    if (!('at' in value) || value['at'] === undefined) return false;
    return true;
}

export function ChatTurnFromJSON(json: any): ChatTurn {
    return ChatTurnFromJSONTyped(json, false);
}

export function ChatTurnFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatTurn {
    if (json == null) {
        return json;
    }
    return {

        'fundingSource': json['funding_source'] == null ? undefined : FundingSourceEnumFromJSON(json['funding_source']),
        'model': json['model'] == null ? undefined : json['model'],
        'engine': json['engine'] == null ? undefined : json['engine'],
        'id': json['id'] == null ? undefined : json['id'],
        'role': ChatTurnRoleEnumFromJSON(json['role']),
        'text': json['text'],
        'error': json['error'] == null ? undefined : json['error'],
        'cells': json['cells'] == null ? undefined : json['cells'],
        'steps': json['steps'] == null ? undefined : json['steps'],
        'ms': json['ms'] == null ? undefined : json['ms'],
        'status': json['status'] == null ? undefined : ChatTurnStatusEnumFromJSON(json['status']),
        'intentChoice': json['intent_choice'] == null ? undefined : IntentChoiceEnumFromJSON(json['intent_choice']),
        'progress': json['progress'] == null ? undefined : json['progress'],
        'at': json['at'],
    };
}

export function ChatTurnToJSON(json: any): ChatTurn {
    return ChatTurnToJSONTyped(json, false);
}

export function ChatTurnToJSONTyped(value?: ChatTurn | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'funding_source': FundingSourceEnumToJSON(value['fundingSource']),
        'model': value['model'],
        'engine': value['engine'],
        'id': value['id'],
        'role': ChatTurnRoleEnumToJSON(value['role']),
        'text': value['text'],
        'error': value['error'],
        'cells': value['cells'],
        'steps': value['steps'],
        'ms': value['ms'],
        'status': ChatTurnStatusEnumToJSON(value['status']),
        'intent_choice': IntentChoiceEnumToJSON(value['intentChoice']),
        'progress': value['progress'],
        'at': value['at'],
    };
}
