/* tslint:disable */
/* eslint-disable */
/**
 * Overbae API
 * Backend API for the Overclaw / Overmind platform.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ConnectorCredentialsSyncCreate202Response
 */
export interface ConnectorCredentialsSyncCreate202Response {
    /**
     *
     * @type {string}
     * @memberof ConnectorCredentialsSyncCreate202Response
     */
    status?: string;
}

/**
 * Check if a given object implements the ConnectorCredentialsSyncCreate202Response interface.
 */
export function instanceOfConnectorCredentialsSyncCreate202Response(value: object): value is ConnectorCredentialsSyncCreate202Response {
    return true;
}

export function ConnectorCredentialsSyncCreate202ResponseFromJSON(json: any): ConnectorCredentialsSyncCreate202Response {
    return ConnectorCredentialsSyncCreate202ResponseFromJSONTyped(json, false);
}

export function ConnectorCredentialsSyncCreate202ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConnectorCredentialsSyncCreate202Response {
    if (json == null) {
        return json;
    }
    return {

        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function ConnectorCredentialsSyncCreate202ResponseToJSON(json: any): ConnectorCredentialsSyncCreate202Response {
    return ConnectorCredentialsSyncCreate202ResponseToJSONTyped(json, false);
}

export function ConnectorCredentialsSyncCreate202ResponseToJSONTyped(value?: ConnectorCredentialsSyncCreate202Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'status': value['status'],
    };
}
