/* tslint:disable */
/* eslint-disable */
/**
 * Overbae API
 * Backend API for the Overclaw / Overmind platform.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ConnectorPreviewRequestRequest
 */
export interface ConnectorPreviewRequestRequest {
    /**
     *
     * @type {number}
     * @memberof ConnectorPreviewRequestRequest
     */
    lookbackDays?: number | null;
    /**
     *
     * @type {string}
     * @memberof ConnectorPreviewRequestRequest
     */
    sourceProjectId?: string;
    /**
     *
     * @type {Date}
     * @memberof ConnectorPreviewRequestRequest
     */
    backfillFrom?: Date | null;
    /**
     *
     * @type {Date}
     * @memberof ConnectorPreviewRequestRequest
     */
    backfillTo?: Date | null;
}

/**
 * Check if a given object implements the ConnectorPreviewRequestRequest interface.
 */
export function instanceOfConnectorPreviewRequestRequest(value: object): value is ConnectorPreviewRequestRequest {
    return true;
}

export function ConnectorPreviewRequestRequestFromJSON(json: any): ConnectorPreviewRequestRequest {
    return ConnectorPreviewRequestRequestFromJSONTyped(json, false);
}

export function ConnectorPreviewRequestRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConnectorPreviewRequestRequest {
    if (json == null) {
        return json;
    }
    return {

        'lookbackDays': json['lookback_days'] == null ? undefined : json['lookback_days'],
        'sourceProjectId': json['source_project_id'] == null ? undefined : json['source_project_id'],
        'backfillFrom': json['backfill_from'] == null ? undefined : (new Date(json['backfill_from'])),
        'backfillTo': json['backfill_to'] == null ? undefined : (new Date(json['backfill_to'])),
    };
}

export function ConnectorPreviewRequestRequestToJSON(json: any): ConnectorPreviewRequestRequest {
    return ConnectorPreviewRequestRequestToJSONTyped(json, false);
}

export function ConnectorPreviewRequestRequestToJSONTyped(value?: ConnectorPreviewRequestRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'lookback_days': value['lookbackDays'],
        'source_project_id': value['sourceProjectId'],
        'backfill_from': value['backfillFrom'] == null ? value['backfillFrom'] : value['backfillFrom'].toISOString(),
        'backfill_to': value['backfillTo'] == null ? value['backfillTo'] : value['backfillTo'].toISOString(),
    };
}
