/* tslint:disable */
/* eslint-disable */
/**
 * Overbae API
 * Backend API for the Overclaw / Overmind platform.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `observation_name` - observation_name
 * * `metadata` - metadata
 * * `tag` - tag
 * * `trace_name` - trace_name
 * @export
 */
export const ConnectorCapabilityMappingWriteSourceEnum = {
    observation_name: 'observation_name',
    metadata: 'metadata',
    tag: 'tag',
    trace_name: 'trace_name'
} as const;
export type ConnectorCapabilityMappingWriteSourceEnum = typeof ConnectorCapabilityMappingWriteSourceEnum[keyof typeof ConnectorCapabilityMappingWriteSourceEnum];


export function instanceOfConnectorCapabilityMappingWriteSourceEnum(value: any): boolean {
    for (const key in ConnectorCapabilityMappingWriteSourceEnum) {
        if (Object.prototype.hasOwnProperty.call(ConnectorCapabilityMappingWriteSourceEnum, key)) {
            if (ConnectorCapabilityMappingWriteSourceEnum[key as keyof typeof ConnectorCapabilityMappingWriteSourceEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ConnectorCapabilityMappingWriteSourceEnumFromJSON(json: any): ConnectorCapabilityMappingWriteSourceEnum {
    return ConnectorCapabilityMappingWriteSourceEnumFromJSONTyped(json, false);
}

export function ConnectorCapabilityMappingWriteSourceEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConnectorCapabilityMappingWriteSourceEnum {
    return json as ConnectorCapabilityMappingWriteSourceEnum;
}

export function ConnectorCapabilityMappingWriteSourceEnumToJSON(value?: ConnectorCapabilityMappingWriteSourceEnum | null): any {
    return value as any;
}

export function ConnectorCapabilityMappingWriteSourceEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): ConnectorCapabilityMappingWriteSourceEnum {
    return value as ConnectorCapabilityMappingWriteSourceEnum;
}
