/* tslint:disable */
/* eslint-disable */
/**
 * Overbae API
 * Backend API for the Overclaw / Overmind platform.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ConnectorCapabilities
 */
export interface ConnectorCapabilities {
    /**
     *
     * @type {boolean}
     * @memberof ConnectorCapabilities
     */
    exactCount: boolean;
    /**
     *
     * @type {Array<string>}
     * @memberof ConnectorCapabilities
     */
    capabilitySources: Array<string>;
    /**
     *
     * @type {boolean}
     * @memberof ConnectorCapabilities
     */
    needsSourceProject: boolean;
    /**
     *
     * @type {string}
     * @memberof ConnectorCapabilities
     */
    retentionNote?: string;
}

/**
 * Check if a given object implements the ConnectorCapabilities interface.
 */
export function instanceOfConnectorCapabilities(value: object): value is ConnectorCapabilities {
    if (!('exactCount' in value) || value['exactCount'] === undefined) return false;
    if (!('capabilitySources' in value) || value['capabilitySources'] === undefined) return false;
    if (!('needsSourceProject' in value) || value['needsSourceProject'] === undefined) return false;
    return true;
}

export function ConnectorCapabilitiesFromJSON(json: any): ConnectorCapabilities {
    return ConnectorCapabilitiesFromJSONTyped(json, false);
}

export function ConnectorCapabilitiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConnectorCapabilities {
    if (json == null) {
        return json;
    }
    return {

        'exactCount': json['exact_count'],
        'capabilitySources': json['capability_sources'],
        'needsSourceProject': json['needs_source_project'],
        'retentionNote': json['retention_note'] == null ? undefined : json['retention_note'],
    };
}

export function ConnectorCapabilitiesToJSON(json: any): ConnectorCapabilities {
    return ConnectorCapabilitiesToJSONTyped(json, false);
}

export function ConnectorCapabilitiesToJSONTyped(value?: ConnectorCapabilities | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'exact_count': value['exactCount'],
        'capability_sources': value['capabilitySources'],
        'needs_source_project': value['needsSourceProject'],
        'retention_note': value['retentionNote'],
    };
}
