/* tslint:disable */
/* eslint-disable */
/**
 * Overbae API
 * Backend API for the Overclaw / Overmind platform.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CandidateInputRequest } from './CandidateInputRequest';
import {
    CandidateInputRequestFromJSON,
    CandidateInputRequestFromJSONTyped,
    CandidateInputRequestToJSON,
    CandidateInputRequestToJSONTyped,
} from './CandidateInputRequest';

/**
 *
 * @export
 * @interface CreateIterationRequest
 */
export interface CreateIterationRequest {
    /**
     *
     * @type {number}
     * @memberof CreateIterationRequest
     */
    order: number;
    /**
     *
     * @type {string}
     * @memberof CreateIterationRequest
     */
    name?: string;
    /**
     *
     * @type {Array<CandidateInputRequest>}
     * @memberof CreateIterationRequest
     */
    candidates: Array<CandidateInputRequest>;
}

/**
 * Check if a given object implements the CreateIterationRequest interface.
 */
export function instanceOfCreateIterationRequest(value: object): value is CreateIterationRequest {
    if (!('order' in value) || value['order'] === undefined) return false;
    if (!('candidates' in value) || value['candidates'] === undefined) return false;
    return true;
}

export function CreateIterationRequestFromJSON(json: any): CreateIterationRequest {
    return CreateIterationRequestFromJSONTyped(json, false);
}

export function CreateIterationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateIterationRequest {
    if (json == null) {
        return json;
    }
    return {

        'order': json['order'],
        'name': json['name'] == null ? undefined : json['name'],
        'candidates': ((json['candidates'] as Array<any>).map(CandidateInputRequestFromJSON)),
    };
}

export function CreateIterationRequestToJSON(json: any): CreateIterationRequest {
    return CreateIterationRequestToJSONTyped(json, false);
}

export function CreateIterationRequestToJSONTyped(value?: CreateIterationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'order': value['order'],
        'name': value['name'],
        'candidates': ((value['candidates'] as Array<any>).map(CandidateInputRequestToJSON)),
    };
}
