/* tslint:disable */
/* eslint-disable */
/**
 * Overbae API
 * Backend API for the Overclaw / Overmind platform.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `landing` - Landing
 * * `diagnosing` - Diagnosing
 * * `idle` - Idle
 * * `running` - Running
 * * `error` - Error
 * @export
 */
export const DatasetStateEnum = {
    landing: 'landing',
    diagnosing: 'diagnosing',
    idle: 'idle',
    running: 'running',
    error: 'error'
} as const;
export type DatasetStateEnum = typeof DatasetStateEnum[keyof typeof DatasetStateEnum];


export function instanceOfDatasetStateEnum(value: any): boolean {
    for (const key in DatasetStateEnum) {
        if (Object.prototype.hasOwnProperty.call(DatasetStateEnum, key)) {
            if (DatasetStateEnum[key as keyof typeof DatasetStateEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function DatasetStateEnumFromJSON(json: any): DatasetStateEnum {
    return DatasetStateEnumFromJSONTyped(json, false);
}

export function DatasetStateEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): DatasetStateEnum {
    return json as DatasetStateEnum;
}

export function DatasetStateEnumToJSON(value?: DatasetStateEnum | null): any {
    return value as any;
}

export function DatasetStateEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): DatasetStateEnum {
    return value as DatasetStateEnum;
}
