/* tslint:disable */
/* eslint-disable */
/**
 * Overbae API
 * Backend API for the Overclaw / Overmind platform.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DatasetValidationStats } from './DatasetValidationStats';
import {
    DatasetValidationStatsFromJSON,
    DatasetValidationStatsFromJSONTyped,
    DatasetValidationStatsToJSON,
    DatasetValidationStatsToJSONTyped,
} from './DatasetValidationStats';

/**
 * Mirrors ``ValidationResult.as_dict()``.
 * @export
 * @interface DatasetValidationResponse
 */
export interface DatasetValidationResponse {
    /**
     *
     * @type {boolean}
     * @memberof DatasetValidationResponse
     */
    valid: boolean;
    /**
     *
     * @type {string}
     * @memberof DatasetValidationResponse
     */
    format: string;
    /**
     *
     * @type {number}
     * @memberof DatasetValidationResponse
     */
    numExamples: number;
    /**
     *
     * @type {Array<string>}
     * @memberof DatasetValidationResponse
     */
    errors: Array<string>;
    /**
     *
     * @type {Array<string>}
     * @memberof DatasetValidationResponse
     */
    warnings: Array<string>;
    /**
     *
     * @type {DatasetValidationStats}
     * @memberof DatasetValidationResponse
     */
    stats: DatasetValidationStats;
}

/**
 * Check if a given object implements the DatasetValidationResponse interface.
 */
export function instanceOfDatasetValidationResponse(value: object): value is DatasetValidationResponse {
    if (!('valid' in value) || value['valid'] === undefined) return false;
    if (!('format' in value) || value['format'] === undefined) return false;
    if (!('numExamples' in value) || value['numExamples'] === undefined) return false;
    if (!('errors' in value) || value['errors'] === undefined) return false;
    if (!('warnings' in value) || value['warnings'] === undefined) return false;
    if (!('stats' in value) || value['stats'] === undefined) return false;
    return true;
}

export function DatasetValidationResponseFromJSON(json: any): DatasetValidationResponse {
    return DatasetValidationResponseFromJSONTyped(json, false);
}

export function DatasetValidationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DatasetValidationResponse {
    if (json == null) {
        return json;
    }
    return {

        'valid': json['valid'],
        'format': json['format'],
        'numExamples': json['num_examples'],
        'errors': json['errors'],
        'warnings': json['warnings'],
        'stats': DatasetValidationStatsFromJSON(json['stats']),
    };
}

export function DatasetValidationResponseToJSON(json: any): DatasetValidationResponse {
    return DatasetValidationResponseToJSONTyped(json, false);
}

export function DatasetValidationResponseToJSONTyped(value?: DatasetValidationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'valid': value['valid'],
        'format': value['format'],
        'num_examples': value['numExamples'],
        'errors': value['errors'],
        'warnings': value['warnings'],
        'stats': DatasetValidationStatsToJSON(value['stats']),
    };
}
