/* tslint:disable */
/* eslint-disable */
/**
 * Overbae API
 * Backend API for the Overclaw / Overmind platform.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `file` - File
 * * `traces` - Traces
 * * `llm_calls` - Llm Calls
 * @export
 */
export const DatasetSourceKindEnum = {
    file: 'file',
    traces: 'traces',
    llm_calls: 'llm_calls'
} as const;
export type DatasetSourceKindEnum = typeof DatasetSourceKindEnum[keyof typeof DatasetSourceKindEnum];


export function instanceOfDatasetSourceKindEnum(value: any): boolean {
    for (const key in DatasetSourceKindEnum) {
        if (Object.prototype.hasOwnProperty.call(DatasetSourceKindEnum, key)) {
            if (DatasetSourceKindEnum[key as keyof typeof DatasetSourceKindEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function DatasetSourceKindEnumFromJSON(json: any): DatasetSourceKindEnum {
    return DatasetSourceKindEnumFromJSONTyped(json, false);
}

export function DatasetSourceKindEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): DatasetSourceKindEnum {
    return json as DatasetSourceKindEnum;
}

export function DatasetSourceKindEnumToJSON(value?: DatasetSourceKindEnum | null): any {
    return value as any;
}

export function DatasetSourceKindEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): DatasetSourceKindEnum {
    return value as DatasetSourceKindEnum;
}
