/* tslint:disable */
/* eslint-disable */
/**
 * Overbae API
 * Backend API for the Overclaw / Overmind platform.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DecisionPolicyBackendEnum } from './DecisionPolicyBackendEnum';
import {
    DecisionPolicyBackendEnumFromJSON,
    DecisionPolicyBackendEnumFromJSONTyped,
    DecisionPolicyBackendEnumToJSON,
    DecisionPolicyBackendEnumToJSONTyped,
} from './DecisionPolicyBackendEnum';

/**
 *
 * @export
 * @interface DecisionPolicyRequest
 */
export interface DecisionPolicyRequest {
    /**
     *
     * @type {DecisionPolicyBackendEnum}
     * @memberof DecisionPolicyRequest
     */
    backend?: DecisionPolicyBackendEnum;
    /**
     *
     * @type {string}
     * @memberof DecisionPolicyRequest
     */
    model?: string;
    /**
     *
     * @type {number}
     * @memberof DecisionPolicyRequest
     */
    minConfidence?: number;
    /**
     *
     * @type {number}
     * @memberof DecisionPolicyRequest
     */
    version?: number;
}



/**
 * Check if a given object implements the DecisionPolicyRequest interface.
 */
export function instanceOfDecisionPolicyRequest(value: object): value is DecisionPolicyRequest {
    return true;
}

export function DecisionPolicyRequestFromJSON(json: any): DecisionPolicyRequest {
    return DecisionPolicyRequestFromJSONTyped(json, false);
}

export function DecisionPolicyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DecisionPolicyRequest {
    if (json == null) {
        return json;
    }
    return {

        'backend': json['backend'] == null ? undefined : DecisionPolicyBackendEnumFromJSON(json['backend']),
        'model': json['model'] == null ? undefined : json['model'],
        'minConfidence': json['min_confidence'] == null ? undefined : json['min_confidence'],
        'version': json['version'] == null ? undefined : json['version'],
    };
}

export function DecisionPolicyRequestToJSON(json: any): DecisionPolicyRequest {
    return DecisionPolicyRequestToJSONTyped(json, false);
}

export function DecisionPolicyRequestToJSONTyped(value?: DecisionPolicyRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'backend': DecisionPolicyBackendEnumToJSON(value['backend']),
        'model': value['model'],
        'min_confidence': value['minConfidence'],
        'version': value['version'],
    };
}
