/* tslint:disable */
/* eslint-disable */
/**
 * Overbae API
 * Backend API for the Overclaw / Overmind platform.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Kind703Enum } from './Kind703Enum';
import {
    Kind703EnumFromJSON,
    Kind703EnumFromJSONTyped,
    Kind703EnumToJSON,
    Kind703EnumToJSONTyped,
} from './Kind703Enum';

/**
 *
 * @export
 * @interface DecisionParticipantRequest
 */
export interface DecisionParticipantRequest {
    /**
     *
     * @type {string}
     * @memberof DecisionParticipantRequest
     */
    key: string;
    /**
     *
     * @type {string}
     * @memberof DecisionParticipantRequest
     */
    name: string;
    /**
     *
     * @type {Kind703Enum}
     * @memberof DecisionParticipantRequest
     */
    kind: Kind703Enum;
    /**
     *
     * @type {string}
     * @memberof DecisionParticipantRequest
     */
    job?: string;
    /**
     *
     * @type {string}
     * @memberof DecisionParticipantRequest
     */
    model?: string;
    /**
     *
     * @type {string}
     * @memberof DecisionParticipantRequest
     */
    servedModel?: string;
}



/**
 * Check if a given object implements the DecisionParticipantRequest interface.
 */
export function instanceOfDecisionParticipantRequest(value: object): value is DecisionParticipantRequest {
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('kind' in value) || value['kind'] === undefined) return false;
    return true;
}

export function DecisionParticipantRequestFromJSON(json: any): DecisionParticipantRequest {
    return DecisionParticipantRequestFromJSONTyped(json, false);
}

export function DecisionParticipantRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DecisionParticipantRequest {
    if (json == null) {
        return json;
    }
    return {

        'key': json['key'],
        'name': json['name'],
        'kind': Kind703EnumFromJSON(json['kind']),
        'job': json['job'] == null ? undefined : json['job'],
        'model': json['model'] == null ? undefined : json['model'],
        'servedModel': json['served_model'] == null ? undefined : json['served_model'],
    };
}

export function DecisionParticipantRequestToJSON(json: any): DecisionParticipantRequest {
    return DecisionParticipantRequestToJSONTyped(json, false);
}

export function DecisionParticipantRequestToJSONTyped(value?: DecisionParticipantRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'key': value['key'],
        'name': value['name'],
        'kind': Kind703EnumToJSON(value['kind']),
        'job': value['job'],
        'model': value['model'],
        'served_model': value['servedModel'],
    };
}
