/* tslint:disable */
/* eslint-disable */
/**
 * Overbae API
 * Backend API for the Overclaw / Overmind platform.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DeployedModelStatusEnum } from './DeployedModelStatusEnum';
import {
    DeployedModelStatusEnumFromJSON,
    DeployedModelStatusEnumFromJSONTyped,
    DeployedModelStatusEnumToJSON,
    DeployedModelStatusEnumToJSONTyped,
} from './DeployedModelStatusEnum';
import type { QuantizationEnum } from './QuantizationEnum';
import {
    QuantizationEnumFromJSON,
    QuantizationEnumFromJSONTyped,
    QuantizationEnumToJSON,
    QuantizationEnumToJSONTyped,
} from './QuantizationEnum';

/**
 *
 * @export
 * @interface DeployedModel
 */
export interface DeployedModel {
    /**
     *
     * @type {string}
     * @memberof DeployedModel
     */
    readonly id: string;
    /**
     *
     * @type {string}
     * @memberof DeployedModel
     */
    readonly project: string;
    /**
     *
     * @type {string}
     * @memberof DeployedModel
     */
    readonly modelId: string;
    /**
     *
     * @type {DeployedModelStatusEnum}
     * @memberof DeployedModel
     */
    readonly status: DeployedModelStatusEnum;
    /**
     *
     * @type {QuantizationEnum}
     * @memberof DeployedModel
     */
    readonly quantization: QuantizationEnum;
    /**
     * Base model ID used for the fine-tuning job.
     * @type {string}
     * @memberof DeployedModel
     */
    readonly baseModelId: string;
    /**
     * Modal GPU type: 'L4' or 'L40S'.
     * @type {string}
     * @memberof DeployedModel
     */
    readonly gpuType: string;
    /**
     *
     * @type {boolean}
     * @memberof DeployedModel
     */
    readonly isLora: boolean;
    /**
     * LoRA rank; 0 for full models.
     * @type {number}
     * @memberof DeployedModel
     */
    readonly loraRank: number;
    /**
     * Path inside the Modal overmind-weights Volume.
     * @type {string}
     * @memberof DeployedModel
     */
    readonly weightsPath: string;
    /**
     * Content hash of the quantized weights directory.
     * @type {string}
     * @memberof DeployedModel
     */
    readonly checkpointHash: string;
    /**
     * Maximum context length passed to vLLM --max-model-len.
     * @type {number}
     * @memberof DeployedModel
     */
    readonly maxModelLen: number;
    /**
     *
     * @type {number}
     * @memberof DeployedModel
     */
    readonly numParameters: number;
    /**
     * 'hot' keeps a warm container alive; 'standard' scales to zero.
     * @type {string}
     * @memberof DeployedModel
     */
    readonly slaTier: string;
    /**
     * Modal web endpoint URL for the model's vLLM container pool.
     * @type {string}
     * @memberof DeployedModel
     */
    readonly inferenceUrl: string;
    /**
     *
     * @type {string}
     * @memberof DeployedModel
     */
    readonly errorMessage: string;
    /**
     *
     * @type {Date}
     * @memberof DeployedModel
     */
    readonly createdAt: Date;
    /**
     *
     * @type {Date}
     * @memberof DeployedModel
     */
    readonly deployedAt: Date | null;
    /**
     *
     * @type {string}
     * @memberof DeployedModel
     */
    readonly finetuningJobId: string;
    /**
     *
     * @type {string}
     * @memberof DeployedModel
     */
    readonly finetuningJobName: string | null;
    /**
     *
     * @type {string}
     * @memberof DeployedModel
     */
    readonly capabilityId: string | null;
    /**
     *
     * @type {string}
     * @memberof DeployedModel
     */
    readonly capabilityName: string | null;
    /**
     *
     * @type {number}
     * @memberof DeployedModel
     */
    readonly requestCount: number;
    /**
     *
     * @type {Date}
     * @memberof DeployedModel
     */
    readonly lastActiveAt: Date | null;
    /**
     *
     * @type {number}
     * @memberof DeployedModel
     */
    readonly totalTokens: number | null;
    /**
     *
     * @type {number}
     * @memberof DeployedModel
     */
    readonly avgTokensPerSecond: number | null;
    /**
     *
     * @type {number}
     * @memberof DeployedModel
     */
    readonly avgLatencyMs: number | null;
    /**
     *
     * @type {number}
     * @memberof DeployedModel
     */
    readonly costTotal: number | null;
    /**
     *
     * @type {number}
     * @memberof DeployedModel
     */
    readonly costThisMonth: number | null;
}



/**
 * Check if a given object implements the DeployedModel interface.
 */
export function instanceOfDeployedModel(value: object): value is DeployedModel {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('project' in value) || value['project'] === undefined) return false;
    if (!('modelId' in value) || value['modelId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('quantization' in value) || value['quantization'] === undefined) return false;
    if (!('baseModelId' in value) || value['baseModelId'] === undefined) return false;
    if (!('gpuType' in value) || value['gpuType'] === undefined) return false;
    if (!('isLora' in value) || value['isLora'] === undefined) return false;
    if (!('loraRank' in value) || value['loraRank'] === undefined) return false;
    if (!('weightsPath' in value) || value['weightsPath'] === undefined) return false;
    if (!('checkpointHash' in value) || value['checkpointHash'] === undefined) return false;
    if (!('maxModelLen' in value) || value['maxModelLen'] === undefined) return false;
    if (!('numParameters' in value) || value['numParameters'] === undefined) return false;
    if (!('slaTier' in value) || value['slaTier'] === undefined) return false;
    if (!('inferenceUrl' in value) || value['inferenceUrl'] === undefined) return false;
    if (!('errorMessage' in value) || value['errorMessage'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('deployedAt' in value) || value['deployedAt'] === undefined) return false;
    if (!('finetuningJobId' in value) || value['finetuningJobId'] === undefined) return false;
    if (!('finetuningJobName' in value) || value['finetuningJobName'] === undefined) return false;
    if (!('capabilityId' in value) || value['capabilityId'] === undefined) return false;
    if (!('capabilityName' in value) || value['capabilityName'] === undefined) return false;
    if (!('requestCount' in value) || value['requestCount'] === undefined) return false;
    if (!('lastActiveAt' in value) || value['lastActiveAt'] === undefined) return false;
    if (!('totalTokens' in value) || value['totalTokens'] === undefined) return false;
    if (!('avgTokensPerSecond' in value) || value['avgTokensPerSecond'] === undefined) return false;
    if (!('avgLatencyMs' in value) || value['avgLatencyMs'] === undefined) return false;
    if (!('costTotal' in value) || value['costTotal'] === undefined) return false;
    if (!('costThisMonth' in value) || value['costThisMonth'] === undefined) return false;
    return true;
}

export function DeployedModelFromJSON(json: any): DeployedModel {
    return DeployedModelFromJSONTyped(json, false);
}

export function DeployedModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeployedModel {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'],
        'project': json['project'],
        'modelId': json['model_id'],
        'status': DeployedModelStatusEnumFromJSON(json['status']),
        'quantization': QuantizationEnumFromJSON(json['quantization']),
        'baseModelId': json['base_model_id'],
        'gpuType': json['gpu_type'],
        'isLora': json['is_lora'],
        'loraRank': json['lora_rank'],
        'weightsPath': json['weights_path'],
        'checkpointHash': json['checkpoint_hash'],
        'maxModelLen': json['max_model_len'],
        'numParameters': json['num_parameters'],
        'slaTier': json['sla_tier'],
        'inferenceUrl': json['inference_url'],
        'errorMessage': json['error_message'],
        'createdAt': (new Date(json['created_at'])),
        'deployedAt': (json['deployed_at'] == null ? null : new Date(json['deployed_at'])),
        'finetuningJobId': json['finetuning_job_id'],
        'finetuningJobName': json['finetuning_job_name'],
        'capabilityId': json['capability_id'],
        'capabilityName': json['capability_name'],
        'requestCount': json['request_count'],
        'lastActiveAt': (json['last_active_at'] == null ? null : new Date(json['last_active_at'])),
        'totalTokens': json['total_tokens'],
        'avgTokensPerSecond': json['avg_tokens_per_second'],
        'avgLatencyMs': json['avg_latency_ms'],
        'costTotal': json['cost_total'],
        'costThisMonth': json['cost_this_month'],
    };
}

export function DeployedModelToJSON(json: any): DeployedModel {
    return DeployedModelToJSONTyped(json, false);
}

export function DeployedModelToJSONTyped(value?: Omit<DeployedModel, 'id'|'project'|'model_id'|'status'|'quantization'|'base_model_id'|'gpu_type'|'is_lora'|'lora_rank'|'weights_path'|'checkpoint_hash'|'max_model_len'|'num_parameters'|'sla_tier'|'inference_url'|'error_message'|'created_at'|'deployed_at'|'finetuning_job_id'|'finetuning_job_name'|'capability_id'|'capability_name'|'request_count'|'last_active_at'|'total_tokens'|'avg_tokens_per_second'|'avg_latency_ms'|'cost_total'|'cost_this_month'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

    };
}
