/* tslint:disable */
/* eslint-disable */
/**
 * Overbae API
 * Backend API for the Overclaw / Overmind platform.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `dataset` - Dataset
 * * `trace_filter` - Trace Filter
 * @export
 */
export const EvalRunDataSourceEnum = {
    dataset: 'dataset',
    trace_filter: 'trace_filter'
} as const;
export type EvalRunDataSourceEnum = typeof EvalRunDataSourceEnum[keyof typeof EvalRunDataSourceEnum];


export function instanceOfEvalRunDataSourceEnum(value: any): boolean {
    for (const key in EvalRunDataSourceEnum) {
        if (Object.prototype.hasOwnProperty.call(EvalRunDataSourceEnum, key)) {
            if (EvalRunDataSourceEnum[key as keyof typeof EvalRunDataSourceEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function EvalRunDataSourceEnumFromJSON(json: any): EvalRunDataSourceEnum {
    return EvalRunDataSourceEnumFromJSONTyped(json, false);
}

export function EvalRunDataSourceEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): EvalRunDataSourceEnum {
    return json as EvalRunDataSourceEnum;
}

export function EvalRunDataSourceEnumToJSON(value?: EvalRunDataSourceEnum | null): any {
    return value as any;
}

export function EvalRunDataSourceEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): EvalRunDataSourceEnum {
    return value as EvalRunDataSourceEnum;
}
