/* tslint:disable */
/* eslint-disable */
/**
 * Overbae API
 * Backend API for the Overclaw / Overmind platform.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface EvaluationContextVariantRequest
 */
export interface EvaluationContextVariantRequest {
    /**
     *
     * @type {string}
     * @memberof EvaluationContextVariantRequest
     */
    modelName?: string;
    /**
     *
     * @type {string}
     * @memberof EvaluationContextVariantRequest
     */
    modelRef?: string | null;
    /**
     *
     * @type {string}
     * @memberof EvaluationContextVariantRequest
     */
    label?: string;
    /**
     *
     * @type {any}
     * @memberof EvaluationContextVariantRequest
     */
    params?: any | null;
    /**
     *
     * @type {number}
     * @memberof EvaluationContextVariantRequest
     */
    outputTokens?: number;
}

/**
 * Check if a given object implements the EvaluationContextVariantRequest interface.
 */
export function instanceOfEvaluationContextVariantRequest(value: object): value is EvaluationContextVariantRequest {
    return true;
}

export function EvaluationContextVariantRequestFromJSON(json: any): EvaluationContextVariantRequest {
    return EvaluationContextVariantRequestFromJSONTyped(json, false);
}

export function EvaluationContextVariantRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EvaluationContextVariantRequest {
    if (json == null) {
        return json;
    }
    return {

        'modelName': json['model_name'] == null ? undefined : json['model_name'],
        'modelRef': json['model_ref'] == null ? undefined : json['model_ref'],
        'label': json['label'] == null ? undefined : json['label'],
        'params': json['params'] == null ? undefined : json['params'],
        'outputTokens': json['output_tokens'] == null ? undefined : json['output_tokens'],
    };
}

export function EvaluationContextVariantRequestToJSON(json: any): EvaluationContextVariantRequest {
    return EvaluationContextVariantRequestToJSONTyped(json, false);
}

export function EvaluationContextVariantRequestToJSONTyped(value?: EvaluationContextVariantRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'model_name': value['modelName'],
        'model_ref': value['modelRef'],
        'label': value['label'],
        'params': value['params'],
        'output_tokens': value['outputTokens'],
    };
}
