/* tslint:disable */
/* eslint-disable */
/**
 * Overbae API
 * Backend API for the Overclaw / Overmind platform.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * ``gen_*`` is the model-under-test's responses, ``eval_*`` the LLM-judge
 * passes. Latency and token fields are null when the provider reported no
 * timing or usage.
 * @export
 * @interface EvalRunOperationalStat
 */
export interface EvalRunOperationalStat {
    /**
     *
     * @type {string}
     * @memberof EvalRunOperationalStat
     */
    variantId: string;
    /**
     *
     * @type {string}
     * @memberof EvalRunOperationalStat
     */
    label: string;
    /**
     *
     * @type {number}
     * @memberof EvalRunOperationalStat
     */
    sampleCount: number;
    /**
     *
     * @type {number}
     * @memberof EvalRunOperationalStat
     */
    genCost: number;
    /**
     *
     * @type {number}
     * @memberof EvalRunOperationalStat
     */
    evalCost: number;
    /**
     *
     * @type {number}
     * @memberof EvalRunOperationalStat
     */
    totalCost: number;
    /**
     *
     * @type {number}
     * @memberof EvalRunOperationalStat
     */
    genLatencyMs: number | null;
    /**
     *
     * @type {number}
     * @memberof EvalRunOperationalStat
     */
    evalLatencyMs: number | null;
    /**
     *
     * @type {number}
     * @memberof EvalRunOperationalStat
     */
    totalTokens: number | null;
}

/**
 * Check if a given object implements the EvalRunOperationalStat interface.
 */
export function instanceOfEvalRunOperationalStat(value: object): value is EvalRunOperationalStat {
    if (!('variantId' in value) || value['variantId'] === undefined) return false;
    if (!('label' in value) || value['label'] === undefined) return false;
    if (!('sampleCount' in value) || value['sampleCount'] === undefined) return false;
    if (!('genCost' in value) || value['genCost'] === undefined) return false;
    if (!('evalCost' in value) || value['evalCost'] === undefined) return false;
    if (!('totalCost' in value) || value['totalCost'] === undefined) return false;
    if (!('genLatencyMs' in value) || value['genLatencyMs'] === undefined) return false;
    if (!('evalLatencyMs' in value) || value['evalLatencyMs'] === undefined) return false;
    if (!('totalTokens' in value) || value['totalTokens'] === undefined) return false;
    return true;
}

export function EvalRunOperationalStatFromJSON(json: any): EvalRunOperationalStat {
    return EvalRunOperationalStatFromJSONTyped(json, false);
}

export function EvalRunOperationalStatFromJSONTyped(json: any, ignoreDiscriminator: boolean): EvalRunOperationalStat {
    if (json == null) {
        return json;
    }
    return {

        'variantId': json['variant_id'],
        'label': json['label'],
        'sampleCount': json['sample_count'],
        'genCost': json['gen_cost'],
        'evalCost': json['eval_cost'],
        'totalCost': json['total_cost'],
        'genLatencyMs': json['gen_latency_ms'],
        'evalLatencyMs': json['eval_latency_ms'],
        'totalTokens': json['total_tokens'],
    };
}

export function EvalRunOperationalStatToJSON(json: any): EvalRunOperationalStat {
    return EvalRunOperationalStatToJSONTyped(json, false);
}

export function EvalRunOperationalStatToJSONTyped(value?: EvalRunOperationalStat | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'variant_id': value['variantId'],
        'label': value['label'],
        'sample_count': value['sampleCount'],
        'gen_cost': value['genCost'],
        'eval_cost': value['evalCost'],
        'total_cost': value['totalCost'],
        'gen_latency_ms': value['genLatencyMs'],
        'eval_latency_ms': value['evalLatencyMs'],
        'total_tokens': value['totalTokens'],
    };
}
