/* tslint:disable */
/* eslint-disable */
/**
 * Overbae API
 * Backend API for the Overclaw / Overmind platform.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EvaluationContextVariantRequest } from './EvaluationContextVariantRequest';
import {
    EvaluationContextVariantRequestFromJSON,
    EvaluationContextVariantRequestFromJSONTyped,
    EvaluationContextVariantRequestToJSON,
    EvaluationContextVariantRequestToJSONTyped,
} from './EvaluationContextVariantRequest';

/**
 *
 * @export
 * @interface EvaluationContextRequestRequest
 */
export interface EvaluationContextRequestRequest {
    /**
     *
     * @type {string}
     * @memberof EvaluationContextRequestRequest
     */
    judgeModel?: EvaluationContextRequestRequestJudgeModelEnum;
    /**
     *
     * @type {string}
     * @memberof EvaluationContextRequestRequest
     */
    project: string;
    /**
     *
     * @type {string}
     * @memberof EvaluationContextRequestRequest
     */
    dataset: string;
    /**
     *
     * @type {string}
     * @memberof EvaluationContextRequestRequest
     */
    cell?: string | null;
    /**
     *
     * @type {string}
     * @memberof EvaluationContextRequestRequest
     */
    evalSet?: string | null;
    /**
     *
     * @type {string}
     * @memberof EvaluationContextRequestRequest
     */
    capability?: string | null;
    /**
     *
     * @type {Array<EvaluationContextVariantRequest>}
     * @memberof EvaluationContextRequestRequest
     */
    variants?: Array<EvaluationContextVariantRequest>;
}


/**
 * @export
 */
export const EvaluationContextRequestRequestJudgeModelEnum = {
    gpt_5_6_luna: 'gpt-5.6-luna',
    gpt_5_6_terra: 'gpt-5.6-terra',
    claude_sonnet_5: 'claude-sonnet-5',
    claude_haiku_4_5: 'claude-haiku-4-5',
    gemini_3_1_pro_preview: 'gemini-3.1-pro-preview',
    gemini_3_8_flash: 'gemini-3.8-flash',
    deepseek_v3_2: 'deepseek-v3.2',
    empty: ''
} as const;
export type EvaluationContextRequestRequestJudgeModelEnum = typeof EvaluationContextRequestRequestJudgeModelEnum[keyof typeof EvaluationContextRequestRequestJudgeModelEnum];


/**
 * Check if a given object implements the EvaluationContextRequestRequest interface.
 */
export function instanceOfEvaluationContextRequestRequest(value: object): value is EvaluationContextRequestRequest {
    if (!('project' in value) || value['project'] === undefined) return false;
    if (!('dataset' in value) || value['dataset'] === undefined) return false;
    return true;
}

export function EvaluationContextRequestRequestFromJSON(json: any): EvaluationContextRequestRequest {
    return EvaluationContextRequestRequestFromJSONTyped(json, false);
}

export function EvaluationContextRequestRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EvaluationContextRequestRequest {
    if (json == null) {
        return json;
    }
    return {

        'judgeModel': json['judge_model'] == null ? undefined : json['judge_model'],
        'project': json['project'],
        'dataset': json['dataset'],
        'cell': json['cell'] == null ? undefined : json['cell'],
        'evalSet': json['eval_set'] == null ? undefined : json['eval_set'],
        'capability': json['capability'] == null ? undefined : json['capability'],
        'variants': json['variants'] == null ? undefined : ((json['variants'] as Array<any>).map(EvaluationContextVariantRequestFromJSON)),
    };
}

export function EvaluationContextRequestRequestToJSON(json: any): EvaluationContextRequestRequest {
    return EvaluationContextRequestRequestToJSONTyped(json, false);
}

export function EvaluationContextRequestRequestToJSONTyped(value?: EvaluationContextRequestRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'judge_model': value['judgeModel'],
        'project': value['project'],
        'dataset': value['dataset'],
        'cell': value['cell'],
        'eval_set': value['evalSet'],
        'capability': value['capability'],
        'variants': value['variants'] == null ? undefined : ((value['variants'] as Array<any>).map(EvaluationContextVariantRequestToJSON)),
    };
}
