/* tslint:disable */
/* eslint-disable */
/**
 * Overbae API
 * Backend API for the Overclaw / Overmind platform.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ExecutionIntent
 */
export interface ExecutionIntent {
    /**
     *
     * @type {string}
     * @memberof ExecutionIntent
     */
    text: string;
    /**
     *
     * @type {string}
     * @memberof ExecutionIntent
     */
    source: string;
    /**
     *
     * @type {string}
     * @memberof ExecutionIntent
     */
    current?: string;
}

/**
 * Check if a given object implements the ExecutionIntent interface.
 */
export function instanceOfExecutionIntent(value: object): value is ExecutionIntent {
    if (!('text' in value) || value['text'] === undefined) return false;
    if (!('source' in value) || value['source'] === undefined) return false;
    return true;
}

export function ExecutionIntentFromJSON(json: any): ExecutionIntent {
    return ExecutionIntentFromJSONTyped(json, false);
}

export function ExecutionIntentFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExecutionIntent {
    if (json == null) {
        return json;
    }
    return {

        'text': json['text'],
        'source': json['source'],
        'current': json['current'] == null ? undefined : json['current'],
    };
}

export function ExecutionIntentToJSON(json: any): ExecutionIntent {
    return ExecutionIntentToJSONTyped(json, false);
}

export function ExecutionIntentToJSONTyped(value?: ExecutionIntent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'text': value['text'],
        'source': value['source'],
        'current': value['current'],
    };
}
