/* tslint:disable */
/* eslint-disable */
/**
 * Overbae API
 * Backend API for the Overclaw / Overmind platform.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SplitMethodEnum } from './SplitMethodEnum';
import {
    SplitMethodEnumFromJSON,
    SplitMethodEnumFromJSONTyped,
    SplitMethodEnumToJSON,
    SplitMethodEnumToJSONTyped,
} from './SplitMethodEnum';

/**
 *
 * @export
 * @interface FinetuningJobRequest
 */
export interface FinetuningJobRequest {
    /**
     *
     * @type {string}
     * @memberof FinetuningJobRequest
     */
    project: string;
    /**
     *
     * @type {string}
     * @memberof FinetuningJobRequest
     */
    capability?: string | null;
    /**
     *
     * @type {string}
     * @memberof FinetuningJobRequest
     */
    dataset: string;
    /**
     *
     * @type {string}
     * @memberof FinetuningJobRequest
     */
    evalDataset: string;
    /**
     *
     * @type {string}
     * @memberof FinetuningJobRequest
     */
    evalCell?: string | null;
    /**
     *
     * @type {string}
     * @memberof FinetuningJobRequest
     */
    evalSet: string;
    /**
     *
     * @type {boolean}
     * @memberof FinetuningJobRequest
     */
    evalIncumbentBefore?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof FinetuningJobRequest
     */
    evalIncumbentAfter?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof FinetuningJobRequest
     */
    evalModelBefore?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof FinetuningJobRequest
     */
    evalModelAfter?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof FinetuningJobRequest
     */
    validationEnabled?: boolean;
    /**
     *
     * @type {number}
     * @memberof FinetuningJobRequest
     */
    validationSplitRatio?: number;
    /**
     *
     * @type {string}
     * @memberof FinetuningJobRequest
     */
    validationDataset?: string | null;
    /**
     *
     * @type {string}
     * @memberof FinetuningJobRequest
     */
    cell?: string | null;
    /**
     *
     * @type {string}
     * @memberof FinetuningJobRequest
     */
    validationCell?: string | null;
    /**
     *
     * @type {SplitMethodEnum}
     * @memberof FinetuningJobRequest
     */
    splitMethod?: SplitMethodEnum;
    /**
     *
     * @type {string}
     * @memberof FinetuningJobRequest
     */
    name?: string;
    /**
     *
     * @type {string}
     * @memberof FinetuningJobRequest
     */
    useCase?: string;
    /**
     *
     * @type {string}
     * @memberof FinetuningJobRequest
     */
    baseModel: string;
    /**
     *
     * @type {string}
     * @memberof FinetuningJobRequest
     */
    baselineModel?: string;
    /**
     *
     * @type {any}
     * @memberof FinetuningJobRequest
     */
    hyperparameters?: any | null;
    /**
     *
     * @type {string}
     * @memberof FinetuningJobRequest
     */
    groupId?: string | null;
    /**
     *
     * @type {string}
     * @memberof FinetuningJobRequest
     */
    modelTier?: FinetuningJobRequestModelTierEnum;
    /**
     *
     * @type {number}
     * @memberof FinetuningJobRequest
     */
    maxRetries?: number;
}


/**
 * @export
 */
export const FinetuningJobRequestModelTierEnum = {
    compact: 'compact',
    small: 'small',
    mid: 'mid',
    large: 'large',
    empty: ''
} as const;
export type FinetuningJobRequestModelTierEnum = typeof FinetuningJobRequestModelTierEnum[keyof typeof FinetuningJobRequestModelTierEnum];


/**
 * Check if a given object implements the FinetuningJobRequest interface.
 */
export function instanceOfFinetuningJobRequest(value: object): value is FinetuningJobRequest {
    if (!('project' in value) || value['project'] === undefined) return false;
    if (!('dataset' in value) || value['dataset'] === undefined) return false;
    if (!('evalDataset' in value) || value['evalDataset'] === undefined) return false;
    if (!('evalSet' in value) || value['evalSet'] === undefined) return false;
    if (!('baseModel' in value) || value['baseModel'] === undefined) return false;
    return true;
}

export function FinetuningJobRequestFromJSON(json: any): FinetuningJobRequest {
    return FinetuningJobRequestFromJSONTyped(json, false);
}

export function FinetuningJobRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): FinetuningJobRequest {
    if (json == null) {
        return json;
    }
    return {

        'project': json['project'],
        'capability': json['capability'] == null ? undefined : json['capability'],
        'dataset': json['dataset'],
        'evalDataset': json['eval_dataset'],
        'evalCell': json['eval_cell'] == null ? undefined : json['eval_cell'],
        'evalSet': json['eval_set'],
        'evalIncumbentBefore': json['eval_incumbent_before'] == null ? undefined : json['eval_incumbent_before'],
        'evalIncumbentAfter': json['eval_incumbent_after'] == null ? undefined : json['eval_incumbent_after'],
        'evalModelBefore': json['eval_model_before'] == null ? undefined : json['eval_model_before'],
        'evalModelAfter': json['eval_model_after'] == null ? undefined : json['eval_model_after'],
        'validationEnabled': json['validation_enabled'] == null ? undefined : json['validation_enabled'],
        'validationSplitRatio': json['validation_split_ratio'] == null ? undefined : json['validation_split_ratio'],
        'validationDataset': json['validation_dataset'] == null ? undefined : json['validation_dataset'],
        'cell': json['cell'] == null ? undefined : json['cell'],
        'validationCell': json['validation_cell'] == null ? undefined : json['validation_cell'],
        'splitMethod': json['split_method'] == null ? undefined : SplitMethodEnumFromJSON(json['split_method']),
        'name': json['name'] == null ? undefined : json['name'],
        'useCase': json['use_case'] == null ? undefined : json['use_case'],
        'baseModel': json['base_model'],
        'baselineModel': json['baseline_model'] == null ? undefined : json['baseline_model'],
        'hyperparameters': json['hyperparameters'] == null ? undefined : json['hyperparameters'],
        'groupId': json['group_id'] == null ? undefined : json['group_id'],
        'modelTier': json['model_tier'] == null ? undefined : json['model_tier'],
        'maxRetries': json['max_retries'] == null ? undefined : json['max_retries'],
    };
}

export function FinetuningJobRequestToJSON(json: any): FinetuningJobRequest {
    return FinetuningJobRequestToJSONTyped(json, false);
}

export function FinetuningJobRequestToJSONTyped(value?: FinetuningJobRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'project': value['project'],
        'capability': value['capability'],
        'dataset': value['dataset'],
        'eval_dataset': value['evalDataset'],
        'eval_cell': value['evalCell'],
        'eval_set': value['evalSet'],
        'eval_incumbent_before': value['evalIncumbentBefore'],
        'eval_incumbent_after': value['evalIncumbentAfter'],
        'eval_model_before': value['evalModelBefore'],
        'eval_model_after': value['evalModelAfter'],
        'validation_enabled': value['validationEnabled'],
        'validation_split_ratio': value['validationSplitRatio'],
        'validation_dataset': value['validationDataset'],
        'cell': value['cell'],
        'validation_cell': value['validationCell'],
        'split_method': SplitMethodEnumToJSON(value['splitMethod']),
        'name': value['name'],
        'use_case': value['useCase'],
        'base_model': value['baseModel'],
        'baseline_model': value['baselineModel'],
        'hyperparameters': value['hyperparameters'],
        'group_id': value['groupId'],
        'model_tier': value['modelTier'],
        'max_retries': value['maxRetries'],
    };
}
