/* tslint:disable */
/* eslint-disable */
/**
 * Overbae API
 * Backend API for the Overclaw / Overmind platform.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelTierEnum } from './ModelTierEnum';
import {
    ModelTierEnumFromJSON,
    ModelTierEnumFromJSONTyped,
    ModelTierEnumToJSON,
    ModelTierEnumToJSONTyped,
} from './ModelTierEnum';
import type { ProviderEnum } from './ProviderEnum';
import {
    ProviderEnumFromJSON,
    ProviderEnumFromJSONTyped,
    ProviderEnumToJSON,
    ProviderEnumToJSONTyped,
} from './ProviderEnum';
import type { FinetuningJobStatusEnum } from './FinetuningJobStatusEnum';
import {
    FinetuningJobStatusEnumFromJSON,
    FinetuningJobStatusEnumFromJSONTyped,
    FinetuningJobStatusEnumToJSON,
    FinetuningJobStatusEnumToJSONTyped,
} from './FinetuningJobStatusEnum';
import type { SplitMethodEnum } from './SplitMethodEnum';
import {
    SplitMethodEnumFromJSON,
    SplitMethodEnumFromJSONTyped,
    SplitMethodEnumToJSON,
    SplitMethodEnumToJSONTyped,
} from './SplitMethodEnum';

/**
 *
 * @export
 * @interface FinetuningJobList
 */
export interface FinetuningJobList {
    /**
     *
     * @type {string}
     * @memberof FinetuningJobList
     */
    readonly id: string;
    /**
     *
     * @type {string}
     * @memberof FinetuningJobList
     */
    readonly project: string;
    /**
     *
     * @type {string}
     * @memberof FinetuningJobList
     */
    readonly capability: string | null;
    /**
     *
     * @type {string}
     * @memberof FinetuningJobList
     */
    readonly dataset: string;
    /**
     *
     * @type {string}
     * @memberof FinetuningJobList
     */
    readonly evalDataset: string | null;
    /**
     *
     * @type {string}
     * @memberof FinetuningJobList
     */
    readonly evalCell: string | null;
    /**
     *
     * @type {string}
     * @memberof FinetuningJobList
     */
    readonly evalSet: string | null;
    /**
     *
     * @type {boolean}
     * @memberof FinetuningJobList
     */
    readonly validationEnabled: boolean;
    /**
     *
     * @type {number}
     * @memberof FinetuningJobList
     */
    readonly validationSplitRatio: number;
    /**
     *
     * @type {string}
     * @memberof FinetuningJobList
     */
    readonly validationDataset: string | null;
    /**
     *
     * @type {string}
     * @memberof FinetuningJobList
     */
    readonly cell: string | null;
    /**
     *
     * @type {{ [key: string]: any; }}
     * @memberof FinetuningJobList
     */
    readonly cellInfo: { [key: string]: any; } | null;
    /**
     *
     * @type {string}
     * @memberof FinetuningJobList
     */
    readonly validationCell: string | null;
    /**
     *
     * @type {SplitMethodEnum}
     * @memberof FinetuningJobList
     */
    readonly splitMethod: SplitMethodEnum;
    /**
     *
     * @type {string}
     * @memberof FinetuningJobList
     */
    readonly name: string;
    /**
     *
     * @type {string}
     * @memberof FinetuningJobList
     */
    readonly useCase: string;
    /**
     *
     * @type {string}
     * @memberof FinetuningJobList
     */
    readonly baseModel: string;
    /**
     *
     * @type {FinetuningJobStatusEnum}
     * @memberof FinetuningJobList
     */
    readonly status: FinetuningJobStatusEnum;
    /**
     *
     * @type {string}
     * @memberof FinetuningJobList
     */
    readonly groupId: string | null;
    /**
     *
     * @type {ModelTierEnum}
     * @memberof FinetuningJobList
     */
    readonly modelTier: ModelTierEnum;
    /**
     *
     * @type {ProviderEnum}
     * @memberof FinetuningJobList
     */
    readonly provider: ProviderEnum;
    /**
     *
     * @type {string}
     * @memberof FinetuningJobList
     */
    readonly outputModelName: string;
    /**
     *
     * @type {string}
     * @memberof FinetuningJobList
     */
    readonly deployedModelId: string | null;
    /**
     *
     * @type {string}
     * @memberof FinetuningJobList
     */
    readonly modelWeightsLocation: string;
    /**
     *
     * @type {any}
     * @memberof FinetuningJobList
     */
    readonly progress: any | null;
    /**
     *
     * @type {number}
     * @memberof FinetuningJobList
     */
    readonly retryCount: number;
    /**
     *
     * @type {number}
     * @memberof FinetuningJobList
     */
    readonly maxRetries: number;
    /**
     *
     * @type {string}
     * @memberof FinetuningJobList
     */
    readonly errorMessage: string;
    /**
     *
     * @type {string}
     * @memberof FinetuningJobList
     */
    readonly costUsd: string | null;
    /**
     *
     * @type {number}
     * @memberof FinetuningJobList
     */
    readonly billedMinutes: number | null;
    /**
     *
     * @type {Date}
     * @memberof FinetuningJobList
     */
    readonly costSyncedAt: Date | null;
    /**
     *
     * @type {Date}
     * @memberof FinetuningJobList
     */
    readonly createdAt: Date;
    /**
     *
     * @type {Date}
     * @memberof FinetuningJobList
     */
    readonly updatedAt: Date;
    /**
     *
     * @type {Date}
     * @memberof FinetuningJobList
     */
    readonly startedAt: Date | null;
    /**
     *
     * @type {Date}
     * @memberof FinetuningJobList
     */
    readonly completedAt: Date | null;
}



/**
 * Check if a given object implements the FinetuningJobList interface.
 */
export function instanceOfFinetuningJobList(value: object): value is FinetuningJobList {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('project' in value) || value['project'] === undefined) return false;
    if (!('capability' in value) || value['capability'] === undefined) return false;
    if (!('dataset' in value) || value['dataset'] === undefined) return false;
    if (!('evalDataset' in value) || value['evalDataset'] === undefined) return false;
    if (!('evalCell' in value) || value['evalCell'] === undefined) return false;
    if (!('evalSet' in value) || value['evalSet'] === undefined) return false;
    if (!('validationEnabled' in value) || value['validationEnabled'] === undefined) return false;
    if (!('validationSplitRatio' in value) || value['validationSplitRatio'] === undefined) return false;
    if (!('validationDataset' in value) || value['validationDataset'] === undefined) return false;
    if (!('cell' in value) || value['cell'] === undefined) return false;
    if (!('cellInfo' in value) || value['cellInfo'] === undefined) return false;
    if (!('validationCell' in value) || value['validationCell'] === undefined) return false;
    if (!('splitMethod' in value) || value['splitMethod'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('useCase' in value) || value['useCase'] === undefined) return false;
    if (!('baseModel' in value) || value['baseModel'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('groupId' in value) || value['groupId'] === undefined) return false;
    if (!('modelTier' in value) || value['modelTier'] === undefined) return false;
    if (!('provider' in value) || value['provider'] === undefined) return false;
    if (!('outputModelName' in value) || value['outputModelName'] === undefined) return false;
    if (!('deployedModelId' in value) || value['deployedModelId'] === undefined) return false;
    if (!('modelWeightsLocation' in value) || value['modelWeightsLocation'] === undefined) return false;
    if (!('progress' in value) || value['progress'] === undefined) return false;
    if (!('retryCount' in value) || value['retryCount'] === undefined) return false;
    if (!('maxRetries' in value) || value['maxRetries'] === undefined) return false;
    if (!('errorMessage' in value) || value['errorMessage'] === undefined) return false;
    if (!('costUsd' in value) || value['costUsd'] === undefined) return false;
    if (!('billedMinutes' in value) || value['billedMinutes'] === undefined) return false;
    if (!('costSyncedAt' in value) || value['costSyncedAt'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('startedAt' in value) || value['startedAt'] === undefined) return false;
    if (!('completedAt' in value) || value['completedAt'] === undefined) return false;
    return true;
}

export function FinetuningJobListFromJSON(json: any): FinetuningJobList {
    return FinetuningJobListFromJSONTyped(json, false);
}

export function FinetuningJobListFromJSONTyped(json: any, ignoreDiscriminator: boolean): FinetuningJobList {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'],
        'project': json['project'],
        'capability': json['capability'],
        'dataset': json['dataset'],
        'evalDataset': json['eval_dataset'],
        'evalCell': json['eval_cell'],
        'evalSet': json['eval_set'],
        'validationEnabled': json['validation_enabled'],
        'validationSplitRatio': json['validation_split_ratio'],
        'validationDataset': json['validation_dataset'],
        'cell': json['cell'],
        'cellInfo': json['cell_info'],
        'validationCell': json['validation_cell'],
        'splitMethod': SplitMethodEnumFromJSON(json['split_method']),
        'name': json['name'],
        'useCase': json['use_case'],
        'baseModel': json['base_model'],
        'status': FinetuningJobStatusEnumFromJSON(json['status']),
        'groupId': json['group_id'],
        'modelTier': ModelTierEnumFromJSON(json['model_tier']),
        'provider': ProviderEnumFromJSON(json['provider']),
        'outputModelName': json['output_model_name'],
        'deployedModelId': json['deployed_model_id'],
        'modelWeightsLocation': json['model_weights_location'],
        'progress': json['progress'],
        'retryCount': json['retry_count'],
        'maxRetries': json['max_retries'],
        'errorMessage': json['error_message'],
        'costUsd': json['cost_usd'],
        'billedMinutes': json['billed_minutes'],
        'costSyncedAt': (json['cost_synced_at'] == null ? null : new Date(json['cost_synced_at'])),
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
        'startedAt': (json['started_at'] == null ? null : new Date(json['started_at'])),
        'completedAt': (json['completed_at'] == null ? null : new Date(json['completed_at'])),
    };
}

export function FinetuningJobListToJSON(json: any): FinetuningJobList {
    return FinetuningJobListToJSONTyped(json, false);
}

export function FinetuningJobListToJSONTyped(value?: Omit<FinetuningJobList, 'id'|'project'|'capability'|'dataset'|'eval_dataset'|'eval_cell'|'eval_set'|'validation_enabled'|'validation_split_ratio'|'validation_dataset'|'cell'|'cell_info'|'validation_cell'|'split_method'|'name'|'use_case'|'base_model'|'status'|'group_id'|'model_tier'|'provider'|'output_model_name'|'deployed_model_id'|'model_weights_location'|'progress'|'retry_count'|'max_retries'|'error_message'|'cost_usd'|'billed_minutes'|'cost_synced_at'|'created_at'|'updated_at'|'started_at'|'completed_at'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

    };
}
