/* tslint:disable */
/* eslint-disable */
/**
 * Overbae API
 * Backend API for the Overclaw / Overmind platform.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface FinetuningTimeEstimate
 */
export interface FinetuningTimeEstimate {
    /**
     *
     * @type {number}
     * @memberof FinetuningTimeEstimate
     */
    seconds: number;
    /**
     *
     * @type {string}
     * @memberof FinetuningTimeEstimate
     */
    human: string;
}

/**
 * Check if a given object implements the FinetuningTimeEstimate interface.
 */
export function instanceOfFinetuningTimeEstimate(value: object): value is FinetuningTimeEstimate {
    if (!('seconds' in value) || value['seconds'] === undefined) return false;
    if (!('human' in value) || value['human'] === undefined) return false;
    return true;
}

export function FinetuningTimeEstimateFromJSON(json: any): FinetuningTimeEstimate {
    return FinetuningTimeEstimateFromJSONTyped(json, false);
}

export function FinetuningTimeEstimateFromJSONTyped(json: any, ignoreDiscriminator: boolean): FinetuningTimeEstimate {
    if (json == null) {
        return json;
    }
    return {

        'seconds': json['seconds'],
        'human': json['human'],
    };
}

export function FinetuningTimeEstimateToJSON(json: any): FinetuningTimeEstimate {
    return FinetuningTimeEstimateToJSONTyped(json, false);
}

export function FinetuningTimeEstimateToJSONTyped(value?: FinetuningTimeEstimate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'seconds': value['seconds'],
        'human': value['human'],
    };
}
