/* tslint:disable */
/* eslint-disable */
/**
 * Overbae API
 * Backend API for the Overclaw / Overmind platform.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface GuestClaimRequest
 */
export interface GuestClaimRequest {
    /**
     *
     * @type {string}
     * @memberof GuestClaimRequest
     */
    clerkToken: string;
}

/**
 * Check if a given object implements the GuestClaimRequest interface.
 */
export function instanceOfGuestClaimRequest(value: object): value is GuestClaimRequest {
    if (!('clerkToken' in value) || value['clerkToken'] === undefined) return false;
    return true;
}

export function GuestClaimRequestFromJSON(json: any): GuestClaimRequest {
    return GuestClaimRequestFromJSONTyped(json, false);
}

export function GuestClaimRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GuestClaimRequest {
    if (json == null) {
        return json;
    }
    return {

        'clerkToken': json['clerk_token'],
    };
}

export function GuestClaimRequestToJSON(json: any): GuestClaimRequest {
    return GuestClaimRequestToJSONTyped(json, false);
}

export function GuestClaimRequestToJSONTyped(value?: GuestClaimRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'clerk_token': value['clerkToken'],
    };
}
