/* tslint:disable */
/* eslint-disable */
/**
 * Overbae API
 * Backend API for the Overclaw / Overmind platform.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface PackageSource
 */
export interface PackageSource {
    /**
     *
     * @type {string}
     * @memberof PackageSource
     */
    path: string;
    /**
     *
     * @type {string}
     * @memberof PackageSource
     */
    sha256: string;
    /**
     *
     * @type {string}
     * @memberof PackageSource
     */
    content: string;
    /**
     *
     * @type {number}
     * @memberof PackageSource
     */
    offset: number;
    /**
     *
     * @type {number}
     * @memberof PackageSource
     */
    total: number;
    /**
     *
     * @type {number}
     * @memberof PackageSource
     */
    nextOffset: number | null;
}

/**
 * Check if a given object implements the PackageSource interface.
 */
export function instanceOfPackageSource(value: object): value is PackageSource {
    if (!('path' in value) || value['path'] === undefined) return false;
    if (!('sha256' in value) || value['sha256'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('offset' in value) || value['offset'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('nextOffset' in value) || value['nextOffset'] === undefined) return false;
    return true;
}

export function PackageSourceFromJSON(json: any): PackageSource {
    return PackageSourceFromJSONTyped(json, false);
}

export function PackageSourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): PackageSource {
    if (json == null) {
        return json;
    }
    return {

        'path': json['path'],
        'sha256': json['sha256'],
        'content': json['content'],
        'offset': json['offset'],
        'total': json['total'],
        'nextOffset': json['next_offset'],
    };
}

export function PackageSourceToJSON(json: any): PackageSource {
    return PackageSourceToJSONTyped(json, false);
}

export function PackageSourceToJSONTyped(value?: PackageSource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'path': value['path'],
        'sha256': value['sha256'],
        'content': value['content'],
        'offset': value['offset'],
        'total': value['total'],
        'next_offset': value['nextOffset'],
    };
}
