/* tslint:disable */
/* eslint-disable */
/**
 * Overbae API
 * Backend API for the Overclaw / Overmind platform.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TraceGroup } from './TraceGroup';
import {
    TraceGroupFromJSON,
    TraceGroupFromJSONTyped,
    TraceGroupToJSON,
    TraceGroupToJSONTyped,
} from './TraceGroup';

/**
 *
 * @export
 * @interface PaginatedTraceGroupList
 */
export interface PaginatedTraceGroupList {
    /**
     *
     * @type {number}
     * @memberof PaginatedTraceGroupList
     */
    count: number;
    /**
     *
     * @type {string}
     * @memberof PaginatedTraceGroupList
     */
    next?: string | null;
    /**
     *
     * @type {string}
     * @memberof PaginatedTraceGroupList
     */
    previous?: string | null;
    /**
     *
     * @type {Array<TraceGroup>}
     * @memberof PaginatedTraceGroupList
     */
    results: Array<TraceGroup>;
}

/**
 * Check if a given object implements the PaginatedTraceGroupList interface.
 */
export function instanceOfPaginatedTraceGroupList(value: object): value is PaginatedTraceGroupList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedTraceGroupListFromJSON(json: any): PaginatedTraceGroupList {
    return PaginatedTraceGroupListFromJSONTyped(json, false);
}

export function PaginatedTraceGroupListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedTraceGroupList {
    if (json == null) {
        return json;
    }
    return {

        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(TraceGroupFromJSON)),
    };
}

export function PaginatedTraceGroupListToJSON(json: any): PaginatedTraceGroupList {
    return PaginatedTraceGroupListToJSONTyped(json, false);
}

export function PaginatedTraceGroupListToJSONTyped(value?: PaginatedTraceGroupList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(TraceGroupToJSON)),
    };
}
