/* tslint:disable */
/* eslint-disable */
/**
 * Overbae API
 * Backend API for the Overclaw / Overmind platform.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FinetuningJobList } from './FinetuningJobList';
import {
    FinetuningJobListFromJSON,
    FinetuningJobListFromJSONTyped,
    FinetuningJobListToJSON,
    FinetuningJobListToJSONTyped,
} from './FinetuningJobList';

/**
 *
 * @export
 * @interface PaginatedFinetuningJobListList
 */
export interface PaginatedFinetuningJobListList {
    /**
     *
     * @type {number}
     * @memberof PaginatedFinetuningJobListList
     */
    count: number;
    /**
     *
     * @type {string}
     * @memberof PaginatedFinetuningJobListList
     */
    next?: string | null;
    /**
     *
     * @type {string}
     * @memberof PaginatedFinetuningJobListList
     */
    previous?: string | null;
    /**
     *
     * @type {Array<FinetuningJobList>}
     * @memberof PaginatedFinetuningJobListList
     */
    results: Array<FinetuningJobList>;
}

/**
 * Check if a given object implements the PaginatedFinetuningJobListList interface.
 */
export function instanceOfPaginatedFinetuningJobListList(value: object): value is PaginatedFinetuningJobListList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedFinetuningJobListListFromJSON(json: any): PaginatedFinetuningJobListList {
    return PaginatedFinetuningJobListListFromJSONTyped(json, false);
}

export function PaginatedFinetuningJobListListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedFinetuningJobListList {
    if (json == null) {
        return json;
    }
    return {

        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(FinetuningJobListFromJSON)),
    };
}

export function PaginatedFinetuningJobListListToJSON(json: any): PaginatedFinetuningJobListList {
    return PaginatedFinetuningJobListListToJSONTyped(json, false);
}

export function PaginatedFinetuningJobListListToJSONTyped(value?: PaginatedFinetuningJobListList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(FinetuningJobListToJSON)),
    };
}
