/* tslint:disable */
/* eslint-disable */
/**
 * Overbae API
 * Backend API for the Overclaw / Overmind platform.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OptimizerCommand } from './OptimizerCommand';
import {
    OptimizerCommandFromJSON,
    OptimizerCommandFromJSONTyped,
    OptimizerCommandToJSON,
    OptimizerCommandToJSONTyped,
} from './OptimizerCommand';

/**
 *
 * @export
 * @interface PaginatedOptimizerCommandList
 */
export interface PaginatedOptimizerCommandList {
    /**
     *
     * @type {number}
     * @memberof PaginatedOptimizerCommandList
     */
    count: number;
    /**
     *
     * @type {string}
     * @memberof PaginatedOptimizerCommandList
     */
    next?: string | null;
    /**
     *
     * @type {string}
     * @memberof PaginatedOptimizerCommandList
     */
    previous?: string | null;
    /**
     *
     * @type {Array<OptimizerCommand>}
     * @memberof PaginatedOptimizerCommandList
     */
    results: Array<OptimizerCommand>;
}

/**
 * Check if a given object implements the PaginatedOptimizerCommandList interface.
 */
export function instanceOfPaginatedOptimizerCommandList(value: object): value is PaginatedOptimizerCommandList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedOptimizerCommandListFromJSON(json: any): PaginatedOptimizerCommandList {
    return PaginatedOptimizerCommandListFromJSONTyped(json, false);
}

export function PaginatedOptimizerCommandListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedOptimizerCommandList {
    if (json == null) {
        return json;
    }
    return {

        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(OptimizerCommandFromJSON)),
    };
}

export function PaginatedOptimizerCommandListToJSON(json: any): PaginatedOptimizerCommandList {
    return PaginatedOptimizerCommandListToJSONTyped(json, false);
}

export function PaginatedOptimizerCommandListToJSONTyped(value?: PaginatedOptimizerCommandList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(OptimizerCommandToJSON)),
    };
}
