/* tslint:disable */
/* eslint-disable */
/**
 * Overbae API
 * Backend API for the Overclaw / Overmind platform.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CapabilityStatusEnum } from './CapabilityStatusEnum';
import {
    CapabilityStatusEnumFromJSON,
    CapabilityStatusEnumFromJSONTyped,
    CapabilityStatusEnumToJSON,
    CapabilityStatusEnumToJSONTyped,
} from './CapabilityStatusEnum';

/**
 *
 * @export
 * @interface PatchedCapabilityRequest
 */
export interface PatchedCapabilityRequest {
    /**
     *
     * @type {any}
     * @memberof PatchedCapabilityRequest
     */
    toolConfig?: any | null;
    /**
     *
     * @type {any}
     * @memberof PatchedCapabilityRequest
     */
    consistencyRules?: any | null;
    /**
     *
     * @type {any}
     * @memberof PatchedCapabilityRequest
     */
    optimizableElements?: any | null;
    /**
     *
     * @type {any}
     * @memberof PatchedCapabilityRequest
     */
    fixedElements?: any | null;
    /**
     *
     * @type {string}
     * @memberof PatchedCapabilityRequest
     */
    name?: string;
    /**
     *
     * @type {string}
     * @memberof PatchedCapabilityRequest
     */
    description?: string;
    /**
     *
     * @type {string}
     * @memberof PatchedCapabilityRequest
     */
    sourcePath?: string;
    /**
     *
     * @type {string}
     * @memberof PatchedCapabilityRequest
     */
    entrypointFn?: string;
    /**
     *
     * @type {string}
     * @memberof PatchedCapabilityRequest
     */
    model?: string;
    /**
     *
     * @type {string}
     * @memberof PatchedCapabilityRequest
     */
    analyzerModel?: string;
    /**
     *
     * @type {string}
     * @memberof PatchedCapabilityRequest
     */
    cliVersion?: string;
    /**
     *
     * @type {CapabilityStatusEnum}
     * @memberof PatchedCapabilityRequest
     */
    status?: CapabilityStatusEnum;
    /**
     *
     * @type {boolean}
     * @memberof PatchedCapabilityRequest
     */
    observed?: boolean;
    /**
     *
     * @type {any}
     * @memberof PatchedCapabilityRequest
     */
    footprint?: any | null;
    /**
     *
     * @type {any}
     * @memberof PatchedCapabilityRequest
     */
    inputSchema?: any | null;
    /**
     *
     * @type {any}
     * @memberof PatchedCapabilityRequest
     */
    outputFields?: any | null;
    /**
     *
     * @type {any}
     * @memberof PatchedCapabilityRequest
     */
    outputSchema?: any | null;
    /**
     *
     * @type {number}
     * @memberof PatchedCapabilityRequest
     */
    structureWeight?: number;
    /**
     *
     * @type {number}
     * @memberof PatchedCapabilityRequest
     */
    totalPoints?: number;
    /**
     *
     * @type {number}
     * @memberof PatchedCapabilityRequest
     */
    toolUsageWeight?: number;
    /**
     *
     * @type {string}
     * @memberof PatchedCapabilityRequest
     */
    policyMarkdown?: string;
    /**
     *
     * @type {string}
     * @memberof PatchedCapabilityRequest
     */
    toolsSummary?: string;
    /**
     *
     * @type {string}
     * @memberof PatchedCapabilityRequest
     */
    decisionLogic?: string;
    /**
     *
     * @type {any}
     * @memberof PatchedCapabilityRequest
     */
    improvementMetadata?: any | null;
    /**
     *
     * @type {any}
     * @memberof PatchedCapabilityRequest
     */
    usageStats?: any | null;
    /**
     *
     * @type {Date}
     * @memberof PatchedCapabilityRequest
     */
    lastActivityAt?: Date | null;
    /**
     *
     * @type {string}
     * @memberof PatchedCapabilityRequest
     */
    project?: string;
    /**
     *
     * @type {string}
     * @memberof PatchedCapabilityRequest
     */
    activeEvalSet?: string | null;
    /**
     *
     * @type {string}
     * @memberof PatchedCapabilityRequest
     */
    activeModel?: string | null;
    /**
     *
     * @type {string}
     * @memberof PatchedCapabilityRequest
     */
    benchmarkModel?: string | null;
}



/**
 * Check if a given object implements the PatchedCapabilityRequest interface.
 */
export function instanceOfPatchedCapabilityRequest(value: object): value is PatchedCapabilityRequest {
    return true;
}

export function PatchedCapabilityRequestFromJSON(json: any): PatchedCapabilityRequest {
    return PatchedCapabilityRequestFromJSONTyped(json, false);
}

export function PatchedCapabilityRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedCapabilityRequest {
    if (json == null) {
        return json;
    }
    return {

        'toolConfig': json['tool_config'] == null ? undefined : json['tool_config'],
        'consistencyRules': json['consistency_rules'] == null ? undefined : json['consistency_rules'],
        'optimizableElements': json['optimizable_elements'] == null ? undefined : json['optimizable_elements'],
        'fixedElements': json['fixed_elements'] == null ? undefined : json['fixed_elements'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'sourcePath': json['source_path'] == null ? undefined : json['source_path'],
        'entrypointFn': json['entrypoint_fn'] == null ? undefined : json['entrypoint_fn'],
        'model': json['model'] == null ? undefined : json['model'],
        'analyzerModel': json['analyzer_model'] == null ? undefined : json['analyzer_model'],
        'cliVersion': json['cli_version'] == null ? undefined : json['cli_version'],
        'status': json['status'] == null ? undefined : CapabilityStatusEnumFromJSON(json['status']),
        'observed': json['observed'] == null ? undefined : json['observed'],
        'footprint': json['footprint'] == null ? undefined : json['footprint'],
        'inputSchema': json['input_schema'] == null ? undefined : json['input_schema'],
        'outputFields': json['output_fields'] == null ? undefined : json['output_fields'],
        'outputSchema': json['output_schema'] == null ? undefined : json['output_schema'],
        'structureWeight': json['structure_weight'] == null ? undefined : json['structure_weight'],
        'totalPoints': json['total_points'] == null ? undefined : json['total_points'],
        'toolUsageWeight': json['tool_usage_weight'] == null ? undefined : json['tool_usage_weight'],
        'policyMarkdown': json['policy_markdown'] == null ? undefined : json['policy_markdown'],
        'toolsSummary': json['tools_summary'] == null ? undefined : json['tools_summary'],
        'decisionLogic': json['decision_logic'] == null ? undefined : json['decision_logic'],
        'improvementMetadata': json['improvement_metadata'] == null ? undefined : json['improvement_metadata'],
        'usageStats': json['usage_stats'] == null ? undefined : json['usage_stats'],
        'lastActivityAt': json['last_activity_at'] == null ? undefined : (new Date(json['last_activity_at'])),
        'project': json['project'] == null ? undefined : json['project'],
        'activeEvalSet': json['active_eval_set'] == null ? undefined : json['active_eval_set'],
        'activeModel': json['active_model'] == null ? undefined : json['active_model'],
        'benchmarkModel': json['benchmark_model'] == null ? undefined : json['benchmark_model'],
    };
}

export function PatchedCapabilityRequestToJSON(json: any): PatchedCapabilityRequest {
    return PatchedCapabilityRequestToJSONTyped(json, false);
}

export function PatchedCapabilityRequestToJSONTyped(value?: PatchedCapabilityRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'tool_config': value['toolConfig'],
        'consistency_rules': value['consistencyRules'],
        'optimizable_elements': value['optimizableElements'],
        'fixed_elements': value['fixedElements'],
        'name': value['name'],
        'description': value['description'],
        'source_path': value['sourcePath'],
        'entrypoint_fn': value['entrypointFn'],
        'model': value['model'],
        'analyzer_model': value['analyzerModel'],
        'cli_version': value['cliVersion'],
        'status': CapabilityStatusEnumToJSON(value['status']),
        'observed': value['observed'],
        'footprint': value['footprint'],
        'input_schema': value['inputSchema'],
        'output_fields': value['outputFields'],
        'output_schema': value['outputSchema'],
        'structure_weight': value['structureWeight'],
        'total_points': value['totalPoints'],
        'tool_usage_weight': value['toolUsageWeight'],
        'policy_markdown': value['policyMarkdown'],
        'tools_summary': value['toolsSummary'],
        'decision_logic': value['decisionLogic'],
        'improvement_metadata': value['improvementMetadata'],
        'usage_stats': value['usageStats'],
        'last_activity_at': value['lastActivityAt'] == null ? value['lastActivityAt'] : value['lastActivityAt'].toISOString(),
        'project': value['project'],
        'active_eval_set': value['activeEvalSet'],
        'active_model': value['activeModel'],
        'benchmark_model': value['benchmarkModel'],
    };
}
