/* tslint:disable */
/* eslint-disable */
/**
 * Overbae API
 * Backend API for the Overclaw / Overmind platform.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface PreparationExecution
 */
export interface PreparationExecution {
    /**
     *
     * @type {string}
     * @memberof PreparationExecution
     */
    cell: string;
    /**
     *
     * @type {string}
     * @memberof PreparationExecution
     */
    stepId: string;
    /**
     *
     * @type {string}
     * @memberof PreparationExecution
     */
    state: string;
    /**
     *
     * @type {number}
     * @memberof PreparationExecution
     */
    rows: number;
    /**
     *
     * @type {string}
     * @memberof PreparationExecution
     */
    fingerprint: string;
}

/**
 * Check if a given object implements the PreparationExecution interface.
 */
export function instanceOfPreparationExecution(value: object): value is PreparationExecution {
    if (!('cell' in value) || value['cell'] === undefined) return false;
    if (!('stepId' in value) || value['stepId'] === undefined) return false;
    if (!('state' in value) || value['state'] === undefined) return false;
    if (!('rows' in value) || value['rows'] === undefined) return false;
    if (!('fingerprint' in value) || value['fingerprint'] === undefined) return false;
    return true;
}

export function PreparationExecutionFromJSON(json: any): PreparationExecution {
    return PreparationExecutionFromJSONTyped(json, false);
}

export function PreparationExecutionFromJSONTyped(json: any, ignoreDiscriminator: boolean): PreparationExecution {
    if (json == null) {
        return json;
    }
    return {

        'cell': json['cell'],
        'stepId': json['step_id'],
        'state': json['state'],
        'rows': json['rows'],
        'fingerprint': json['fingerprint'],
    };
}

export function PreparationExecutionToJSON(json: any): PreparationExecution {
    return PreparationExecutionToJSONTyped(json, false);
}

export function PreparationExecutionToJSONTyped(value?: PreparationExecution | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'cell': value['cell'],
        'step_id': value['stepId'],
        'state': value['state'],
        'rows': value['rows'],
        'fingerprint': value['fingerprint'],
    };
}
