/* tslint:disable */
/* eslint-disable */
/**
 * Overbae API
 * Backend API for the Overclaw / Overmind platform.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IntegrationTypeEnum } from './IntegrationTypeEnum';
import {
    IntegrationTypeEnumFromJSON,
    IntegrationTypeEnumFromJSONTyped,
    IntegrationTypeEnumToJSON,
    IntegrationTypeEnumToJSONTyped,
} from './IntegrationTypeEnum';

/**
 *
 * @export
 * @interface Project
 */
export interface Project {
    /**
     *
     * @type {string}
     * @memberof Project
     */
    readonly id: string;
    /**
     *
     * @type {number}
     * @memberof Project
     */
    readonly memberCount: number;
    /**
     *
     * @type {Array<string>}
     * @memberof Project
     */
    readonly memberEmails: Array<string>;
    /**
     *
     * @type {string}
     * @memberof Project
     */
    name: string;
    /**
     *
     * @type {string}
     * @memberof Project
     */
    slug: string;
    /**
     *
     * @type {IntegrationTypeEnum}
     * @memberof Project
     */
    integrationType?: IntegrationTypeEnum;
    /**
     *
     * @type {boolean}
     * @memberof Project
     */
    isActive?: boolean;
    /**
     *
     * @type {any}
     * @memberof Project
     */
    settings?: any | null;
    /**
     *
     * @type {Date}
     * @memberof Project
     */
    readonly createdAt: Date;
    /**
     *
     * @type {Date}
     * @memberof Project
     */
    readonly updatedAt: Date;
}



/**
 * Check if a given object implements the Project interface.
 */
export function instanceOfProject(value: object): value is Project {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('memberCount' in value) || value['memberCount'] === undefined) return false;
    if (!('memberEmails' in value) || value['memberEmails'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function ProjectFromJSON(json: any): Project {
    return ProjectFromJSONTyped(json, false);
}

export function ProjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): Project {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'],
        'memberCount': json['member_count'],
        'memberEmails': json['member_emails'],
        'name': json['name'],
        'slug': json['slug'],
        'integrationType': json['integration_type'] == null ? undefined : IntegrationTypeEnumFromJSON(json['integration_type']),
        'isActive': json['is_active'] == null ? undefined : json['is_active'],
        'settings': json['settings'] == null ? undefined : json['settings'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function ProjectToJSON(json: any): Project {
    return ProjectToJSONTyped(json, false);
}

export function ProjectToJSONTyped(value?: Omit<Project, 'id'|'member_count'|'member_emails'|'created_at'|'updated_at'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'name': value['name'],
        'slug': value['slug'],
        'integration_type': IntegrationTypeEnumToJSON(value['integrationType']),
        'is_active': value['isActive'],
        'settings': value['settings'],
    };
}
