/* tslint:disable */
/* eslint-disable */
/**
 * Overbae API
 * Backend API for the Overclaw / Overmind platform.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface PublicTokenRefresh
 */
export interface PublicTokenRefresh {
    /**
     *
     * @type {string}
     * @memberof PublicTokenRefresh
     */
    refresh: string;
    /**
     *
     * @type {string}
     * @memberof PublicTokenRefresh
     */
    readonly access: string;
}

/**
 * Check if a given object implements the PublicTokenRefresh interface.
 */
export function instanceOfPublicTokenRefresh(value: object): value is PublicTokenRefresh {
    if (!('refresh' in value) || value['refresh'] === undefined) return false;
    if (!('access' in value) || value['access'] === undefined) return false;
    return true;
}

export function PublicTokenRefreshFromJSON(json: any): PublicTokenRefresh {
    return PublicTokenRefreshFromJSONTyped(json, false);
}

export function PublicTokenRefreshFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicTokenRefresh {
    if (json == null) {
        return json;
    }
    return {

        'refresh': json['refresh'],
        'access': json['access'],
    };
}

export function PublicTokenRefreshToJSON(json: any): PublicTokenRefresh {
    return PublicTokenRefreshToJSONTyped(json, false);
}

export function PublicTokenRefreshToJSONTyped(value?: Omit<PublicTokenRefresh, 'access'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'refresh': value['refresh'],
    };
}
