/* tslint:disable */
/* eslint-disable */
/**
 * Overbae API
 * Backend API for the Overclaw / Overmind platform.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Buyer-facing copy from models.json ``marketing`` (per model).
 * @export
 * @interface PublicModelMarketing
 */
export interface PublicModelMarketing {
    /**
     *
     * @type {string}
     * @memberof PublicModelMarketing
     */
    pitch: string | null;
    /**
     *
     * @type {string}
     * @memberof PublicModelMarketing
     */
    overview: string | null;
    /**
     *
     * @type {string}
     * @memberof PublicModelMarketing
     */
    description: string | null;
    /**
     *
     * @type {Array<string>}
     * @memberof PublicModelMarketing
     */
    goodFor: Array<string>;
}

/**
 * Check if a given object implements the PublicModelMarketing interface.
 */
export function instanceOfPublicModelMarketing(value: object): value is PublicModelMarketing {
    if (!('pitch' in value) || value['pitch'] === undefined) return false;
    if (!('overview' in value) || value['overview'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('goodFor' in value) || value['goodFor'] === undefined) return false;
    return true;
}

export function PublicModelMarketingFromJSON(json: any): PublicModelMarketing {
    return PublicModelMarketingFromJSONTyped(json, false);
}

export function PublicModelMarketingFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicModelMarketing {
    if (json == null) {
        return json;
    }
    return {

        'pitch': json['pitch'],
        'overview': json['overview'],
        'description': json['description'],
        'goodFor': json['good_for'],
    };
}

export function PublicModelMarketingToJSON(json: any): PublicModelMarketing {
    return PublicModelMarketingToJSONTyped(json, false);
}

export function PublicModelMarketingToJSONTyped(value?: PublicModelMarketing | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'pitch': value['pitch'],
        'overview': value['overview'],
        'description': value['description'],
        'good_for': value['goodFor'],
    };
}
