/* tslint:disable */
/* eslint-disable */
/**
 * Overbae API
 * Backend API for the Overclaw / Overmind platform.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PublicModel } from './PublicModel';
import {
    PublicModelFromJSON,
    PublicModelFromJSONTyped,
    PublicModelToJSON,
    PublicModelToJSONTyped,
} from './PublicModel';
import type { PublicLibraryFilters } from './PublicLibraryFilters';
import {
    PublicLibraryFiltersFromJSON,
    PublicLibraryFiltersFromJSONTyped,
    PublicLibraryFiltersToJSON,
    PublicLibraryFiltersToJSONTyped,
} from './PublicLibraryFilters';

/**
 *
 * @export
 * @interface PublicModelListResponse
 */
export interface PublicModelListResponse {
    /**
     *
     * @type {Array<PublicModel>}
     * @memberof PublicModelListResponse
     */
    models: Array<PublicModel>;
    /**
     *
     * @type {PublicLibraryFilters}
     * @memberof PublicModelListResponse
     */
    filters: PublicLibraryFilters;
}

/**
 * Check if a given object implements the PublicModelListResponse interface.
 */
export function instanceOfPublicModelListResponse(value: object): value is PublicModelListResponse {
    if (!('models' in value) || value['models'] === undefined) return false;
    if (!('filters' in value) || value['filters'] === undefined) return false;
    return true;
}

export function PublicModelListResponseFromJSON(json: any): PublicModelListResponse {
    return PublicModelListResponseFromJSONTyped(json, false);
}

export function PublicModelListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicModelListResponse {
    if (json == null) {
        return json;
    }
    return {

        'models': ((json['models'] as Array<any>).map(PublicModelFromJSON)),
        'filters': PublicLibraryFiltersFromJSON(json['filters']),
    };
}

export function PublicModelListResponseToJSON(json: any): PublicModelListResponse {
    return PublicModelListResponseToJSONTyped(json, false);
}

export function PublicModelListResponseToJSONTyped(value?: PublicModelListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'models': ((value['models'] as Array<any>).map(PublicModelToJSON)),
        'filters': PublicLibraryFiltersToJSON(value['filters']),
    };
}
