/* tslint:disable */
/* eslint-disable */
/**
 * Overbae API
 * Backend API for the Overclaw / Overmind platform.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface RunEvaluator
 */
export interface RunEvaluator {
    /**
     *
     * @type {string}
     * @memberof RunEvaluator
     */
    readonly id: string;
    /**
     *
     * @type {string}
     * @memberof RunEvaluator
     */
    readonly run: string;
    /**
     *
     * @type {string}
     * @memberof RunEvaluator
     */
    readonly evaluator: string | null;
    /**
     *
     * @type {string}
     * @memberof RunEvaluator
     */
    readonly name: string;
    /**
     *
     * @type {string}
     * @memberof RunEvaluator
     */
    readonly kind: string;
    /**
     *
     * @type {any}
     * @memberof RunEvaluator
     */
    readonly snapshot: any | null;
    /**
     *
     * @type {string}
     * @memberof RunEvaluator
     */
    readonly scopeOverride: string;
    /**
     *
     * @type {number}
     * @memberof RunEvaluator
     */
    readonly sampling: number;
    /**
     *
     * @type {boolean}
     * @memberof RunEvaluator
     */
    readonly enabled: boolean;
    /**
     *
     * @type {number}
     * @memberof RunEvaluator
     */
    readonly order: number;
    /**
     *
     * @type {Date}
     * @memberof RunEvaluator
     */
    readonly createdAt: Date;
}

/**
 * Check if a given object implements the RunEvaluator interface.
 */
export function instanceOfRunEvaluator(value: object): value is RunEvaluator {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('run' in value) || value['run'] === undefined) return false;
    if (!('evaluator' in value) || value['evaluator'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('kind' in value) || value['kind'] === undefined) return false;
    if (!('snapshot' in value) || value['snapshot'] === undefined) return false;
    if (!('scopeOverride' in value) || value['scopeOverride'] === undefined) return false;
    if (!('sampling' in value) || value['sampling'] === undefined) return false;
    if (!('enabled' in value) || value['enabled'] === undefined) return false;
    if (!('order' in value) || value['order'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function RunEvaluatorFromJSON(json: any): RunEvaluator {
    return RunEvaluatorFromJSONTyped(json, false);
}

export function RunEvaluatorFromJSONTyped(json: any, ignoreDiscriminator: boolean): RunEvaluator {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'],
        'run': json['run'],
        'evaluator': json['evaluator'],
        'name': json['name'],
        'kind': json['kind'],
        'snapshot': json['snapshot'],
        'scopeOverride': json['scope_override'],
        'sampling': json['sampling'],
        'enabled': json['enabled'],
        'order': json['order'],
        'createdAt': (new Date(json['created_at'])),
    };
}

export function RunEvaluatorToJSON(json: any): RunEvaluator {
    return RunEvaluatorToJSONTyped(json, false);
}

export function RunEvaluatorToJSONTyped(value?: Omit<RunEvaluator, 'id'|'run'|'evaluator'|'name'|'kind'|'snapshot'|'scope_override'|'sampling'|'enabled'|'order'|'created_at'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

    };
}
