/* tslint:disable */
/* eslint-disable */
/**
 * Overbae API
 * Backend API for the Overclaw / Overmind platform.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Exactly one of ``upload_id``, ``text``, ``rows`` or ``traces``.
 * ``traces`` is a traces-list selection or ``{"trace_ids": [...]}``.
 * @export
 * @interface SourceRequest
 */
export interface SourceRequest {
    /**
     *
     * @type {string}
     * @memberof SourceRequest
     */
    uploadId?: string;
    /**
     *
     * @type {string}
     * @memberof SourceRequest
     */
    filename?: string;
    /**
     *
     * @type {string}
     * @memberof SourceRequest
     */
    text?: string;
    /**
     *
     * @type {Array<any>}
     * @memberof SourceRequest
     */
    rows?: Array<any>;
    /**
     *
     * @type {any}
     * @memberof SourceRequest
     */
    traces?: any | null;
}

/**
 * Check if a given object implements the SourceRequest interface.
 */
export function instanceOfSourceRequest(value: object): value is SourceRequest {
    return true;
}

export function SourceRequestFromJSON(json: any): SourceRequest {
    return SourceRequestFromJSONTyped(json, false);
}

export function SourceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SourceRequest {
    if (json == null) {
        return json;
    }
    return {

        'uploadId': json['upload_id'] == null ? undefined : json['upload_id'],
        'filename': json['filename'] == null ? undefined : json['filename'],
        'text': json['text'] == null ? undefined : json['text'],
        'rows': json['rows'] == null ? undefined : json['rows'],
        'traces': json['traces'] == null ? undefined : json['traces'],
    };
}

export function SourceRequestToJSON(json: any): SourceRequest {
    return SourceRequestToJSONTyped(json, false);
}

export function SourceRequestToJSONTyped(value?: SourceRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'upload_id': value['uploadId'],
        'filename': value['filename'],
        'text': value['text'],
        'rows': value['rows'],
        'traces': value['traces'],
    };
}
