/* tslint:disable */
/* eslint-disable */
/**
 * Overbae API
 * Backend API for the Overclaw / Overmind platform.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StatusFbaEnum } from './StatusFbaEnum';
import {
    StatusFbaEnumFromJSON,
    StatusFbaEnumFromJSONTyped,
    StatusFbaEnumToJSON,
    StatusFbaEnumToJSONTyped,
} from './StatusFbaEnum';
import type { BindingSourceEnum } from './BindingSourceEnum';
import {
    BindingSourceEnumFromJSON,
    BindingSourceEnumFromJSONTyped,
    BindingSourceEnumToJSON,
    BindingSourceEnumToJSONTyped,
} from './BindingSourceEnum';

/**
 *
 * @export
 * @interface TaskExecutionList
 */
export interface TaskExecutionList {
    /**
     *
     * @type {string}
     * @memberof TaskExecutionList
     */
    readonly id: string;
    /**
     *
     * @type {string}
     * @memberof TaskExecutionList
     */
    capability?: string | null;
    /**
     *
     * @type {string}
     * @memberof TaskExecutionList
     */
    behaviour?: string | null;
    /**
     *
     * @type {string}
     * @memberof TaskExecutionList
     */
    readonly behaviourKey: string;
    /**
     *
     * @type {string}
     * @memberof TaskExecutionList
     */
    traceId: string;
    /**
     *
     * @type {string}
     * @memberof TaskExecutionList
     */
    unitSpanId: string;
    /**
     *
     * @type {string}
     * @memberof TaskExecutionList
     */
    conversationId?: string;
    /**
     *
     * @type {BindingSourceEnum}
     * @memberof TaskExecutionList
     */
    bindingSource?: BindingSourceEnum;
    /**
     *
     * @type {number}
     * @memberof TaskExecutionList
     */
    successScore?: number | null;
    /**
     *
     * @type {number}
     * @memberof TaskExecutionList
     */
    sessionScore?: number | null;
    /**
     *
     * @type {string}
     * @memberof TaskExecutionList
     */
    sessionRationale?: string;
    /**
     *
     * @type {any}
     * @memberof TaskExecutionList
     */
    routeFlags?: any | null;
    /**
     *
     * @type {string}
     * @memberof TaskExecutionList
     */
    terminalKind?: string;
    /**
     *
     * @type {StatusFbaEnum}
     * @memberof TaskExecutionList
     */
    status?: StatusFbaEnum;
    /**
     *
     * @type {Date}
     * @memberof TaskExecutionList
     */
    startedAt?: Date | null;
    /**
     *
     * @type {number}
     * @memberof TaskExecutionList
     */
    durationMs?: number | null;
    /**
     *
     * @type {number}
     * @memberof TaskExecutionList
     */
    readonly totalTokens: number | null;
    /**
     *
     * @type {number}
     * @memberof TaskExecutionList
     */
    readonly totalCost: number | null;
    /**
     *
     * @type {string}
     * @memberof TaskExecutionList
     */
    readonly model: string | null;
    /**
     *
     * @type {boolean}
     * @memberof TaskExecutionList
     */
    readonly scoringPending: boolean;
}



/**
 * Check if a given object implements the TaskExecutionList interface.
 */
export function instanceOfTaskExecutionList(value: object): value is TaskExecutionList {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('behaviourKey' in value) || value['behaviourKey'] === undefined) return false;
    if (!('traceId' in value) || value['traceId'] === undefined) return false;
    if (!('unitSpanId' in value) || value['unitSpanId'] === undefined) return false;
    if (!('totalTokens' in value) || value['totalTokens'] === undefined) return false;
    if (!('totalCost' in value) || value['totalCost'] === undefined) return false;
    if (!('model' in value) || value['model'] === undefined) return false;
    if (!('scoringPending' in value) || value['scoringPending'] === undefined) return false;
    return true;
}

export function TaskExecutionListFromJSON(json: any): TaskExecutionList {
    return TaskExecutionListFromJSONTyped(json, false);
}

export function TaskExecutionListFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskExecutionList {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'],
        'capability': json['capability'] == null ? undefined : json['capability'],
        'behaviour': json['behaviour'] == null ? undefined : json['behaviour'],
        'behaviourKey': json['behaviour_key'],
        'traceId': json['trace_id'],
        'unitSpanId': json['unit_span_id'],
        'conversationId': json['conversation_id'] == null ? undefined : json['conversation_id'],
        'bindingSource': json['binding_source'] == null ? undefined : BindingSourceEnumFromJSON(json['binding_source']),
        'successScore': json['success_score'] == null ? undefined : json['success_score'],
        'sessionScore': json['session_score'] == null ? undefined : json['session_score'],
        'sessionRationale': json['session_rationale'] == null ? undefined : json['session_rationale'],
        'routeFlags': json['route_flags'] == null ? undefined : json['route_flags'],
        'terminalKind': json['terminal_kind'] == null ? undefined : json['terminal_kind'],
        'status': json['status'] == null ? undefined : StatusFbaEnumFromJSON(json['status']),
        'startedAt': json['started_at'] == null ? undefined : (new Date(json['started_at'])),
        'durationMs': json['duration_ms'] == null ? undefined : json['duration_ms'],
        'totalTokens': json['total_tokens'],
        'totalCost': json['total_cost'],
        'model': json['model'],
        'scoringPending': json['scoring_pending'],
    };
}

export function TaskExecutionListToJSON(json: any): TaskExecutionList {
    return TaskExecutionListToJSONTyped(json, false);
}

export function TaskExecutionListToJSONTyped(value?: Omit<TaskExecutionList, 'id'|'behaviour_key'|'total_tokens'|'total_cost'|'model'|'scoring_pending'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'capability': value['capability'],
        'behaviour': value['behaviour'],
        'trace_id': value['traceId'],
        'unit_span_id': value['unitSpanId'],
        'conversation_id': value['conversationId'],
        'binding_source': BindingSourceEnumToJSON(value['bindingSource']),
        'success_score': value['successScore'],
        'session_score': value['sessionScore'],
        'session_rationale': value['sessionRationale'],
        'route_flags': value['routeFlags'],
        'terminal_kind': value['terminalKind'],
        'status': StatusFbaEnumToJSON(value['status']),
        'started_at': value['startedAt'] == null ? value['startedAt'] : value['startedAt'].toISOString(),
        'duration_ms': value['durationMs'],
    };
}
