/* tslint:disable */
/* eslint-disable */
/**
 * Overbae API
 * Backend API for the Overclaw / Overmind platform.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TraceGroupEvidence } from './TraceGroupEvidence';
import {
    TraceGroupEvidenceFromJSON,
    TraceGroupEvidenceFromJSONTyped,
    TraceGroupEvidenceToJSON,
    TraceGroupEvidenceToJSONTyped,
} from './TraceGroupEvidence';

/**
 *
 * @export
 * @interface TraceGroup
 */
export interface TraceGroup {
    /**
     *
     * @type {string}
     * @memberof TraceGroup
     */
    id: string;
    /**
     *
     * @type {string}
     * @memberof TraceGroup
     */
    name: string;
    /**
     *
     * @type {number}
     * @memberof TraceGroup
     */
    revision: number;
    /**
     *
     * @type {number}
     * @memberof TraceGroup
     */
    traceCount: number;
    /**
     *
     * @type {number}
     * @memberof TraceGroup
     */
    unreviewedTraceCount: number;
    /**
     *
     * @type {boolean}
     * @memberof TraceGroup
     */
    needsReview: boolean;
    /**
     *
     * @type {string}
     * @memberof TraceGroup
     */
    capabilityId: string | null;
    /**
     *
     * @type {boolean}
     * @memberof TraceGroup
     */
    mixed: boolean;
    /**
     *
     * @type {TraceGroupEvidence}
     * @memberof TraceGroup
     */
    evidence: TraceGroupEvidence;
    /**
     *
     * @type {Array<string>}
     * @memberof TraceGroup
     */
    sampleTraceIds: Array<string>;
    /**
     *
     * @type {Date}
     * @memberof TraceGroup
     */
    lastReviewedAt: Date | null;
    /**
     *
     * @type {number}
     * @memberof TraceGroup
     */
    lastReviewedTraceCount: number | null;
}

/**
 * Check if a given object implements the TraceGroup interface.
 */
export function instanceOfTraceGroup(value: object): value is TraceGroup {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('revision' in value) || value['revision'] === undefined) return false;
    if (!('traceCount' in value) || value['traceCount'] === undefined) return false;
    if (!('unreviewedTraceCount' in value) || value['unreviewedTraceCount'] === undefined) return false;
    if (!('needsReview' in value) || value['needsReview'] === undefined) return false;
    if (!('capabilityId' in value) || value['capabilityId'] === undefined) return false;
    if (!('mixed' in value) || value['mixed'] === undefined) return false;
    if (!('evidence' in value) || value['evidence'] === undefined) return false;
    if (!('sampleTraceIds' in value) || value['sampleTraceIds'] === undefined) return false;
    if (!('lastReviewedAt' in value) || value['lastReviewedAt'] === undefined) return false;
    if (!('lastReviewedTraceCount' in value) || value['lastReviewedTraceCount'] === undefined) return false;
    return true;
}

export function TraceGroupFromJSON(json: any): TraceGroup {
    return TraceGroupFromJSONTyped(json, false);
}

export function TraceGroupFromJSONTyped(json: any, ignoreDiscriminator: boolean): TraceGroup {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'],
        'name': json['name'],
        'revision': json['revision'],
        'traceCount': json['trace_count'],
        'unreviewedTraceCount': json['unreviewed_trace_count'],
        'needsReview': json['needs_review'],
        'capabilityId': json['capability_id'],
        'mixed': json['mixed'],
        'evidence': TraceGroupEvidenceFromJSON(json['evidence']),
        'sampleTraceIds': json['sample_trace_ids'],
        'lastReviewedAt': (json['last_reviewed_at'] == null ? null : new Date(json['last_reviewed_at'])),
        'lastReviewedTraceCount': json['last_reviewed_trace_count'],
    };
}

export function TraceGroupToJSON(json: any): TraceGroup {
    return TraceGroupToJSONTyped(json, false);
}

export function TraceGroupToJSONTyped(value?: TraceGroup | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'id': value['id'],
        'name': value['name'],
        'revision': value['revision'],
        'trace_count': value['traceCount'],
        'unreviewed_trace_count': value['unreviewedTraceCount'],
        'needs_review': value['needsReview'],
        'capability_id': value['capabilityId'],
        'mixed': value['mixed'],
        'evidence': TraceGroupEvidenceToJSON(value['evidence']),
        'sample_trace_ids': value['sampleTraceIds'],
        'last_reviewed_at': value['lastReviewedAt'] == null ? value['lastReviewedAt'] : value['lastReviewedAt'].toISOString(),
        'last_reviewed_trace_count': value['lastReviewedTraceCount'],
    };
}
