/* tslint:disable */
/* eslint-disable */
/**
 * Overbae API
 * Backend API for the Overclaw / Overmind platform.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TraceStatusEnum } from './TraceStatusEnum';
import {
    TraceStatusEnumFromJSON,
    TraceStatusEnumFromJSONTyped,
    TraceStatusEnumToJSON,
    TraceStatusEnumToJSONTyped,
} from './TraceStatusEnum';
import type { TraceUsage } from './TraceUsage';
import {
    TraceUsageFromJSON,
    TraceUsageFromJSONTyped,
    TraceUsageToJSON,
    TraceUsageToJSONTyped,
} from './TraceUsage';
import type { Span } from './Span';
import {
    SpanFromJSON,
    SpanFromJSONTyped,
    SpanToJSON,
    SpanToJSONTyped,
} from './Span';

/**
 * ``GET /api/traces/{trace_id}/`` payload — root summary + every span.
 * @export
 * @interface TraceDetail
 */
export interface TraceDetail {
    /**
     *
     * @type {string}
     * @memberof TraceDetail
     */
    traceId: string;
    /**
     *
     * @type {Span}
     * @memberof TraceDetail
     */
    root: Span | null;
    /**
     *
     * @type {number}
     * @memberof TraceDetail
     */
    spanCount: number;
    /**
     *
     * @type {TraceStatusEnum}
     * @memberof TraceDetail
     */
    traceStatus: TraceStatusEnum;
    /**
     *
     * @type {TraceUsage}
     * @memberof TraceDetail
     */
    usage: TraceUsage;
    /**
     *
     * @type {Array<Span>}
     * @memberof TraceDetail
     */
    spans: Array<Span>;
}



/**
 * Check if a given object implements the TraceDetail interface.
 */
export function instanceOfTraceDetail(value: object): value is TraceDetail {
    if (!('traceId' in value) || value['traceId'] === undefined) return false;
    if (!('root' in value) || value['root'] === undefined) return false;
    if (!('spanCount' in value) || value['spanCount'] === undefined) return false;
    if (!('traceStatus' in value) || value['traceStatus'] === undefined) return false;
    if (!('usage' in value) || value['usage'] === undefined) return false;
    if (!('spans' in value) || value['spans'] === undefined) return false;
    return true;
}

export function TraceDetailFromJSON(json: any): TraceDetail {
    return TraceDetailFromJSONTyped(json, false);
}

export function TraceDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): TraceDetail {
    if (json == null) {
        return json;
    }
    return {

        'traceId': json['trace_id'],
        'root': SpanFromJSON(json['root']),
        'spanCount': json['span_count'],
        'traceStatus': TraceStatusEnumFromJSON(json['trace_status']),
        'usage': TraceUsageFromJSON(json['usage']),
        'spans': ((json['spans'] as Array<any>).map(SpanFromJSON)),
    };
}

export function TraceDetailToJSON(json: any): TraceDetail {
    return TraceDetailToJSONTyped(json, false);
}

export function TraceDetailToJSONTyped(value?: TraceDetail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'trace_id': value['traceId'],
        'root': SpanToJSON(value['root']),
        'span_count': value['spanCount'],
        'trace_status': TraceStatusEnumToJSON(value['traceStatus']),
        'usage': TraceUsageToJSON(value['usage']),
        'spans': ((value['spans'] as Array<any>).map(SpanToJSON)),
    };
}
