/* tslint:disable */
/* eslint-disable */
/**
 * Overbae API
 * Backend API for the Overclaw / Overmind platform.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TrainingTypeEnum } from './TrainingTypeEnum';
import {
    TrainingTypeEnumFromJSON,
    TrainingTypeEnumFromJSONTyped,
    TrainingTypeEnumToJSON,
    TrainingTypeEnumToJSONTyped,
} from './TrainingTypeEnum';

/**
 *
 * @export
 * @interface TrainingPreparationRequestRequest
 */
export interface TrainingPreparationRequestRequest {
    /**
     *
     * @type {string}
     * @memberof TrainingPreparationRequestRequest
     */
    dataset: string;
    /**
     *
     * @type {string}
     * @memberof TrainingPreparationRequestRequest
     */
    cell?: string;
    /**
     *
     * @type {string}
     * @memberof TrainingPreparationRequestRequest
     */
    validationDataset?: string | null;
    /**
     *
     * @type {string}
     * @memberof TrainingPreparationRequestRequest
     */
    model: string;
    /**
     *
     * @type {number}
     * @memberof TrainingPreparationRequestRequest
     */
    contextLength: number;
    /**
     *
     * @type {TrainingTypeEnum}
     * @memberof TrainingPreparationRequestRequest
     */
    trainingType?: TrainingTypeEnum;
}



/**
 * Check if a given object implements the TrainingPreparationRequestRequest interface.
 */
export function instanceOfTrainingPreparationRequestRequest(value: object): value is TrainingPreparationRequestRequest {
    if (!('dataset' in value) || value['dataset'] === undefined) return false;
    if (!('model' in value) || value['model'] === undefined) return false;
    if (!('contextLength' in value) || value['contextLength'] === undefined) return false;
    return true;
}

export function TrainingPreparationRequestRequestFromJSON(json: any): TrainingPreparationRequestRequest {
    return TrainingPreparationRequestRequestFromJSONTyped(json, false);
}

export function TrainingPreparationRequestRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrainingPreparationRequestRequest {
    if (json == null) {
        return json;
    }
    return {

        'dataset': json['dataset'],
        'cell': json['cell'] == null ? undefined : json['cell'],
        'validationDataset': json['validation_dataset'] == null ? undefined : json['validation_dataset'],
        'model': json['model'],
        'contextLength': json['context_length'],
        'trainingType': json['training_type'] == null ? undefined : TrainingTypeEnumFromJSON(json['training_type']),
    };
}

export function TrainingPreparationRequestRequestToJSON(json: any): TrainingPreparationRequestRequest {
    return TrainingPreparationRequestRequestToJSONTyped(json, false);
}

export function TrainingPreparationRequestRequestToJSONTyped(value?: TrainingPreparationRequestRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'dataset': value['dataset'],
        'cell': value['cell'],
        'validation_dataset': value['validationDataset'],
        'model': value['model'],
        'context_length': value['contextLength'],
        'training_type': TrainingTypeEnumToJSON(value['trainingType']),
    };
}
