/* tslint:disable */
/* eslint-disable */
/**
 * Overbae API
 * Backend API for the Overclaw / Overmind platform.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface UploadInspection
 */
export interface UploadInspection {
    /**
     *
     * @type {string}
     * @memberof UploadInspection
     */
    filename: string;
    /**
     *
     * @type {number}
     * @memberof UploadInspection
     */
    bytes: number;
    /**
     *
     * @type {number}
     * @memberof UploadInspection
     */
    rows: number;
}

/**
 * Check if a given object implements the UploadInspection interface.
 */
export function instanceOfUploadInspection(value: object): value is UploadInspection {
    if (!('filename' in value) || value['filename'] === undefined) return false;
    if (!('bytes' in value) || value['bytes'] === undefined) return false;
    if (!('rows' in value) || value['rows'] === undefined) return false;
    return true;
}

export function UploadInspectionFromJSON(json: any): UploadInspection {
    return UploadInspectionFromJSONTyped(json, false);
}

export function UploadInspectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadInspection {
    if (json == null) {
        return json;
    }
    return {

        'filename': json['filename'],
        'bytes': json['bytes'],
        'rows': json['rows'],
    };
}

export function UploadInspectionToJSON(json: any): UploadInspection {
    return UploadInspectionToJSONTyped(json, false);
}

export function UploadInspectionToJSONTyped(value?: UploadInspection | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'filename': value['filename'],
        'bytes': value['bytes'],
        'rows': value['rows'],
    };
}
