/* tslint:disable */
/* eslint-disable */
/**
 * Overbae API
 * Backend API for the Overclaw / Overmind platform.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface UserOnboarding
 */
export interface UserOnboarding {
    /**
     *
     * @type {string}
     * @memberof UserOnboarding
     */
    readonly id: string;
    /**
     *
     * @type {string}
     * @memberof UserOnboarding
     */
    step?: string;
    /**
     *
     * @type {string}
     * @memberof UserOnboarding
     */
    status?: string;
    /**
     *
     * @type {any}
     * @memberof UserOnboarding
     */
    priorities?: any | null;
    /**
     *
     * @type {string}
     * @memberof UserOnboarding
     */
    description?: string;
    /**
     *
     * @type {Date}
     * @memberof UserOnboarding
     */
    readonly createdAt: Date;
    /**
     *
     * @type {number}
     * @memberof UserOnboarding
     */
    readonly user: number;
}

/**
 * Check if a given object implements the UserOnboarding interface.
 */
export function instanceOfUserOnboarding(value: object): value is UserOnboarding {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('user' in value) || value['user'] === undefined) return false;
    return true;
}

export function UserOnboardingFromJSON(json: any): UserOnboarding {
    return UserOnboardingFromJSONTyped(json, false);
}

export function UserOnboardingFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserOnboarding {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'],
        'step': json['step'] == null ? undefined : json['step'],
        'status': json['status'] == null ? undefined : json['status'],
        'priorities': json['priorities'] == null ? undefined : json['priorities'],
        'description': json['description'] == null ? undefined : json['description'],
        'createdAt': (new Date(json['created_at'])),
        'user': json['user'],
    };
}

export function UserOnboardingToJSON(json: any): UserOnboarding {
    return UserOnboardingToJSONTyped(json, false);
}

export function UserOnboardingToJSONTyped(value?: Omit<UserOnboarding, 'id'|'created_at'|'user'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'step': value['step'],
        'status': value['status'],
        'priorities': value['priorities'],
        'description': value['description'],
    };
}
