/**
 * The only module allowed to read the raw glyph table and the title marks (enforced by
 * `bun run check:design`): app code renders semantic names, so a concept maps to one glyph.
 *
 * Adding a glyph: `name: glyph("<svg file name>")` here, then `bun run icons:vendor`.
 */
import { glyph } from "./glyph";
import {
  BarbellVertical,
  DesktopTower,
  Eyeball,
  LockersTwoFilled,
  OvermindEyeMono,
  Chart as TitleChart,
} from "./page-title";

export const Icon = {
  add: glyph("plus"),
  addUser: glyph("user-plus"),
  agent: glyph("robot-body"),
  agentTesting: glyph("test-tubes"),
  ai: glyph("sparkle"), // the "optimise / AI / magic" affordance (not Sparkles)
  algorithm: glyph("algorithm"),
  analytics: glyph("analytics"),
  arrowDown: glyph("arrow-down"),
  arrowUp: glyph("arrow-up"),
  aspectRatio: glyph("aspect-ratio"),
  back: glyph("arrow-left"),
  bell: glyph("bell"),
  capability: glyph("robot-body"),
  capabilityOff: glyph("avatar-circle-x"),
  chart: glyph("chart"),
  chartBar: glyph("chart-bar-big"),
  checkbox: glyph("checkbox"),
  chevronDown: glyph("chevron-down"),
  chevronLeft: glyph("chevron-left"),
  chevronRight: glyph("chevron-right"),
  chevronUp: glyph("chevron-up"),
  circle: glyph("circle"),
  clipboard: glyph("clipboard"),
  close: glyph("cancel"), // the "X" — close / dismiss / cancel only
  code: glyph("braces"),
  columns: glyph("grid-3x2"),
  components: glyph("blocks"),
  copy: glyph("copy"),
  cost: glyph("coins"),
  credits: glyph("money-bag-coins"), // Overmind credits balance/amounts (never plain USD)
  dataset: glyph("database"),
  datasetAdd: glyph("database-zap"),
  delete: glyph("trash"), // the ONLY delete glyph (never the Cancel "X")
  diff: glyph("git-pull-request"),
  docs: glyph("book-open"),
  download: glyph("download"),
  edit: glyph("pen-square"),
  eval: glyph("chart-column-stacked"),
  evaluations: LockersTwoFilled,
  expand: glyph("expand"),
  externalLink: glyph("external-link"),
  failed: glyph("cancel"), // same "X" glyph as close, but a distinct semantic entry
  file: glyph("file-text"),
  files: glyph("files"),
  filter: glyph("filter"),
  finetuning: BarbellVertical,
  folder: glyph("folder"),
  folderAdd: glyph("folder-plus"),
  forward: glyph("arrow-right"),
  gitBranch: glyph("git-branch"),
  grid: glyph("grid-3x3"),
  hash: glyph("hash"),
  help: glyph("circle-question"),
  hide: glyph("eye-off"),
  history: glyph("clock"), // same clock glyph as `job`, but a distinct semantic entry
  home: glyph("home"),
  inference: glyph("binary"),
  inferenceTitle: DesktopTower,
  info: glyph("info-box"),
  integrations: glyph("cable"),
  job: glyph("clock"),
  link: glyph("link"),
  list: glyph("bulletlist"),
  listBox: glyph("list-box"),
  loader: glyph("loader"), // prefer the <Spinner> component; this is for icon slots only
  lock: glyph("lock"),
  login: glyph("login"),
  logout: glyph("logout"),
  megaphone: glyph("megaphone"),
  menu: glyph("menu"),
  minimap: glyph("map"),
  model: glyph("cpu"),
  models: glyph("neural-network-2"),
  notify: glyph("bell"),
  observability: glyph("eye"),
  observabilityTitle: Eyeball,
  optimiser: glyph("speed-fast"),
  optimiserTitle: TitleChart,
  overmind: OvermindEyeMono,
  panelLeftClose: glyph("arrow-bar-left"),
  panelLeftOpen: glyph("arrow-bar-right"),
  pin: glyph("anchor"),
  play: glyph("play"),
  project: glyph("box"),
  projectAdd: glyph("box-plus"),
  refresh: glyph("reload"),
  search: glyph("search"),
  send: glyph("send"),
  server: glyph("server"),
  session: glyph("comment"),
  settings: glyph("settings-2"), // the plain settings glyph — the workshop cog is `workshop`
  skull: glyph("skull"),
  sort: glyph("sort-vertical"),
  sortable: glyph("chevrons-vertical"),
  stop: glyph("power-off"),
  success: glyph("check"),
  successDouble: glyph("check-double"),
  target: glyph("target"),
  terminal: glyph("terminal"),
  themeDark: glyph("moon-star"),
  themeLight: glyph("sun"),
  tool: glyph("tool-case"),
  training: glyph("sliders-horizontal"),
  trophy: glyph("trophy"),
  undo: glyph("undo"),
  unlock: glyph("unlock"),
  upload: glyph("upload"),
  user: glyph("user"),
  view: glyph("eye"),
  warning: glyph("warning-diamond"),
  workshop: glyph("settings-cog-2"),
  zap: glyph("zap"),
} as const;

export type IconName = keyof typeof Icon;
