/**
 * The only module allowed to import the raw glyphs in `./pixelart` (enforced by
 * `bun run check:design`): app code renders semantic names, so a concept maps to
 * one glyph.
 */

import {
  BarbellVertical,
  DesktopTower,
  Eyeball,
  LockersTwoFilled,
  OvermindEyeMono,
  Chart as TitleChart,
} from "./page-title";
import {
  Algorithm,
  Analytics,
  Anchor,
  ArrowBarLeft,
  ArrowBarRight,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  AspectRatio,
  AvatarCircleX,
  Bell,
  Binary,
  Blocks,
  BookOpen,
  Box,
  BoxPlus,
  Braces,
  Bulletlist,
  Cable,
  Cancel,
  Chart,
  ChartBarBig,
  ChartColumnStacked,
  Check,
  Checkbox,
  CheckDouble,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsVertical,
  ChevronUp,
  Circle,
  CircleQuestion,
  Clipboard,
  Clock,
  Coins,
  Comment,
  Copy,
  Cpu,
  Database,
  DatabaseZap,
  Download,
  Expand,
  ExternalLink,
  Eye,
  EyeOff,
  Files,
  FileText,
  Filter,
  Folder,
  FolderPlus,
  GitBranch,
  GitPullRequest,
  Grid3x2,
  Grid3x3,
  Hash,
  Home,
  InfoBox,
  Link,
  ListBox,
  Loader,
  Lock,
  Login,
  Logout,
  MapGlyph,
  Megaphone,
  Menu,
  MoneyBagCoins,
  MoonStar,
  NeuralNetwork2,
  PenSquare,
  Play,
  Plus,
  PowerOff,
  Reload,
  RobotBody,
  Search,
  Send,
  Server,
  Settings2,
  SettingsCog2,
  Skull,
  SlidersHorizontal,
  SortVertical,
  Sparkle,
  SpeedFast,
  Sun,
  Target,
  Terminal,
  TestTubes,
  ToolCase,
  Trash,
  Trophy,
  Undo,
  Unlock,
  Upload,
  User,
  UserPlus,
  WarningDiamond,
  Zap,
} from "./pixelart";

export const Icon = {
  add: Plus,
  addUser: UserPlus,
  agent: RobotBody,
  agentTesting: TestTubes,
  ai: Sparkle, // the "optimise / AI / magic" affordance (not Sparkles)
  algorithm: Algorithm,
  analytics: Analytics,
  arrowDown: ArrowDown,
  arrowUp: ArrowUp,
  aspectRatio: AspectRatio,
  back: ArrowLeft,
  bell: Bell,
  capability: RobotBody,
  capabilityOff: AvatarCircleX,
  chart: Chart,
  chartBar: ChartBarBig,
  checkbox: Checkbox,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  circle: Circle,
  clipboard: Clipboard,
  close: Cancel, // the "X" — close / dismiss / cancel only
  code: Braces,
  columns: Grid3x2,
  components: Blocks,
  copy: Copy,
  cost: Coins,
  credits: MoneyBagCoins, // Overmind credits balance/amounts (never plain USD)
  dataset: Database,
  datasetAdd: DatabaseZap,
  delete: Trash, // the ONLY delete glyph (never the Cancel "X")
  diff: GitPullRequest,
  docs: BookOpen,
  download: Download,
  edit: PenSquare,
  eval: ChartColumnStacked,
  evaluations: LockersTwoFilled,
  expand: Expand,
  externalLink: ExternalLink,
  failed: Cancel, // same "X" glyph as close, but a distinct semantic entry
  file: FileText,
  files: Files,
  filter: Filter,
  finetuning: BarbellVertical,
  folder: Folder,
  folderAdd: FolderPlus,
  forward: ArrowRight,
  gitBranch: GitBranch,
  grid: Grid3x3,
  hash: Hash,
  help: CircleQuestion,
  hide: EyeOff,
  history: Clock, // same clock glyph as `job`, but a distinct semantic entry
  home: Home,
  inference: Binary,
  inferenceTitle: DesktopTower,
  info: InfoBox,
  integrations: Cable,
  job: Clock,
  link: Link,
  list: Bulletlist,
  listBox: ListBox,
  loader: Loader, // prefer the <Spinner> component; this is for icon slots only
  lock: Lock,
  login: Login,
  logout: Logout,
  megaphone: Megaphone,
  menu: Menu,
  minimap: MapGlyph,
  model: Cpu,
  models: NeuralNetwork2,
  notify: Bell,
  observability: Eye,
  observabilityTitle: Eyeball,
  optimiser: SpeedFast,
  optimiserTitle: TitleChart,
  overmind: OvermindEyeMono,
  panelLeftClose: ArrowBarLeft,
  panelLeftOpen: ArrowBarRight,
  pin: Anchor,
  play: Play,
  project: Box,
  projectAdd: BoxPlus,
  refresh: Reload,
  search: Search,
  send: Send,
  server: Server,
  session: Comment,
  settings: Settings2, // the plain settings glyph — the workshop cog is `workshop`
  skull: Skull,
  sort: SortVertical,
  sortable: ChevronsVertical,
  stop: PowerOff,
  success: Check,
  successDouble: CheckDouble,
  target: Target,
  terminal: Terminal,
  themeDark: MoonStar,
  themeLight: Sun,
  tool: ToolCase,
  training: SlidersHorizontal,
  trophy: Trophy,
  undo: Undo,
  unlock: Unlock,
  upload: Upload,
  user: User,
  view: Eye,
  warning: WarningDiamond,
  workshop: SettingsCog2,
  zap: Zap,
} as const;

export type IconName = keyof typeof Icon;
