/* tslint:disable */
/* eslint-disable */
/**
 * Overbae API
 * Backend API for the Overclaw / Overmind platform.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BehaviourAuthoringContextResponse,
  BehaviourCoverageResponse,
  BehaviourEvaluator,
  PaginatedBehaviourList,
} from '../models/index';
import {
    BehaviourAuthoringContextResponseFromJSON,
    BehaviourAuthoringContextResponseToJSON,
    BehaviourCoverageResponseFromJSON,
    BehaviourCoverageResponseToJSON,
    BehaviourEvaluatorFromJSON,
    BehaviourEvaluatorToJSON,
    PaginatedBehaviourListFromJSON,
    PaginatedBehaviourListToJSON,
} from '../models/index';

export interface BehavioursAuthoringContextRetrieveRequest {
    id: string;
}

export interface BehavioursCoverageRetrieveRequest {
    capability: string;
}

export interface BehavioursEvaluatorsListRequest {
    id: string;
    ordering?: string;
    search?: string;
}

export interface BehavioursListRequest {
    ordering?: string;
    page?: number;
    pageSize?: number;
    search?: string;
}

/**
 *
 */
export class BehavioursApi extends runtime.BaseAPI {

    /**
     * Preloaded context for task-scoped eval authoring: the behaviour\'s latest contract, so the picker can list the steps a judge may target.
     */
    async behavioursAuthoringContextRetrieveRaw(requestParameters: BehavioursAuthoringContextRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BehaviourAuthoringContextResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling behavioursAuthoringContextRetrieve().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ClerkBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/behaviours/{id}/authoring-context/`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BehaviourAuthoringContextResponseFromJSON(jsonValue));
    }

    /**
     * Preloaded context for task-scoped eval authoring: the behaviour\'s latest contract, so the picker can list the steps a judge may target.
     */
    async behavioursAuthoringContextRetrieve(requestParameters: BehavioursAuthoringContextRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BehaviourAuthoringContextResponse> {
        const response = await this.behavioursAuthoringContextRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Per-behaviour and per-step eval-coverage rollups for ?capability=<id>.
     */
    async behavioursCoverageRetrieveRaw(requestParameters: BehavioursCoverageRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BehaviourCoverageResponse>> {
        if (requestParameters['capability'] == null) {
            throw new runtime.RequiredError(
                'capability',
                'Required parameter "capability" was null or undefined when calling behavioursCoverageRetrieve().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['capability'] != null) {
            queryParameters['capability'] = requestParameters['capability'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ClerkBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/behaviours/coverage/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BehaviourCoverageResponseFromJSON(jsonValue));
    }

    /**
     * Per-behaviour and per-step eval-coverage rollups for ?capability=<id>.
     */
    async behavioursCoverageRetrieve(requestParameters: BehavioursCoverageRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BehaviourCoverageResponse> {
        const response = await this.behavioursCoverageRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * The behaviour\'s compiled eval suite (step + outcome evaluators).
     */
    async behavioursEvaluatorsListRaw(requestParameters: BehavioursEvaluatorsListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<BehaviourEvaluator>>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling behavioursEvaluatorsList().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['ordering'] != null) {
            queryParameters['ordering'] = requestParameters['ordering'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ClerkBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/behaviours/{id}/evaluators/`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(BehaviourEvaluatorFromJSON));
    }

    /**
     * The behaviour\'s compiled eval suite (step + outcome evaluators).
     */
    async behavioursEvaluatorsList(requestParameters: BehavioursEvaluatorsListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<BehaviourEvaluator>> {
        const response = await this.behavioursEvaluatorsListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async behavioursListRaw(requestParameters: BehavioursListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedBehaviourList>> {
        const queryParameters: any = {};

        if (requestParameters['ordering'] != null) {
            queryParameters['ordering'] = requestParameters['ordering'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['page_size'] = requestParameters['pageSize'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ClerkBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/behaviours/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedBehaviourListFromJSON(jsonValue));
    }

    /**
     */
    async behavioursList(requestParameters: BehavioursListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedBehaviourList> {
        const response = await this.behavioursListRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
