/* tslint:disable */
/* eslint-disable */
/**
 * Overbae API
 * Backend API for the Overclaw / Overmind platform.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AuthTokensResponse,
  ChatGPTAccountRequestRequest,
  ChatGPTDisconnect,
  ChatGPTLogin,
  ChatGPTLoginConfirmRequest,
  ChatGPTLoginHandoff,
  ChatGPTLoginRequestRequest,
  ChatGPTModel,
  ChatGPTStart,
  ChatGPTStartRequestRequest,
  PatchedWorkshopFundingRequestRequest,
  WorkshopFunding,
} from '../models/index';
import {
    AuthTokensResponseFromJSON,
    AuthTokensResponseToJSON,
    ChatGPTAccountRequestRequestFromJSON,
    ChatGPTAccountRequestRequestToJSON,
    ChatGPTDisconnectFromJSON,
    ChatGPTDisconnectToJSON,
    ChatGPTLoginFromJSON,
    ChatGPTLoginToJSON,
    ChatGPTLoginConfirmRequestFromJSON,
    ChatGPTLoginConfirmRequestToJSON,
    ChatGPTLoginHandoffFromJSON,
    ChatGPTLoginHandoffToJSON,
    ChatGPTLoginRequestRequestFromJSON,
    ChatGPTLoginRequestRequestToJSON,
    ChatGPTModelFromJSON,
    ChatGPTModelToJSON,
    ChatGPTStartFromJSON,
    ChatGPTStartToJSON,
    ChatGPTStartRequestRequestFromJSON,
    ChatGPTStartRequestRequestToJSON,
    PatchedWorkshopFundingRequestRequestFromJSON,
    PatchedWorkshopFundingRequestRequestToJSON,
    WorkshopFundingFromJSON,
    WorkshopFundingToJSON,
} from '../models/index';

export interface ChatgptCallbackSessionCreateRequest {
    chatGPTLoginConfirmRequest?: ChatGPTLoginConfirmRequest;
}

export interface ChatgptDisconnectCreateRequest {
    chatGPTAccountRequestRequest: ChatGPTAccountRequestRequest;
}

export interface ChatgptLoginCreateRequest {
    chatGPTLoginRequestRequest?: ChatGPTLoginRequestRequest;
}

export interface ChatgptModelsListRequest {
    accountId: string;
}

export interface ChatgptPartialUpdateRequest {
    patchedWorkshopFundingRequestRequest?: PatchedWorkshopFundingRequestRequest;
}

export interface ChatgptStartCreateRequest {
    chatGPTStartRequestRequest?: ChatGPTStartRequestRequest;
}

/**
 *
 */
export class ChatGPTApi extends runtime.BaseAPI {

    /**
     */
    async chatgptCallbackSessionCreateRaw(requestParameters: ChatgptCallbackSessionCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthTokensResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/chatgpt/callback/session/`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ChatGPTLoginConfirmRequestToJSON(requestParameters['chatGPTLoginConfirmRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthTokensResponseFromJSON(jsonValue));
    }

    /**
     */
    async chatgptCallbackSessionCreate(requestParameters: ChatgptCallbackSessionCreateRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthTokensResponse> {
        const response = await this.chatgptCallbackSessionCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async chatgptCallbackSessionRetrieveRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ChatGPTLoginHandoff>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/chatgpt/callback/session/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ChatGPTLoginHandoffFromJSON(jsonValue));
    }

    /**
     */
    async chatgptCallbackSessionRetrieve(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ChatGPTLoginHandoff> {
        const response = await this.chatgptCallbackSessionRetrieveRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async chatgptDisconnectCreateRaw(requestParameters: ChatgptDisconnectCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ChatGPTDisconnect>> {
        if (requestParameters['chatGPTAccountRequestRequest'] == null) {
            throw new runtime.RequiredError(
                'chatGPTAccountRequestRequest',
                'Required parameter "chatGPTAccountRequestRequest" was null or undefined when calling chatgptDisconnectCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ClerkBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/chatgpt/disconnect/`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ChatGPTAccountRequestRequestToJSON(requestParameters['chatGPTAccountRequestRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ChatGPTDisconnectFromJSON(jsonValue));
    }

    /**
     */
    async chatgptDisconnectCreate(requestParameters: ChatgptDisconnectCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ChatGPTDisconnect> {
        const response = await this.chatgptDisconnectCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async chatgptLoginCreateRaw(requestParameters: ChatgptLoginCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ChatGPTStart>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/chatgpt/login/`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ChatGPTLoginRequestRequestToJSON(requestParameters['chatGPTLoginRequestRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ChatGPTStartFromJSON(jsonValue));
    }

    /**
     */
    async chatgptLoginCreate(requestParameters: ChatgptLoginCreateRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ChatGPTStart> {
        const response = await this.chatgptLoginCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async chatgptLoginRetrieveRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ChatGPTLogin>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/chatgpt/login/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ChatGPTLoginFromJSON(jsonValue));
    }

    /**
     */
    async chatgptLoginRetrieve(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ChatGPTLogin> {
        const response = await this.chatgptLoginRetrieveRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async chatgptModelsListRaw(requestParameters: ChatgptModelsListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ChatGPTModel>>> {
        if (requestParameters['accountId'] == null) {
            throw new runtime.RequiredError(
                'accountId',
                'Required parameter "accountId" was null or undefined when calling chatgptModelsList().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['accountId'] != null) {
            queryParameters['account_id'] = requestParameters['accountId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ClerkBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/chatgpt/models/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ChatGPTModelFromJSON));
    }

    /**
     */
    async chatgptModelsList(requestParameters: ChatgptModelsListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ChatGPTModel>> {
        const response = await this.chatgptModelsListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async chatgptPartialUpdateRaw(requestParameters: ChatgptPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WorkshopFunding>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ClerkBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/chatgpt/`;

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PatchedWorkshopFundingRequestRequestToJSON(requestParameters['patchedWorkshopFundingRequestRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WorkshopFundingFromJSON(jsonValue));
    }

    /**
     */
    async chatgptPartialUpdate(requestParameters: ChatgptPartialUpdateRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WorkshopFunding> {
        const response = await this.chatgptPartialUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async chatgptRetrieveRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WorkshopFunding>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ClerkBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/chatgpt/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WorkshopFundingFromJSON(jsonValue));
    }

    /**
     */
    async chatgptRetrieve(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WorkshopFunding> {
        const response = await this.chatgptRetrieveRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async chatgptStartCreateRaw(requestParameters: ChatgptStartCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ChatGPTStart>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ClerkBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/chatgpt/start/`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ChatGPTStartRequestRequestToJSON(requestParameters['chatGPTStartRequestRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ChatGPTStartFromJSON(jsonValue));
    }

    /**
     */
    async chatgptStartCreate(requestParameters: ChatgptStartCreateRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ChatGPTStart> {
        const response = await this.chatgptStartCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
