/* tslint:disable */
/* eslint-disable */
/**
 * Overbae API
 * Backend API for the Overclaw / Overmind platform.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DecisionPerformance,
  PaginatedDecisionPerformanceList,
  PerformanceRequestRequest,
} from '../models/index';
import {
    DecisionPerformanceFromJSON,
    DecisionPerformanceToJSON,
    PaginatedDecisionPerformanceListFromJSON,
    PaginatedDecisionPerformanceListToJSON,
    PerformanceRequestRequestFromJSON,
    PerformanceRequestRequestToJSON,
} from '../models/index';

export interface DecisionPerformanceCreateRequest {
    performanceRequestRequest: PerformanceRequestRequest;
}

export interface DecisionPerformanceListRequest {
    evaluation?: string;
    ordering?: string;
    page?: number;
    pageSize?: number;
    project?: string;
    search?: string;
    state?: string;
}

export interface DecisionPerformanceResumeCreateRequest {
    id: string;
}

export interface DecisionPerformanceRetrieveRequest {
    id: string;
}

/**
 *
 */
export class DecisionPerformanceApi extends runtime.BaseAPI {

    /**
     */
    async decisionPerformanceCreateRaw(requestParameters: DecisionPerformanceCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DecisionPerformance>> {
        if (requestParameters['performanceRequestRequest'] == null) {
            throw new runtime.RequiredError(
                'performanceRequestRequest',
                'Required parameter "performanceRequestRequest" was null or undefined when calling decisionPerformanceCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ClerkBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/decision-performance/`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PerformanceRequestRequestToJSON(requestParameters['performanceRequestRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DecisionPerformanceFromJSON(jsonValue));
    }

    /**
     */
    async decisionPerformanceCreate(requestParameters: DecisionPerformanceCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DecisionPerformance> {
        const response = await this.decisionPerformanceCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async decisionPerformanceListRaw(requestParameters: DecisionPerformanceListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedDecisionPerformanceList>> {
        const queryParameters: any = {};

        if (requestParameters['evaluation'] != null) {
            queryParameters['evaluation'] = requestParameters['evaluation'];
        }

        if (requestParameters['ordering'] != null) {
            queryParameters['ordering'] = requestParameters['ordering'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['page_size'] = requestParameters['pageSize'];
        }

        if (requestParameters['project'] != null) {
            queryParameters['project'] = requestParameters['project'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        if (requestParameters['state'] != null) {
            queryParameters['state'] = requestParameters['state'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ClerkBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/decision-performance/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedDecisionPerformanceListFromJSON(jsonValue));
    }

    /**
     */
    async decisionPerformanceList(requestParameters: DecisionPerformanceListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedDecisionPerformanceList> {
        const response = await this.decisionPerformanceListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async decisionPerformanceResumeCreateRaw(requestParameters: DecisionPerformanceResumeCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DecisionPerformance>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling decisionPerformanceResumeCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ClerkBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/decision-performance/{id}/resume/`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DecisionPerformanceFromJSON(jsonValue));
    }

    /**
     */
    async decisionPerformanceResumeCreate(requestParameters: DecisionPerformanceResumeCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DecisionPerformance> {
        const response = await this.decisionPerformanceResumeCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async decisionPerformanceRetrieveRaw(requestParameters: DecisionPerformanceRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DecisionPerformance>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling decisionPerformanceRetrieve().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ClerkBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/decision-performance/{id}/`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DecisionPerformanceFromJSON(jsonValue));
    }

    /**
     */
    async decisionPerformanceRetrieve(requestParameters: DecisionPerformanceRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DecisionPerformance> {
        const response = await this.decisionPerformanceRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
