/* tslint:disable */
/* eslint-disable */
/**
 * Overbae API
 * Backend API for the Overclaw / Overmind platform.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PaginatedScoreList,
  Score,
} from '../models/index';
import {
    PaginatedScoreListFromJSON,
    PaginatedScoreListToJSON,
    ScoreFromJSON,
    ScoreToJSON,
} from '../models/index';

export interface EvalScoresListRequest {
    dataType?: EvalScoresListDataTypeEnum;
    evaluator?: string;
    failureRole?: EvalScoresListFailureRoleEnum;
    name?: string;
    ordering?: string;
    page?: number;
    pageSize?: number;
    run?: string;
    sample?: string;
    scope?: string;
    search?: string;
    source?: EvalScoresListSourceEnum;
    valueMax?: number;
    valueMin?: number;
    variant?: string;
}

export interface EvalScoresRetrieveRequest {
    id: string;
}

/**
 *
 */
export class EvalScoresApi extends runtime.BaseAPI {

    /**
     * List scores
     */
    async evalScoresListRaw(requestParameters: EvalScoresListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedScoreList>> {
        const queryParameters: any = {};

        if (requestParameters['dataType'] != null) {
            queryParameters['data_type'] = requestParameters['dataType'];
        }

        if (requestParameters['evaluator'] != null) {
            queryParameters['evaluator'] = requestParameters['evaluator'];
        }

        if (requestParameters['failureRole'] != null) {
            queryParameters['failure_role'] = requestParameters['failureRole'];
        }

        if (requestParameters['name'] != null) {
            queryParameters['name'] = requestParameters['name'];
        }

        if (requestParameters['ordering'] != null) {
            queryParameters['ordering'] = requestParameters['ordering'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['page_size'] = requestParameters['pageSize'];
        }

        if (requestParameters['run'] != null) {
            queryParameters['run'] = requestParameters['run'];
        }

        if (requestParameters['sample'] != null) {
            queryParameters['sample'] = requestParameters['sample'];
        }

        if (requestParameters['scope'] != null) {
            queryParameters['scope'] = requestParameters['scope'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        if (requestParameters['source'] != null) {
            queryParameters['source'] = requestParameters['source'];
        }

        if (requestParameters['valueMax'] != null) {
            queryParameters['value_max'] = requestParameters['valueMax'];
        }

        if (requestParameters['valueMin'] != null) {
            queryParameters['value_min'] = requestParameters['valueMin'];
        }

        if (requestParameters['variant'] != null) {
            queryParameters['variant'] = requestParameters['variant'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ClerkBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/eval-scores/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedScoreListFromJSON(jsonValue));
    }

    /**
     * List scores
     */
    async evalScoresList(requestParameters: EvalScoresListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedScoreList> {
        const response = await this.evalScoresListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get score
     */
    async evalScoresRetrieveRaw(requestParameters: EvalScoresRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Score>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling evalScoresRetrieve().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ClerkBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/eval-scores/{id}/`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ScoreFromJSON(jsonValue));
    }

    /**
     * Get score
     */
    async evalScoresRetrieve(requestParameters: EvalScoresRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Score> {
        const response = await this.evalScoresRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const EvalScoresListDataTypeEnum = {
    boolean: 'boolean',
    categorical: 'categorical',
    numeric: 'numeric'
} as const;
export type EvalScoresListDataTypeEnum = typeof EvalScoresListDataTypeEnum[keyof typeof EvalScoresListDataTypeEnum];
/**
 * @export
 */
export const EvalScoresListFailureRoleEnum = {
    none: 'none',
    propagated: 'propagated',
    root_cause: 'root_cause'
} as const;
export type EvalScoresListFailureRoleEnum = typeof EvalScoresListFailureRoleEnum[keyof typeof EvalScoresListFailureRoleEnum];
/**
 * @export
 */
export const EvalScoresListSourceEnum = {
    api: 'api',
    eval: 'eval',
    human_annotation: 'human_annotation'
} as const;
export type EvalScoresListSourceEnum = typeof EvalScoresListSourceEnum[keyof typeof EvalScoresListSourceEnum];
