/* tslint:disable */
/* eslint-disable */
/**
 * Overbae API
 * Backend API for the Overclaw / Overmind platform.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PublicModel,
  PublicModelListResponse,
} from '../models/index';
import {
    PublicModelFromJSON,
    PublicModelToJSON,
    PublicModelListResponseFromJSON,
    PublicModelListResponseToJSON,
} from '../models/index';

export interface PublicModelsRetrieve2Request {
    slug: string;
}

/**
 *
 */
export class PublicApi extends runtime.BaseAPI {

    /**
     * Every enabled model on the Overmind platform, deduped across backends and sorted by tier then size. Powers the marketing site\'s /library page — no authentication required.
     * List the public model library
     */
    async publicModelsRetrieveRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PublicModelListResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/public/models/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PublicModelListResponseFromJSON(jsonValue));
    }

    /**
     * Every enabled model on the Overmind platform, deduped across backends and sorted by tier then size. Powers the marketing site\'s /library page — no authentication required.
     * List the public model library
     */
    async publicModelsRetrieve(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PublicModelListResponse> {
        const response = await this.publicModelsRetrieveRaw(initOverrides);
        return await response.value();
    }

    /**
     * A single model\'s catalog entry by slug — 404 if unknown or disabled.
     * Get a public model library entry
     */
    async publicModelsRetrieve2Raw(requestParameters: PublicModelsRetrieve2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PublicModel>> {
        if (requestParameters['slug'] == null) {
            throw new runtime.RequiredError(
                'slug',
                'Required parameter "slug" was null or undefined when calling publicModelsRetrieve2().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/public/models/{slug}/`;
        urlPath = urlPath.replace(`{${"slug"}}`, encodeURIComponent(String(requestParameters['slug'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PublicModelFromJSON(jsonValue));
    }

    /**
     * A single model\'s catalog entry by slug — 404 if unknown or disabled.
     * Get a public model library entry
     */
    async publicModelsRetrieve2(requestParameters: PublicModelsRetrieve2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PublicModel> {
        const response = await this.publicModelsRetrieve2Raw(requestParameters, initOverrides);
        return await response.value();
    }

}
