/* tslint:disable */
/* eslint-disable */
/**
 * Overbae API
 * Backend API for the Overclaw / Overmind platform.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ExperimentLaunchRequest,
  ExperimentRequestRequest,
  PaginatedTrainingExperimentList,
  TrainingExperiment,
  TrainingProfileRequest,
} from '../models/index';
import {
    ExperimentLaunchRequestFromJSON,
    ExperimentLaunchRequestToJSON,
    ExperimentRequestRequestFromJSON,
    ExperimentRequestRequestToJSON,
    PaginatedTrainingExperimentListFromJSON,
    PaginatedTrainingExperimentListToJSON,
    TrainingExperimentFromJSON,
    TrainingExperimentToJSON,
    TrainingProfileRequestFromJSON,
    TrainingProfileRequestToJSON,
} from '../models/index';

export interface TrainingExperimentsCreateRequest {
    experimentRequestRequest: ExperimentRequestRequest;
}

export interface TrainingExperimentsLaunchCreateRequest {
    id: string;
    experimentLaunchRequest?: ExperimentLaunchRequest;
}

export interface TrainingExperimentsListRequest {
    ordering?: string;
    page?: number;
    pageSize?: number;
    project?: string;
    search?: string;
    state?: string;
}

export interface TrainingExperimentsPrepareCreateRequest {
    id: string;
}

export interface TrainingExperimentsProfileCreateRequest {
    trainingProfileRequest: TrainingProfileRequest;
}

export interface TrainingExperimentsRetrieveRequest {
    id: string;
}

/**
 *
 */
export class TrainingExperimentsApi extends runtime.BaseAPI {

    /**
     */
    async trainingExperimentsCreateRaw(requestParameters: TrainingExperimentsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TrainingExperiment>> {
        if (requestParameters['experimentRequestRequest'] == null) {
            throw new runtime.RequiredError(
                'experimentRequestRequest',
                'Required parameter "experimentRequestRequest" was null or undefined when calling trainingExperimentsCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ClerkBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/training-experiments/`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ExperimentRequestRequestToJSON(requestParameters['experimentRequestRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TrainingExperimentFromJSON(jsonValue));
    }

    /**
     */
    async trainingExperimentsCreate(requestParameters: TrainingExperimentsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TrainingExperiment> {
        const response = await this.trainingExperimentsCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async trainingExperimentsLaunchCreateRaw(requestParameters: TrainingExperimentsLaunchCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TrainingExperiment>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling trainingExperimentsLaunchCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ClerkBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/training-experiments/{id}/launch/`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ExperimentLaunchRequestToJSON(requestParameters['experimentLaunchRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TrainingExperimentFromJSON(jsonValue));
    }

    /**
     */
    async trainingExperimentsLaunchCreate(requestParameters: TrainingExperimentsLaunchCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TrainingExperiment> {
        const response = await this.trainingExperimentsLaunchCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async trainingExperimentsListRaw(requestParameters: TrainingExperimentsListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedTrainingExperimentList>> {
        const queryParameters: any = {};

        if (requestParameters['ordering'] != null) {
            queryParameters['ordering'] = requestParameters['ordering'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['page_size'] = requestParameters['pageSize'];
        }

        if (requestParameters['project'] != null) {
            queryParameters['project'] = requestParameters['project'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        if (requestParameters['state'] != null) {
            queryParameters['state'] = requestParameters['state'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ClerkBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/training-experiments/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedTrainingExperimentListFromJSON(jsonValue));
    }

    /**
     */
    async trainingExperimentsList(requestParameters: TrainingExperimentsListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedTrainingExperimentList> {
        const response = await this.trainingExperimentsListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async trainingExperimentsPrepareCreateRaw(requestParameters: TrainingExperimentsPrepareCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TrainingExperiment>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling trainingExperimentsPrepareCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ClerkBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/training-experiments/{id}/prepare/`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TrainingExperimentFromJSON(jsonValue));
    }

    /**
     */
    async trainingExperimentsPrepareCreate(requestParameters: TrainingExperimentsPrepareCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TrainingExperiment> {
        const response = await this.trainingExperimentsPrepareCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async trainingExperimentsProfileCreateRaw(requestParameters: TrainingExperimentsProfileCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TrainingExperiment>> {
        if (requestParameters['trainingProfileRequest'] == null) {
            throw new runtime.RequiredError(
                'trainingProfileRequest',
                'Required parameter "trainingProfileRequest" was null or undefined when calling trainingExperimentsProfileCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ClerkBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/training-experiments/profile/`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TrainingProfileRequestToJSON(requestParameters['trainingProfileRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TrainingExperimentFromJSON(jsonValue));
    }

    /**
     */
    async trainingExperimentsProfileCreate(requestParameters: TrainingExperimentsProfileCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TrainingExperiment> {
        const response = await this.trainingExperimentsProfileCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async trainingExperimentsRetrieveRaw(requestParameters: TrainingExperimentsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TrainingExperiment>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling trainingExperimentsRetrieve().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ClerkBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/training-experiments/{id}/`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TrainingExperimentFromJSON(jsonValue));
    }

    /**
     */
    async trainingExperimentsRetrieve(requestParameters: TrainingExperimentsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TrainingExperiment> {
        const response = await this.trainingExperimentsRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
