/* tslint:disable */
/* eslint-disable */
/**
 * Overbae API
 * Backend API for the Overclaw / Overmind platform.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  TrainingPreparation,
  TrainingPreparationRequestRequest,
} from '../models/index';
import {
    TrainingPreparationFromJSON,
    TrainingPreparationToJSON,
    TrainingPreparationRequestRequestFromJSON,
    TrainingPreparationRequestRequestToJSON,
} from '../models/index';

export interface TrainingPreparationsCreateRequest {
    trainingPreparationRequestRequest: TrainingPreparationRequestRequest;
}

export interface TrainingPreparationsRetrieveRequest {
    id: string;
}

export interface TrainingPreparationsRetryCreateRequest {
    id: string;
}

/**
 *
 */
export class TrainingPreparationsApi extends runtime.BaseAPI {

    /**
     */
    async trainingPreparationsCreateRaw(requestParameters: TrainingPreparationsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TrainingPreparation>> {
        if (requestParameters['trainingPreparationRequestRequest'] == null) {
            throw new runtime.RequiredError(
                'trainingPreparationRequestRequest',
                'Required parameter "trainingPreparationRequestRequest" was null or undefined when calling trainingPreparationsCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ClerkBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/training-preparations/`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TrainingPreparationRequestRequestToJSON(requestParameters['trainingPreparationRequestRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TrainingPreparationFromJSON(jsonValue));
    }

    /**
     */
    async trainingPreparationsCreate(requestParameters: TrainingPreparationsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TrainingPreparation> {
        const response = await this.trainingPreparationsCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async trainingPreparationsRetrieveRaw(requestParameters: TrainingPreparationsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TrainingPreparation>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling trainingPreparationsRetrieve().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ClerkBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/training-preparations/{id}/`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TrainingPreparationFromJSON(jsonValue));
    }

    /**
     */
    async trainingPreparationsRetrieve(requestParameters: TrainingPreparationsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TrainingPreparation> {
        const response = await this.trainingPreparationsRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async trainingPreparationsRetryCreateRaw(requestParameters: TrainingPreparationsRetryCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TrainingPreparation>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling trainingPreparationsRetryCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ClerkBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/training-preparations/{id}/retry/`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TrainingPreparationFromJSON(jsonValue));
    }

    /**
     */
    async trainingPreparationsRetryCreate(requestParameters: TrainingPreparationsRetryCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TrainingPreparation> {
        const response = await this.trainingPreparationsRetryCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
