/* tslint:disable */
/* eslint-disable */
/**
 * Overbae API
 * Backend API for the Overclaw / Overmind platform.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BeginUploadRequest,
  InspectUploadRequest,
  UploadInspection,
  UploadReserved,
  UploadState,
} from '../models/index';
import {
    BeginUploadRequestFromJSON,
    BeginUploadRequestToJSON,
    InspectUploadRequestFromJSON,
    InspectUploadRequestToJSON,
    UploadInspectionFromJSON,
    UploadInspectionToJSON,
    UploadReservedFromJSON,
    UploadReservedToJSON,
    UploadStateFromJSON,
    UploadStateToJSON,
} from '../models/index';

export interface UploadsChunkUpdateRequest {
    id: string;
    offset?: number;
    body?: Blob;
}

export interface UploadsCreateRequest {
    beginUploadRequest: BeginUploadRequest;
}

export interface UploadsInspectCreateRequest {
    id: string;
    inspectUploadRequest: InspectUploadRequest;
}

export interface UploadsRetrieveRequest {
    id: string;
}

/**
 *
 */
export class UploadsApi extends runtime.BaseAPI {

    /**
     * Parsers must stay declared on the class: ``@action`` initkwargs only apply through the router, so an action-level parser silently reverts elsewhere.
     * Append one chunk at a byte offset
     */
    async uploadsChunkUpdateRaw(requestParameters: UploadsChunkUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UploadState>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling uploadsChunkUpdate().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/octet-stream';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ClerkBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/uploads/{id}/chunk/`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UploadStateFromJSON(jsonValue));
    }

    /**
     * Parsers must stay declared on the class: ``@action`` initkwargs only apply through the router, so an action-level parser silently reverts elsewhere.
     * Append one chunk at a byte offset
     */
    async uploadsChunkUpdate(requestParameters: UploadsChunkUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UploadState> {
        const response = await this.uploadsChunkUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Parsers must stay declared on the class: ``@action`` initkwargs only apply through the router, so an action-level parser silently reverts elsewhere.
     * Reserve a chunked upload
     */
    async uploadsCreateRaw(requestParameters: UploadsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UploadReserved>> {
        if (requestParameters['beginUploadRequest'] == null) {
            throw new runtime.RequiredError(
                'beginUploadRequest',
                'Required parameter "beginUploadRequest" was null or undefined when calling uploadsCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ClerkBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/uploads/`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BeginUploadRequestToJSON(requestParameters['beginUploadRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UploadReservedFromJSON(jsonValue));
    }

    /**
     * Parsers must stay declared on the class: ``@action`` initkwargs only apply through the router, so an action-level parser silently reverts elsewhere.
     * Reserve a chunked upload
     */
    async uploadsCreate(requestParameters: UploadsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UploadReserved> {
        const response = await this.uploadsCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Parsers must stay declared on the class: ``@action`` initkwargs only apply through the router, so an action-level parser silently reverts elsewhere.
     * Validate an uploaded file and count its rows
     */
    async uploadsInspectCreateRaw(requestParameters: UploadsInspectCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UploadInspection>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling uploadsInspectCreate().'
            );
        }

        if (requestParameters['inspectUploadRequest'] == null) {
            throw new runtime.RequiredError(
                'inspectUploadRequest',
                'Required parameter "inspectUploadRequest" was null or undefined when calling uploadsInspectCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ClerkBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/uploads/{id}/inspect/`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: InspectUploadRequestToJSON(requestParameters['inspectUploadRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UploadInspectionFromJSON(jsonValue));
    }

    /**
     * Parsers must stay declared on the class: ``@action`` initkwargs only apply through the router, so an action-level parser silently reverts elsewhere.
     * Validate an uploaded file and count its rows
     */
    async uploadsInspectCreate(requestParameters: UploadsInspectCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UploadInspection> {
        const response = await this.uploadsInspectCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Parsers must stay declared on the class: ``@action`` initkwargs only apply through the router, so an action-level parser silently reverts elsewhere.
     * Bytes stored so far — where a resuming client continues
     */
    async uploadsRetrieveRaw(requestParameters: UploadsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UploadState>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling uploadsRetrieve().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ClerkBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/uploads/{id}/`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UploadStateFromJSON(jsonValue));
    }

    /**
     * Parsers must stay declared on the class: ``@action`` initkwargs only apply through the router, so an action-level parser silently reverts elsewhere.
     * Bytes stored so far — where a resuming client continues
     */
    async uploadsRetrieve(requestParameters: UploadsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UploadState> {
        const response = await this.uploadsRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
