"""store trace_id as uuid nullable, no foreign key

Revision ID: 0004
Revises: 0003_add_raw_otlp_requests_table
Create Date: 2026-03-05 17:59:19.006502

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0004"
down_revision = "0003_add_raw_otlp_requests_table"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("spans", "trace_id", existing_type=sa.UUID(), nullable=True)
    op.drop_constraint(op.f("fk_spans_trace_id_traces"), "spans", type_="foreignkey")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        op.f("fk_spans_trace_id_traces"), "spans", "traces", ["trace_id"], ["trace_id"]
    )
    op.alter_column("spans", "trace_id", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###
