"""add status to prompt

Revision ID: 0007_add_status_to_prompt
Revises: 0006_add_backtest_metadata
Create Date: 2026-02-23 20:03:00.079949

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0007_add_status_to_prompt"
down_revision = "0006_add_backtest_metadata"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "prompts",
        sa.Column(
            "status",
            sa.String(20),
            nullable=False,
            server_default="active",
        ),
        if_not_exists=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("prompts", "status")
    # ### end Alembic commands ###
