/* tslint:disable */
/* eslint-disable */
/**
 * Overmind Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JobOut } from './JobOut';
import {
    JobOutFromJSON,
    JobOutFromJSONTyped,
    JobOutToJSON,
    JobOutToJSONTyped,
} from './JobOut';
import type { AgentAnalytics } from './AgentAnalytics';
import {
    AgentAnalyticsFromJSON,
    AgentAnalyticsFromJSONTyped,
    AgentAnalyticsToJSON,
    AgentAnalyticsToJSONTyped,
} from './AgentAnalytics';
import type { SuggestionOut } from './SuggestionOut';
import {
    SuggestionOutFromJSON,
    SuggestionOutFromJSONTyped,
    SuggestionOutToJSON,
    SuggestionOutToJSONTyped,
} from './SuggestionOut';

/**
 * 
 * @export
 * @interface AgentOut
 */
export interface AgentOut {
    /**
     * 
     * @type {string}
     * @memberof AgentOut
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof AgentOut
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof AgentOut
     */
    promptId: string;
    /**
     * 
     * @type {number}
     * @memberof AgentOut
     */
    version: number;
    /**
     * 
     * @type {AgentAnalytics}
     * @memberof AgentOut
     */
    analytics: AgentAnalytics;
    /**
     * 
     * @type {Array<SuggestionOut>}
     * @memberof AgentOut
     */
    suggestions?: Array<SuggestionOut>;
    /**
     * 
     * @type {Array<JobOut>}
     * @memberof AgentOut
     */
    jobs?: Array<JobOut>;
    /**
     * 
     * @type {boolean}
     * @memberof AgentOut
     */
    readyForReview?: boolean;
    /**
     * User-defined categorisation tags, e.g. ["HR", "financial"]
     * @type {Array<string>}
     * @memberof AgentOut
     */
    tags?: Array<string>;
}

/**
 * Check if a given object implements the AgentOut interface.
 */
export function instanceOfAgentOut(value: object): value is AgentOut {
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('promptId' in value) || value['promptId'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('analytics' in value) || value['analytics'] === undefined) return false;
    return true;
}

export function AgentOutFromJSON(json: any): AgentOut {
    return AgentOutFromJSONTyped(json, false);
}

export function AgentOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgentOut {
    if (json == null) {
        return json;
    }
    return {
        
        'slug': json['slug'],
        'name': json['name'],
        'promptId': json['prompt_id'],
        'version': json['version'],
        'analytics': AgentAnalyticsFromJSON(json['analytics']),
        'suggestions': json['suggestions'] == null ? undefined : ((json['suggestions'] as Array<any>).map(SuggestionOutFromJSON)),
        'jobs': json['jobs'] == null ? undefined : ((json['jobs'] as Array<any>).map(JobOutFromJSON)),
        'readyForReview': json['ready_for_review'] == null ? undefined : json['ready_for_review'],
        'tags': json['tags'] == null ? undefined : json['tags'],
    };
}

export function AgentOutToJSON(json: any): AgentOut {
    return AgentOutToJSONTyped(json, false);
}

export function AgentOutToJSONTyped(value?: AgentOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'slug': value['slug'],
        'name': value['name'],
        'prompt_id': value['promptId'],
        'version': value['version'],
        'analytics': AgentAnalyticsToJSON(value['analytics']),
        'suggestions': value['suggestions'] == null ? undefined : ((value['suggestions'] as Array<any>).map(SuggestionOutToJSON)),
        'jobs': value['jobs'] == null ? undefined : ((value['jobs'] as Array<any>).map(JobOutToJSON)),
        'ready_for_review': value['readyForReview'],
        'tags': value['tags'],
    };
}

