/* tslint:disable */
/* eslint-disable */
/**
 * Overmind Core
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CoreProjectModel
 */
export interface CoreProjectModel {
    /**
     * 
     * @type {string}
     * @memberof CoreProjectModel
     */
    projectId: string;
    /**
     * 
     * @type {string}
     * @memberof CoreProjectModel
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CoreProjectModel
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof CoreProjectModel
     */
    description?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof CoreProjectModel
     */
    isActive: boolean;
    /**
     * 
     * @type {Date}
     * @memberof CoreProjectModel
     */
    createdAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof CoreProjectModel
     */
    updatedAt?: Date | null;
}

/**
 * Check if a given object implements the CoreProjectModel interface.
 */
export function instanceOfCoreProjectModel(value: object): value is CoreProjectModel {
    if (!('projectId' in value) || value['projectId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('isActive' in value) || value['isActive'] === undefined) return false;
    return true;
}

export function CoreProjectModelFromJSON(json: any): CoreProjectModel {
    return CoreProjectModelFromJSONTyped(json, false);
}

export function CoreProjectModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoreProjectModel {
    if (json == null) {
        return json;
    }
    return {
        
        'projectId': json['project_id'],
        'name': json['name'],
        'slug': json['slug'],
        'description': json['description'] == null ? undefined : json['description'],
        'isActive': json['is_active'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
    };
}

export function CoreProjectModelToJSON(json: any): CoreProjectModel {
    return CoreProjectModelToJSONTyped(json, false);
}

export function CoreProjectModelToJSONTyped(value?: CoreProjectModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'project_id': value['projectId'],
        'name': value['name'],
        'slug': value['slug'],
        'description': value['description'],
        'is_active': value['isActive'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
    };
}

