/* tslint:disable */
/* eslint-disable */
/**
 * Overmind Core
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CoreUserModel
 */
export interface CoreUserModel {
    /**
     * 
     * @type {string}
     * @memberof CoreUserModel
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof CoreUserModel
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof CoreUserModel
     */
    fullName?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof CoreUserModel
     */
    isActive: boolean;
    /**
     * 
     * @type {Date}
     * @memberof CoreUserModel
     */
    createdAt?: Date | null;
}

/**
 * Check if a given object implements the CoreUserModel interface.
 */
export function instanceOfCoreUserModel(value: object): value is CoreUserModel {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('isActive' in value) || value['isActive'] === undefined) return false;
    return true;
}

export function CoreUserModelFromJSON(json: any): CoreUserModel {
    return CoreUserModelFromJSONTyped(json, false);
}

export function CoreUserModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoreUserModel {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['user_id'],
        'email': json['email'],
        'fullName': json['full_name'] == null ? undefined : json['full_name'],
        'isActive': json['is_active'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
    };
}

export function CoreUserModelToJSON(json: any): CoreUserModel {
    return CoreUserModelToJSONTyped(json, false);
}

export function CoreUserModelToJSONTyped(value?: CoreUserModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user_id': value['userId'],
        'email': value['email'],
        'full_name': value['fullName'],
        'is_active': value['isActive'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
    };
}

