/* tslint:disable */
/* eslint-disable */
/**
 * Overmind Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InvitationResponse
 */
export interface InvitationResponse {
    /**
     * 
     * @type {string}
     * @memberof InvitationResponse
     */
    invitationId: string;
    /**
     * 
     * @type {string}
     * @memberof InvitationResponse
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof InvitationResponse
     */
    organisationId: string;
    /**
     * 
     * @type {string}
     * @memberof InvitationResponse
     */
    organisationName: string;
    /**
     * 
     * @type {string}
     * @memberof InvitationResponse
     */
    inviterName: string;
    /**
     * 
     * @type {string}
     * @memberof InvitationResponse
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof InvitationResponse
     */
    message?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InvitationResponse
     */
    invitedName?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof InvitationResponse
     */
    expiresAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof InvitationResponse
     */
    createdAt: Date;
    /**
     * 
     * @type {Array<string>}
     * @memberof InvitationResponse
     */
    roles: Array<string>;
}

/**
 * Check if a given object implements the InvitationResponse interface.
 */
export function instanceOfInvitationResponse(value: object): value is InvitationResponse {
    if (!('invitationId' in value) || value['invitationId'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('organisationId' in value) || value['organisationId'] === undefined) return false;
    if (!('organisationName' in value) || value['organisationName'] === undefined) return false;
    if (!('inviterName' in value) || value['inviterName'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('expiresAt' in value) || value['expiresAt'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('roles' in value) || value['roles'] === undefined) return false;
    return true;
}

export function InvitationResponseFromJSON(json: any): InvitationResponse {
    return InvitationResponseFromJSONTyped(json, false);
}

export function InvitationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvitationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'invitationId': json['invitation_id'],
        'email': json['email'],
        'organisationId': json['organisation_id'],
        'organisationName': json['organisation_name'],
        'inviterName': json['inviter_name'],
        'status': json['status'],
        'message': json['message'] == null ? undefined : json['message'],
        'invitedName': json['invited_name'] == null ? undefined : json['invited_name'],
        'expiresAt': (new Date(json['expires_at'])),
        'createdAt': (new Date(json['created_at'])),
        'roles': json['roles'],
    };
}

export function InvitationResponseToJSON(json: any): InvitationResponse {
    return InvitationResponseToJSONTyped(json, false);
}

export function InvitationResponseToJSONTyped(value?: InvitationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'invitation_id': value['invitationId'],
        'email': value['email'],
        'organisation_id': value['organisationId'],
        'organisation_name': value['organisationName'],
        'inviter_name': value['inviterName'],
        'status': value['status'],
        'message': value['message'],
        'invited_name': value['invitedName'],
        'expires_at': value['expiresAt'].toISOString(),
        'created_at': value['createdAt'].toISOString(),
        'roles': value['roles'],
    };
}

