/* tslint:disable */
/* eslint-disable */
/**
 * Overmind Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Information about a supported model.
 * @export
 * @interface ModelInfo
 */
export interface ModelInfo {
    /**
     * 
     * @type {string}
     * @memberof ModelInfo
     */
    provider: string;
    /**
     * 
     * @type {string}
     * @memberof ModelInfo
     */
    modelName: string;
}

/**
 * Check if a given object implements the ModelInfo interface.
 */
export function instanceOfModelInfo(value: object): value is ModelInfo {
    if (!('provider' in value) || value['provider'] === undefined) return false;
    if (!('modelName' in value) || value['modelName'] === undefined) return false;
    return true;
}

export function ModelInfoFromJSON(json: any): ModelInfo {
    return ModelInfoFromJSONTyped(json, false);
}

export function ModelInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'provider': json['provider'],
        'modelName': json['model_name'],
    };
}

export function ModelInfoToJSON(json: any): ModelInfo {
    return ModelInfoToJSONTyped(json, false);
}

export function ModelInfoToJSONTyped(value?: ModelInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'provider': value['provider'],
        'model_name': value['modelName'],
    };
}

