/* tslint:disable */
/* eslint-disable */
/**
 * Overmind Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrganisationResponse
 */
export interface OrganisationResponse {
    /**
     * 
     * @type {string}
     * @memberof OrganisationResponse
     */
    organisationId: string;
    /**
     * 
     * @type {string}
     * @memberof OrganisationResponse
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof OrganisationResponse
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof OrganisationResponse
     */
    description?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof OrganisationResponse
     */
    isActive: boolean;
    /**
     * 
     * @type {Date}
     * @memberof OrganisationResponse
     */
    createdAt: Date;
    /**
     * 
     * @type {number}
     * @memberof OrganisationResponse
     */
    memberCount?: number | null;
    /**
     * 
     * @type {number}
     * @memberof OrganisationResponse
     */
    projectCount?: number | null;
}

/**
 * Check if a given object implements the OrganisationResponse interface.
 */
export function instanceOfOrganisationResponse(value: object): value is OrganisationResponse {
    if (!('organisationId' in value) || value['organisationId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('isActive' in value) || value['isActive'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function OrganisationResponseFromJSON(json: any): OrganisationResponse {
    return OrganisationResponseFromJSONTyped(json, false);
}

export function OrganisationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganisationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'organisationId': json['organisation_id'],
        'name': json['name'],
        'slug': json['slug'],
        'description': json['description'] == null ? undefined : json['description'],
        'isActive': json['is_active'],
        'createdAt': (new Date(json['created_at'])),
        'memberCount': json['member_count'] == null ? undefined : json['member_count'],
        'projectCount': json['project_count'] == null ? undefined : json['project_count'],
    };
}

export function OrganisationResponseToJSON(json: any): OrganisationResponse {
    return OrganisationResponseToJSONTyped(json, false);
}

export function OrganisationResponseToJSONTyped(value?: OrganisationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'organisation_id': value['organisationId'],
        'name': value['name'],
        'slug': value['slug'],
        'description': value['description'],
        'is_active': value['isActive'],
        'created_at': value['createdAt'].toISOString(),
        'member_count': value['memberCount'],
        'project_count': value['projectCount'],
    };
}

