/* tslint:disable */
/* eslint-disable */
/**
 * Overmind Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InvitationDetails } from './InvitationDetails';
import {
    InvitationDetailsFromJSON,
    InvitationDetailsFromJSONTyped,
    InvitationDetailsToJSON,
    InvitationDetailsToJSONTyped,
} from './InvitationDetails';

/**
 * 
 * @export
 * @interface SignUpResponse
 */
export interface SignUpResponse {
    /**
     * 
     * @type {string}
     * @memberof SignUpResponse
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof SignUpResponse
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof SignUpResponse
     */
    fullName: string;
    /**
     * 
     * @type {boolean}
     * @memberof SignUpResponse
     */
    hasInvitations: boolean;
    /**
     * 
     * @type {string}
     * @memberof SignUpResponse
     */
    redirectUrl?: string | null;
    /**
     * 
     * @type {Array<InvitationDetails>}
     * @memberof SignUpResponse
     */
    invitations?: Array<InvitationDetails> | null;
}

/**
 * Check if a given object implements the SignUpResponse interface.
 */
export function instanceOfSignUpResponse(value: object): value is SignUpResponse {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('fullName' in value) || value['fullName'] === undefined) return false;
    if (!('hasInvitations' in value) || value['hasInvitations'] === undefined) return false;
    return true;
}

export function SignUpResponseFromJSON(json: any): SignUpResponse {
    return SignUpResponseFromJSONTyped(json, false);
}

export function SignUpResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignUpResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['user_id'],
        'email': json['email'],
        'fullName': json['full_name'],
        'hasInvitations': json['has_invitations'],
        'redirectUrl': json['redirect_url'] == null ? undefined : json['redirect_url'],
        'invitations': json['invitations'] == null ? undefined : ((json['invitations'] as Array<any>).map(InvitationDetailsFromJSON)),
    };
}

export function SignUpResponseToJSON(json: any): SignUpResponse {
    return SignUpResponseToJSONTyped(json, false);
}

export function SignUpResponseToJSONTyped(value?: SignUpResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user_id': value['userId'],
        'email': value['email'],
        'full_name': value['fullName'],
        'has_invitations': value['hasInvitations'],
        'redirect_url': value['redirectUrl'],
        'invitations': value['invitations'] == null ? undefined : ((value['invitations'] as Array<any>).map(InvitationDetailsToJSON)),
    };
}

