/* tslint:disable */
/* eslint-disable */
/**
 * Overmind Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface SpanResponseModel
 */
export interface SpanResponseModel {
    [key: string]: any | any;
    /**
     *
     * @type {string}
     * @memberof SpanResponseModel
     */
    userId?: string | null;
    /**
     *
     * @type {string}
     * @memberof SpanResponseModel
     */
    projectId?: string | null;
    /**
     *
     * @type {string}
     * @memberof SpanResponseModel
     */
    businessId?: string | null;
    /**
     *
     * @type {string}
     * @memberof SpanResponseModel
     */
    traceId: string;
    /**
     *
     * @type {string}
     * @memberof SpanResponseModel
     */
    spanId: string;
    /**
     *
     * @type {string}
     * @memberof SpanResponseModel
     */
    parentSpanId?: string | null;
    /**
     *
     * @type {string}
     * @memberof SpanResponseModel
     */
    traceState?: string | null;
    /**
     *
     * @type {number}
     * @memberof SpanResponseModel
     */
    startTimeUnixNano: number;
    /**
     *
     * @type {number}
     * @memberof SpanResponseModel
     */
    endTimeUnixNano: number;
    /**
     *
     * @type {number}
     * @memberof SpanResponseModel
     */
    durationNano: number;
    /**
     *
     * @type {number}
     * @memberof SpanResponseModel
     */
    statusCode: number;
    /**
     *
     * @type {string}
     * @memberof SpanResponseModel
     */
    statusMessage?: string | null;
    /**
     *
     * @type {{ [key: string]: any; }}
     * @memberof SpanResponseModel
     */
    resourceAttributes?: { [key: string]: any; };
    /**
     *
     * @type {{ [key: string]: any; }}
     * @memberof SpanResponseModel
     */
    spanAttributes?: { [key: string]: any; };
    /**
     *
     * @type {}
     * @memberof SpanResponseModel
     */
    inputs?:  | null;
    /**
     *
     * @type {}
     * @memberof SpanResponseModel
     */
    outputs?:  | null;
    /**
     *
     * @type {string}
     * @memberof SpanResponseModel
     */
    policyOutcome?: string | null;
    /**
     *
     * @type {string}
     * @memberof SpanResponseModel
     */
    scopeName?: string | null;
    /**
     *
     * @type {string}
     * @memberof SpanResponseModel
     */
    name?: string | null;
    /**
     *
     * @type {string}
     * @memberof SpanResponseModel
     */
    scopeVersion?: string | null;
    /**
     *
     * @type {Array<any>}
     * @memberof SpanResponseModel
     */
    events?: Array<any>;
    /**
     *
     * @type {Array<any>}
     * @memberof SpanResponseModel
     */
    links?: Array<any>;
}

/**
 * Check if a given object implements the SpanResponseModel interface.
 */
export function instanceOfSpanResponseModel(value: object): value is SpanResponseModel {
    if (!('traceId' in value) || value['traceId'] === undefined) return false;
    if (!('spanId' in value) || value['spanId'] === undefined) return false;
    if (!('startTimeUnixNano' in value) || value['startTimeUnixNano'] === undefined) return false;
    if (!('endTimeUnixNano' in value) || value['endTimeUnixNano'] === undefined) return false;
    if (!('durationNano' in value) || value['durationNano'] === undefined) return false;
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    return true;
}

export function SpanResponseModelFromJSON(json: any): SpanResponseModel {
    return SpanResponseModelFromJSONTyped(json, false);
}

export function SpanResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpanResponseModel {
    if (json == null) {
        return json;
    }
    return {

            ...json,
        'userId': json['UserId'] == null ? undefined : json['UserId'],
        'projectId': json['ProjectId'] == null ? undefined : json['ProjectId'],
        'businessId': json['BusinessId'] == null ? undefined : json['BusinessId'],
        'traceId': json['TraceId'],
        'spanId': json['SpanId'],
        'parentSpanId': json['ParentSpanId'] == null ? undefined : json['ParentSpanId'],
        'traceState': json['TraceState'] == null ? undefined : json['TraceState'],
        'startTimeUnixNano': json['StartTimeUnixNano'],
        'endTimeUnixNano': json['EndTimeUnixNano'],
        'durationNano': json['DurationNano'],
        'statusCode': json['StatusCode'],
        'statusMessage': json['StatusMessage'] == null ? undefined : json['StatusMessage'],
        'resourceAttributes': json['ResourceAttributes'] == null ? undefined : json['ResourceAttributes'],
        'spanAttributes': json['SpanAttributes'] == null ? undefined : json['SpanAttributes'],
        'inputs': json['Inputs'] == null ? undefined : (json['Inputs']),
        'outputs': json['Outputs'] == null ? undefined : (json['Outputs']),
        'policyOutcome': json['PolicyOutcome'] == null ? undefined : json['PolicyOutcome'],
        'scopeName': json['ScopeName'] == null ? undefined : json['ScopeName'],
        'name': json['Name'] == null ? undefined : json['Name'],
        'scopeVersion': json['ScopeVersion'] == null ? undefined : json['ScopeVersion'],
        'events': json['Events'] == null ? undefined : json['Events'],
        'links': json['Links'] == null ? undefined : json['Links'],
    };
}

export function SpanResponseModelToJSON(json: any): SpanResponseModel {
    return SpanResponseModelToJSONTyped(json, false);
}

export function SpanResponseModelToJSONTyped(value?: SpanResponseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

            ...value,
        'UserId': value['userId'],
        'ProjectId': value['projectId'],
        'BusinessId': value['businessId'],
        'TraceId': value['traceId'],
        'SpanId': value['spanId'],
        'ParentSpanId': value['parentSpanId'],
        'TraceState': value['traceState'],
        'StartTimeUnixNano': value['startTimeUnixNano'],
        'EndTimeUnixNano': value['endTimeUnixNano'],
        'DurationNano': value['durationNano'],
        'StatusCode': value['statusCode'],
        'StatusMessage': value['statusMessage'],
        'ResourceAttributes': value['resourceAttributes'],
        'SpanAttributes': value['spanAttributes'],
        'Inputs': ToJSON(value['inputs']),
        'Outputs': ToJSON(value['outputs']),
        'PolicyOutcome': value['policyOutcome'],
        'ScopeName': value['scopeName'],
        'Name': value['name'],
        'ScopeVersion': value['scopeVersion'],
        'Events': value['events'],
        'Links': value['links'],
    };
}

