/* tslint:disable */
/* eslint-disable */
/**
 * Overmind Core
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateAgentMetadataRequest
 */
export interface UpdateAgentMetadataRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateAgentMetadataRequest
     */
    name?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdateAgentMetadataRequest
     */
    tags?: Array<string> | null;
}

/**
 * Check if a given object implements the UpdateAgentMetadataRequest interface.
 */
export function instanceOfUpdateAgentMetadataRequest(value: object): value is UpdateAgentMetadataRequest {
    return true;
}

export function UpdateAgentMetadataRequestFromJSON(json: any): UpdateAgentMetadataRequest {
    return UpdateAgentMetadataRequestFromJSONTyped(json, false);
}

export function UpdateAgentMetadataRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateAgentMetadataRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'tags': json['tags'] == null ? undefined : json['tags'],
    };
}

export function UpdateAgentMetadataRequestToJSON(json: any): UpdateAgentMetadataRequest {
    return UpdateAgentMetadataRequestToJSONTyped(json, false);
}

export function UpdateAgentMetadataRequestToJSONTyped(value?: UpdateAgentMetadataRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'tags': value['tags'],
    };
}

