/* tslint:disable */
/* eslint-disable */
/**
 * Overmind Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateCriteriaRequest
 */
export interface UpdateCriteriaRequest {
    /**
     * 
     * @type {{ [key: string]: Array<string>; }}
     * @memberof UpdateCriteriaRequest
     */
    evaluationCriteria: { [key: string]: Array<string>; };
    /**
     * 
     * @type {boolean}
     * @memberof UpdateCriteriaRequest
     */
    reEvaluate?: boolean;
}

/**
 * Check if a given object implements the UpdateCriteriaRequest interface.
 */
export function instanceOfUpdateCriteriaRequest(value: object): value is UpdateCriteriaRequest {
    if (!('evaluationCriteria' in value) || value['evaluationCriteria'] === undefined) return false;
    return true;
}

export function UpdateCriteriaRequestFromJSON(json: any): UpdateCriteriaRequest {
    return UpdateCriteriaRequestFromJSONTyped(json, false);
}

export function UpdateCriteriaRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateCriteriaRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'evaluationCriteria': json['evaluation_criteria'],
        'reEvaluate': json['re_evaluate'] == null ? undefined : json['re_evaluate'],
    };
}

export function UpdateCriteriaRequestToJSON(json: any): UpdateCriteriaRequest {
    return UpdateCriteriaRequestToJSONTyped(json, false);
}

export function UpdateCriteriaRequestToJSONTyped(value?: UpdateCriteriaRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'evaluation_criteria': value['evaluationCriteria'],
        're_evaluate': value['reEvaluate'],
    };
}

