/* tslint:disable */
/* eslint-disable */
/**
 * Overmind Core
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateAgentMetadataResponse
 */
export interface UpdateAgentMetadataResponse {
    /**
     * 
     * @type {string}
     * @memberof UpdateAgentMetadataResponse
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateAgentMetadataResponse
     */
    name: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdateAgentMetadataResponse
     */
    tags: Array<string>;
}

/**
 * Check if a given object implements the UpdateAgentMetadataResponse interface.
 */
export function instanceOfUpdateAgentMetadataResponse(value: object): value is UpdateAgentMetadataResponse {
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('tags' in value) || value['tags'] === undefined) return false;
    return true;
}

export function UpdateAgentMetadataResponseFromJSON(json: any): UpdateAgentMetadataResponse {
    return UpdateAgentMetadataResponseFromJSONTyped(json, false);
}

export function UpdateAgentMetadataResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateAgentMetadataResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'slug': json['slug'],
        'name': json['name'],
        'tags': json['tags'],
    };
}

export function UpdateAgentMetadataResponseToJSON(json: any): UpdateAgentMetadataResponse {
    return UpdateAgentMetadataResponseToJSONTyped(json, false);
}

export function UpdateAgentMetadataResponseToJSONTyped(value?: UpdateAgentMetadataResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'slug': value['slug'],
        'name': value['name'],
        'tags': value['tags'],
    };
}

