/* tslint:disable */
/* eslint-disable */
/**
 * Overmind Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserResponse } from './UserResponse';
import {
    UserResponseFromJSON,
    UserResponseFromJSONTyped,
    UserResponseToJSON,
    UserResponseToJSONTyped,
} from './UserResponse';

/**
 * 
 * @export
 * @interface UserListResponse
 */
export interface UserListResponse {
    /**
     * 
     * @type {Array<UserResponse>}
     * @memberof UserListResponse
     */
    users: Array<UserResponse>;
    /**
     * 
     * @type {number}
     * @memberof UserListResponse
     */
    totalCount: number;
}

/**
 * Check if a given object implements the UserListResponse interface.
 */
export function instanceOfUserListResponse(value: object): value is UserListResponse {
    if (!('users' in value) || value['users'] === undefined) return false;
    if (!('totalCount' in value) || value['totalCount'] === undefined) return false;
    return true;
}

export function UserListResponseFromJSON(json: any): UserListResponse {
    return UserListResponseFromJSONTyped(json, false);
}

export function UserListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'users': ((json['users'] as Array<any>).map(UserResponseFromJSON)),
        'totalCount': json['total_count'],
    };
}

export function UserListResponseToJSON(json: any): UserListResponse {
    return UserListResponseToJSONTyped(json, false);
}

export function UserListResponseToJSONTyped(value?: UserListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'users': ((value['users'] as Array<any>).map(UserResponseToJSON)),
        'total_count': value['totalCount'],
    };
}

