/* tslint:disable */
/* eslint-disable */
/**
 * Overmind Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserResponse
 */
export interface UserResponse {
    /**
     * 
     * @type {string}
     * @memberof UserResponse
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof UserResponse
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UserResponse
     */
    fullName?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof UserResponse
     */
    isActive: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UserResponse
     */
    isVerified: boolean;
    /**
     * 
     * @type {Date}
     * @memberof UserResponse
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof UserResponse
     */
    lastLogin?: Date | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof UserResponse
     */
    roles?: Array<string> | null;
}

/**
 * Check if a given object implements the UserResponse interface.
 */
export function instanceOfUserResponse(value: object): value is UserResponse {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('isActive' in value) || value['isActive'] === undefined) return false;
    if (!('isVerified' in value) || value['isVerified'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function UserResponseFromJSON(json: any): UserResponse {
    return UserResponseFromJSONTyped(json, false);
}

export function UserResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['user_id'],
        'email': json['email'],
        'fullName': json['full_name'] == null ? undefined : json['full_name'],
        'isActive': json['is_active'],
        'isVerified': json['is_verified'],
        'createdAt': (new Date(json['created_at'])),
        'lastLogin': json['last_login'] == null ? undefined : (new Date(json['last_login'])),
        'roles': json['roles'] == null ? undefined : json['roles'],
    };
}

export function UserResponseToJSON(json: any): UserResponse {
    return UserResponseToJSONTyped(json, false);
}

export function UserResponseToJSONTyped(value?: UserResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user_id': value['userId'],
        'email': value['email'],
        'full_name': value['fullName'],
        'is_active': value['isActive'],
        'is_verified': value['isVerified'],
        'created_at': value['createdAt'].toISOString(),
        'last_login': value['lastLogin'] == null ? value['lastLogin'] : value['lastLogin'].toISOString(),
        'roles': value['roles'],
    };
}

