/* tslint:disable */
/* eslint-disable */
/**
 * Overmind Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserOnboardingRequest
 */
export interface UserOnboardingRequest {
    /**
     * 
     * @type {Array<string>}
     * @memberof UserOnboardingRequest
     */
    priorities: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof UserOnboardingRequest
     */
    description?: string | null;
}

/**
 * Check if a given object implements the UserOnboardingRequest interface.
 */
export function instanceOfUserOnboardingRequest(value: object): value is UserOnboardingRequest {
    if (!('priorities' in value) || value['priorities'] === undefined) return false;
    return true;
}

export function UserOnboardingRequestFromJSON(json: any): UserOnboardingRequest {
    return UserOnboardingRequestFromJSONTyped(json, false);
}

export function UserOnboardingRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserOnboardingRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'priorities': json['priorities'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function UserOnboardingRequestToJSON(json: any): UserOnboardingRequest {
    return UserOnboardingRequestToJSONTyped(json, false);
}

export function UserOnboardingRequestToJSONTyped(value?: UserOnboardingRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'priorities': value['priorities'],
        'description': value['description'],
    };
}

