# Generated by Django 6.0.7 on 2026-09-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("overbae", "0002_workshop_engines"),
    ]

    operations = [
        migrations.AlterField(
            model_name="finetuningjobeval",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                    ("skipped", "Skipped"),
                    ("unavailable", "Unavailable"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
