# Generated by Django 6.0.7 on 2026-09-21 16:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


def retire_janitor(apps, schema_editor):
    periodic_task = apps.get_model("django_celery_beat", "PeriodicTask")
    periodic_task.objects.using(schema_editor.connection.alias).filter(
        task="overbae.tasks.inference_controller.janitor_stuck_fsm",
    ).update(enabled=False)


def pin_existing_evaluations(apps, schema_editor):
    Job = apps.get_model("overbae", "FinetuningJob")
    JobEval = apps.get_model("overbae", "FinetuningJobEval")
    Cell = apps.get_model("overbae", "Cell")
    alias = schema_editor.connection.alias
    for job in (
        Job.objects.using(alias)
        .filter(eval_cell__isnull=True)
        .select_related("eval_dataset")
        .iterator()
    ):
        cell_id = (
            JobEval.objects.using(alias)
            .filter(job_id=job.pk, eval_run__cell__isnull=False)
            .order_by("created_at")
            .values_list("eval_run__cell_id", flat=True)
            .first()
        )
        if cell_id is None and job.eval_dataset_id:
            cell_id = job.eval_dataset.active_id or (
                Cell.objects.using(alias)
                .filter(dataset_id=job.eval_dataset_id, state="ok")
                .exclude(fingerprint="")
                .order_by("-position")
                .values_list("pk", flat=True)
                .first()
            )
        if cell_id is not None:
            Job.objects.using(alias).filter(pk=job.pk).update(eval_cell_id=cell_id)


class Migration(migrations.Migration):
    replaces = [
        ("overbae", "0005_optional_eval_set_capability"),
        ("overbae", "0006_training_evaluation_schedule"),
        ("overbae", "0007_resumable_deployments"),
        ("overbae", "0008_retire_deployment_janitor"),
        ("overbae", "0009_dataset_reviews"),
        ("overbae", "0010_training_preparation"),
        ("overbae", "0011_pin_training_eval_version"),
        ("overbae", "0012_matched_training_baseline"),
        ("overbae", "0013_capability_benchmark_model"),
    ]

    dependencies = [
        ("django_celery_beat", "0001_initial"),
        ("overbae", "0004_finetuningjob_eval_cell"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evalset",
            name="capability",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="eval_sets",
                to="overbae.capability",
            ),
        ),
        migrations.AddConstraint(
            model_name="evalset",
            constraint=models.UniqueConstraint(
                condition=models.Q(("capability__isnull", True)),
                fields=("project", "name"),
                name="uniq_project_eval_set_name_unbound",
            ),
        ),
        migrations.AddField(
            model_name="finetuningjob",
            name="eval_incumbent_after",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="finetuningjob",
            name="eval_incumbent_before",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="finetuningjob",
            name="eval_model_after",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="finetuningjob",
            name="eval_model_before",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="finetuningjobeval",
            name="kind",
            field=models.CharField(
                choices=[
                    ("baseline", "Baseline"),
                    ("incumbent_after", "Incumbent After"),
                    ("model_before", "Model Before"),
                    ("checkpoint", "Checkpoint"),
                    ("final", "Final"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="finetuningjobeval",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind__in", ["incumbent_after", "model_before"])),
                fields=("job", "kind"),
                name="uniq_ft_job_eval_optional",
            ),
        ),
        migrations.AddField(
            model_name="deployedmodel",
            name="deployment_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="deployedmodel",
            name="deployment_call_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="deployedmodel",
            name="deployment_cancel_pending",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="deployedmodel",
            name="deployment_claim",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deployedmodel",
            name="deployment_claim_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deployedmodel",
            name="deployment_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deployedmodel",
            name="deployment_dispatching",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="deployedmodel",
            name="deployment_generation",
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name="deployedmodel",
            name="deployment_next_poll_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="deployedmodel",
            name="deployment_notify",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="deployedmodel",
            name="deployment_stage",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="deployedmodel",
            name="deployment_waiters",
            field=models.ManyToManyField(
                blank=True, related_name="evaluation_deployments", to="overbae.finetuningjob"
            ),
        ),
        migrations.RunPython(
            code=retire_janitor,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name="cell",
            name="review",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="cell",
            name="quality_report",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="TrainingPreparation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("signature", models.CharField(max_length=64, unique=True)),
                ("config", models.JSONField(default=dict)),
                ("state", models.CharField(default="queued", max_length=16)),
                ("remote_id", models.CharField(blank=True, default="", max_length=255)),
                ("report", models.JSONField(default=dict)),
                ("error", models.TextField(blank=True, default="")),
                ("deadline", models.DateTimeField()),
                ("touched_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cell",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_preparations",
                        to="overbae.cell",
                    ),
                ),
                (
                    "validation_cell",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation_preparations",
                        to="overbae.cell",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="finetuningjob",
            name="eval_cell",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="evaluation_finetuning_jobs",
                to="overbae.cell",
            ),
        ),
        migrations.RunPython(
            code=pin_existing_evaluations,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="finetuningjob",
            name="eval_incumbent_before",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="finetuningjob",
            name="eval_model_before",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="capability",
            name="benchmark_model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="overbae.deployedmodel",
            ),
        ),
    ]
