# Generated by Django 6.0.7 on 2026-09-18 00:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overbae', '0006_training_evaluation_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployedmodel',
            name='deployment_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deployedmodel',
            name='deployment_call_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='deployedmodel',
            name='deployment_cancel_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deployedmodel',
            name='deployment_claim',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deployedmodel',
            name='deployment_claim_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deployedmodel',
            name='deployment_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deployedmodel',
            name='deployment_dispatching',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deployedmodel',
            name='deployment_generation',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='deployedmodel',
            name='deployment_next_poll_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='deployedmodel',
            name='deployment_notify',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deployedmodel',
            name='deployment_stage',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='deployedmodel',
            name='deployment_waiters',
            field=models.ManyToManyField(blank=True, related_name='evaluation_deployments', to='overbae.finetuningjob'),
        ),
    ]
