# Generated by Django 6.0.7 on 2026-09-28 03:37

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("overbae", "0007_evalrun_judge_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="capability",
            name="active_model_activated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="capability",
            name="first_application_request_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="capability",
            name="last_application_request_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="capability",
            name="previous_active_model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="overbae.deployedmodel",
            ),
        ),
        migrations.AddField(
            model_name="inferencecall",
            name="end_to_end_ms",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inferencecall",
            name="error_code",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="inferencecall",
            name="outcome",
            field=models.CharField(default="succeeded", max_length=16),
        ),
        migrations.AddField(
            model_name="inferencecall",
            name="requested_model",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="inferencecall",
            name="source",
            field=models.CharField(default="unknown", max_length=16),
        ),
        migrations.CreateModel(
            name="ModelActivation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("generation", models.UUIDField(default=uuid.uuid4)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("checking", "Checking deployment"),
                            ("verifying", "Waking and verifying inference"),
                            ("switching", "Switching routing"),
                            ("complete", "Live"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="checking",
                        max_length=16,
                    ),
                ),
                ("failed_stage", models.CharField(blank=True, max_length=16)),
                ("error", models.TextField(blank=True)),
                ("call_id", models.CharField(blank=True, max_length=100)),
                ("dispatching", models.BooleanField(default=False)),
                ("claim", models.UUIDField(null=True)),
                ("claim_until", models.DateTimeField(null=True)),
                ("next_poll_at", models.DateTimeField(db_index=True)),
                ("started_at", models.DateTimeField()),
                ("deadline", models.DateTimeField()),
                ("completed_at", models.DateTimeField(null=True)),
                (
                    "capability",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activation",
                        to="overbae.capability",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activations",
                        to="overbae.deployedmodel",
                    ),
                ),
            ],
        ),
    ]
