# Generated by Django 6.0.7 on 2026-09-30 06:03

import django.db.models.deletion
import uuid
import hashlib
import json
from itertools import groupby
from django.conf import settings
from django.db import migrations, models


# Frozen grouping rules preserve existing spans and capability choices during upgrade.
def value_shape(value, depth=0):
    if isinstance(value, str):
        try:
            value = json.loads(value)
        except (ValueError, TypeError):
            return "text"
    if depth >= 4:
        return type(value).__name__
    if isinstance(value, dict):
        return {str(k): value_shape(v, depth + 1) for k, v in sorted(value.items())}
    if isinstance(value, list):
        return sorted({json.dumps(value_shape(v, depth + 1), sort_keys=True) for v in value})
    return type(value).__name__


def trace_signature(spans):
    by_id = {s.span_id: s for s in spans}
    roots = [s for s in spans if s.parent_span_id is None]
    root = min(roots or spans, key=lambda s: (s.start_time_ns, s.span_id))
    paths, templates = [], set()
    for span in spans:
        parent = by_id.get(span.parent_span_id)
        attrs = span.attributes or {}
        paths.append(
            (
                span.name,
                span.span_type,
                parent.name if parent else "",
                value_shape(attrs.get("overmind.input.data")),
                value_shape(attrs.get("overmind.output.data")),
            )
        )
        payload = attrs.get("overmind.input.data")
        if isinstance(payload, str):
            try:
                payload = json.loads(payload)
            except ValueError:
                payload = None
        messages = payload.get("messages", []) if isinstance(payload, dict) else payload
        if isinstance(messages, list):
            for message in messages:
                if isinstance(message, dict) and message.get("role") in {"system", "developer"}:
                    templates.add(
                        hashlib.sha256(
                            json.dumps(message.get("content"), sort_keys=True).encode()
                        ).hexdigest()
                    )
        for key, value in attrs.items():
            if key.endswith(("prompt_id", "prompt_name", "prompt_version")):
                templates.add(f"{key}:{value}")
    tools = sorted({s.name for s in spans if s.span_type == "tool_call"})
    payload = {
        "paths": sorted(paths, key=lambda p: json.dumps(p, sort_keys=True)),
        "templates": sorted(templates),
    }
    incomplete = not roots or any(s.parent_span_id and s.parent_span_id not in by_id for s in spans)
    # Generic, uninstrumented calls provide no shared task identity.
    if incomplete or (
        not tools
        and not templates
        and root.name.lower() in {"run", "root", "agent", "span", "generation", "chat", "llm"}
    ):
        payload["trace"] = root.trace_id
    fingerprint = hashlib.sha256(json.dumps(payload, sort_keys=True).encode()).hexdigest()
    return (
        fingerprint,
        root.name or "Unnamed trace",
        {
            "tools": tools,
            "span_count": len(spans),
            "root_count": len(roots),
            "input_shape": value_shape((root.attributes or {}).get("overmind.input.data")),
            "output_shape": value_shape((root.attributes or {}).get("overmind.output.data")),
            "incomplete": incomplete,
            "agent_steps": sum(
                any(
                    k.endswith(".observation_type") and str(v).upper() == "AGENT"
                    for k, v in (s.attributes or {}).items()
                )
                for s in spans
            ),
        },
    )


def group_existing_spans(apps, schema_editor):
    Span = apps.get_model("overbae", "Span")
    Credential = apps.get_model("overbae", "ConnectorCredential")
    Group = apps.get_model("overbae", "ConnectorTraceGroup")
    credentials = set(str(pk) for pk in Credential.objects.values_list("pk", flat=True))
    spans = Span.objects.filter(resource_attrs__has_key="connector.credential_id").order_by(
        "project_id", "trace_id"
    )
    for (project_id, trace_id), rows in groupby(
        spans.iterator(chunk_size=1000), key=lambda row: (row.project_id, row.trace_id)
    ):
        members = list(rows)
        credential_id = str(members[0].resource_attrs.get("connector.credential_id", ""))
        if credential_id not in credentials:
            continue
        fingerprint, name, evidence = trace_signature(members)
        group, _ = Group.objects.get_or_create(
            credential_id=credential_id,
            project_id=project_id,
            fingerprint=fingerprint,
            defaults={"name": name, "evidence": evidence},
        )
        Span.objects.filter(project_id=project_id, trace_id=trace_id).update(connector_group=group)


class Migration(migrations.Migration):
    dependencies = [
        ("overbae", "0008_model_activation"),
    ]

    operations = [
        migrations.AddField(
            model_name="span",
            name="connector_reviewed",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="ConnectorImportPreview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("source_project_id", models.CharField(blank=True, default="", max_length=128)),
                ("window_from", models.DateTimeField(blank=True, null=True)),
                ("window_to", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                            ("imported", "Imported"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("trace_count", models.PositiveIntegerField(default=0)),
                ("span_count", models.PositiveIntegerField(default=0)),
                ("estimated_seconds_min", models.PositiveIntegerField(default=0)),
                ("estimated_seconds_max", models.PositiveIntegerField(default=0)),
                ("error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "credential",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="previews",
                        to="overbae.connectorcredential",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConnectorTraceGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("fingerprint", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=255)),
                ("evidence", models.JSONField(default=dict)),
                ("revision", models.PositiveIntegerField(default=1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "credential",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trace_groups",
                        to="overbae.connectorcredential",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connector_trace_groups",
                        to="overbae.project",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="ConnectorGroupReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("capability_id_snapshot", models.UUIDField(blank=True, null=True)),
                ("capability_name", models.CharField(blank=True, default="", max_length=255)),
                ("revision", models.PositiveIntegerField()),
                ("trace_count", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="overbae.connectortracegroup",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="span",
            name="connector_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="spans",
                to="overbae.connectortracegroup",
            ),
        ),
        migrations.AddConstraint(
            model_name="connectortracegroup",
            constraint=models.UniqueConstraint(
                fields=("credential", "project", "fingerprint"),
                name="connector_group_fingerprint_unique",
            ),
        ),
        migrations.RunPython(group_existing_spans, migrations.RunPython.noop),
    ]
