# Generated by Django 6.0.7 on 2026-09-30 00:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overbae', '0008_model_activation'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCPOAuthClient',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('metadata', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MCPOAuthGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_hash', models.CharField(max_length=64, unique=True)),
                ('parameters', models.JSONField()),
                ('scopes', models.JSONField(default=list)),
                ('expires_at', models.DateTimeField()),
                ('decided_at', models.DateTimeField(null=True)),
                ('code_hash', models.CharField(max_length=64, null=True, unique=True)),
                ('code_used_at', models.DateTimeField(null=True)),
                ('revoked_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overbae.mcpoauthclient')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MCPOAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_hash', models.CharField(max_length=64, unique=True)),
                ('refresh_hash', models.CharField(max_length=64, unique=True)),
                ('scopes', models.JSONField(default=list)),
                ('access_expires_at', models.DateTimeField()),
                ('refresh_expires_at', models.DateTimeField()),
                ('rotated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overbae.mcpoauthgrant')),
            ],
        ),
    ]
