# Generated by Django 6.0.7 on 2026-09-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overbae', '0008_model_activation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='capability',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='capability',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'deleted'), _negated=True), fields=('project', 'slug'), name='capability_live_slug_unique'),
        ),
    ]
