# Generated by Django 6.0.7 on 2026-09-18 06:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("overbae", "0009_dataset_reviews"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingPreparation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("signature", models.CharField(max_length=64, unique=True)),
                ("config", models.JSONField(default=dict)),
                ("state", models.CharField(default="queued", max_length=16)),
                ("remote_id", models.CharField(blank=True, default="", max_length=255)),
                ("report", models.JSONField(default=dict)),
                ("error", models.TextField(blank=True, default="")),
                ("deadline", models.DateTimeField()),
                ("touched_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cell",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_preparations",
                        to="overbae.cell",
                    ),
                ),
                (
                    "validation_cell",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation_preparations",
                        to="overbae.cell",
                    ),
                ),
            ],
        ),
    ]
