# Generated by Django 6.0.7 on 2026-09-30 06:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("overbae", "0009_span_connector_reviewed_connectorimportpreview_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="connectorcredential",
            name="sync_lease_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="connectorimportpreview",
            name="credential_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
