# Generated by Django 6.0.8 on 2026-10-03 05:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("overbae", "0013_dataset_preparation_plans"),
    ]

    operations = [
        migrations.AddField(
            model_name="finetuningjob",
            name="accepted_findings",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="finetuningjob",
            name="request_key",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="finetuningjob",
            name="requested_configuration",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddConstraint(
            model_name="finetuningjob",
            constraint=models.UniqueConstraint(
                fields=("project", "request_key"), name="finetune_project_request_unique"
            ),
        ),
    ]
