# Generated by Django 6.0.8 on 2026-10-03 06:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overbae', '0017_training_provider_receipts'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatGPTInstallation',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('host_id', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
        migrations.AddField(
            model_name='dataset',
            name='brief',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='intent',
            field=models.CharField(choices=[('train', 'Train'), ('eval', 'Eval'), ('explore', 'Explore'), ('pending', 'Pending')], default='pending', max_length=8),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='source_kind',
            field=models.CharField(choices=[('pending', 'Pending'), ('file', 'File'), ('traces', 'Traces'), ('llm_calls', 'Llm Calls')], default='file', max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='sign_on_method',
            field=models.CharField(choices=[('password', 'Password'), ('chatgpt', 'ChatGPT'), ('google', 'Google'), ('saml', 'Saml')], default='password', max_length=20),
        ),
        migrations.CreateModel(
            name='ChatGPTAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_id', models.CharField(max_length=255, unique=True)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('credentials', models.TextField(blank=True)),
                ('scopes', models.JSONField(default=list)),
                ('expires_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatGPTAuthorization',
            fields=[
                ('state_hash', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('client_id', models.CharField(blank=True, max_length=255)),
                ('retried', models.BooleanField(default=False)),
                ('browser_hash', models.CharField(max_length=64)),
                ('nonce', models.CharField(max_length=128)),
                ('verifier', models.TextField()),
                ('redirect_uri', models.URLField()),
                ('expires_at', models.DateTimeField()),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='overbae.chatgptaccount')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatGPTLoginTicket',
            fields=[
                ('connection', models.TextField(blank=True)),
                ('password_attempts', models.PositiveSmallIntegerField(default=0)),
                ('browser_hash', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkshopPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funding_source', models.CharField(choices=[('platform', 'Platform'), ('chatgpt', 'ChatGPT')], default='platform', max_length=16)),
                ('model', models.CharField(blank=True, max_length=255)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='overbae.chatgptaccount')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
