# Generated by Django 6.0.8 on 2026-10-04 06:57

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def bind_existing_plans(apps, schema_editor):
    plan_model = apps.get_model("overbae", "NativeEvaluationPlan")
    for plan in plan_model.objects.select_related("job").iterator():
        job = plan.job
        config = dict(plan.config)
        config.update(
            participants=[
                {
                    "key": "base",
                    "name": "Unchanged base",
                    "kind": "foundation",
                    "job": str(job.pk),
                    "model": job.base_model,
                },
                {
                    "key": "candidate",
                    "name": "Trained model",
                    "kind": "trained",
                    "job": str(job.pk),
                    "model": job.base_model,
                },
            ],
            baseline="base",
            inference={
                "context_length": 8192,
                "batch_size": 64,
                "padded_tokens": 32768,
                "concurrency": 8,
            },
            logarithm_floor=None,
        )
        plan_model.objects.filter(pk=plan.pk).update(
            project_id=job.project_id,
            triggered_by_id=job.triggered_by_id,
            name=job.name or "Decision comparison",
            config=config,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("overbae", "0018_workshop_sources_and_funding"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataPartitionMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("role", models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name="DataPartitionPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("request_key", models.CharField(max_length=128)),
                ("source_fingerprint", models.CharField(max_length=64)),
                ("recipe", models.JSONField(default=dict)),
                ("report", models.JSONField(default=dict)),
                ("state", models.CharField(db_index=True, default="queued", max_length=16)),
                ("error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="DecisionProviderRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("participant", models.CharField(max_length=64)),
                ("role", models.CharField(max_length=16)),
                ("input_sha256", models.CharField(max_length=64)),
                ("state", models.CharField(db_index=True, default="pending", max_length=24)),
                ("attempts", models.JSONField(default=list)),
                ("response", models.JSONField(blank=True, null=True)),
                ("prediction", models.JSONField(blank=True, null=True)),
                ("diagnostics", models.JSONField(default=dict)),
                ("usage", models.JSONField(default=dict)),
                ("error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="TrainingExperiment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("purpose", models.TextField()),
                ("request_key", models.CharField(max_length=128)),
                ("variants", models.JSONField(default=list)),
                ("protocol", models.JSONField(default=dict)),
                ("state", models.CharField(default="draft", max_length=24)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="nativeevaluationplan",
            name="name",
            field=models.CharField(default="Decision comparison", max_length=255),
        ),
        migrations.AddField(
            model_name="nativeevaluationplan",
            name="project",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="overbae.project"
            ),
        ),
        migrations.AddField(
            model_name="nativeevaluationplan",
            name="request_key",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="nativeevaluationplan",
            name="triggered_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="native_evaluations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="billingtelemetry",
            name="service",
            field=models.CharField(
                choices=[
                    ("free-credits", "Free credits"),
                    ("stripe-topup", "Stripe top-up"),
                    ("finetuning-job", "Finetuning job"),
                    ("inference", "Inference"),
                    ("inference-ft-model", "Fine-tuned inference"),
                    ("data-workshop", "Data workshop"),
                    ("evaluation", "Evaluation"),
                    ("cursor-agent", "Cursor agent"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="nativeevaluationplan",
            name="calibration_cell",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="native_calibration_plans",
                to="overbae.cell",
            ),
        ),
        migrations.AlterField(
            model_name="nativeevaluationplan",
            name="job",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="native_evaluation",
                to="overbae.finetuningjob",
            ),
        ),
        migrations.AddConstraint(
            model_name="nativeevaluationplan",
            constraint=models.UniqueConstraint(
                fields=("project", "request_key"), name="unique_native_evaluation_request"
            ),
        ),
        migrations.AddField(
            model_name="datapartitionmember",
            name="cell",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="partition_memberships",
                to="overbae.cell",
            ),
        ),
        migrations.AddField(
            model_name="datapartitionplan",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="overbae.project"
            ),
        ),
        migrations.AddField(
            model_name="datapartitionplan",
            name="source_cell",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="partition_plans",
                to="overbae.cell",
            ),
        ),
        migrations.AddField(
            model_name="datapartitionmember",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="overbae.datapartitionplan",
            ),
        ),
        migrations.AddField(
            model_name="decisionproviderrequest",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requests",
                to="overbae.nativeevaluationplan",
            ),
        ),
        migrations.AddField(
            model_name="trainingexperiment",
            name="evaluation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="overbae.nativeevaluationplan",
            ),
        ),
        migrations.AddField(
            model_name="trainingexperiment",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="overbae.project"
            ),
        ),
        migrations.AddConstraint(
            model_name="datapartitionplan",
            constraint=models.UniqueConstraint(
                fields=("project", "request_key"), name="unique_partition_request"
            ),
        ),
        migrations.AddConstraint(
            model_name="datapartitionmember",
            constraint=models.UniqueConstraint(
                fields=("plan", "role"), name="unique_partition_role"
            ),
        ),
        migrations.AddConstraint(
            model_name="decisionproviderrequest",
            constraint=models.UniqueConstraint(
                fields=("plan", "participant", "role", "input_sha256"),
                name="unique_decision_provider_request",
            ),
        ),
        migrations.AddConstraint(
            model_name="trainingexperiment",
            constraint=models.UniqueConstraint(
                fields=("project", "request_key"), name="unique_training_experiment_request"
            ),
        ),
        migrations.RunPython(bind_existing_plans, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="nativeevaluationplan",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="overbae.project"
            ),
        ),
    ]
