# Generated by Django 6.0.8 on 2026-10-04 16:01

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("overbae", "0020_decision_performance"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataExploration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("request_key", models.CharField(max_length=128)),
                ("kind", models.CharField(max_length=16)),
                ("source_fingerprint", models.CharField(max_length=64)),
                ("config", models.JSONField(default=dict)),
                ("report", models.JSONField(default=dict)),
                ("state", models.CharField(db_index=True, default="queued", max_length=16)),
                ("error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "output_dataset",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="derivations",
                        to="overbae.dataset",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="overbae.project"
                    ),
                ),
                (
                    "source_cell",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="explorations",
                        to="overbae.cell",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "request_key"), name="unique_exploration_request"
                    )
                ],
            },
        ),
    ]
