# Generated by Django 6.0.8 on 2026-10-05 19:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overbae', '0021_data_exploration'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(default='preparation', max_length=24)),
                ('state', models.CharField(choices=[('planning', 'Planning'), ('queued', 'Queued'), ('running', 'Running'), ('paused', 'Paused'), ('partial', 'Partial'), ('blocked', 'Blocked'), ('complete', 'Complete'), ('cancelled', 'Cancelled')], default='planning', max_length=16)),
                ('request', models.TextField(blank=True, default='')),
                ('source_fingerprint', models.CharField(blank=True, default='', max_length=64)),
                ('specification', models.JSONField(blank=True, default=dict)),
                ('plan', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('failure', models.JSONField(blank=True, default=dict)),
                ('recovery', models.JSONField(blank=True, default=dict)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('generated_rows', models.PositiveIntegerField(default=0)),
                ('target_rows', models.PositiveIntegerField(default=0)),
                ('owner', models.CharField(blank=True, default='', max_length=255)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_runs', to='overbae.dataset')),
                ('output', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='workshop_outputs', to='overbae.cell')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='overbae.workshoprun')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='workshop_inputs', to='overbae.cell')),
            ],
        ),
        migrations.CreateModel(
            name='WorkshopWorkItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=128)),
                ('kind', models.CharField(default='generation', max_length=24)),
                ('state', models.CharField(default='pending', max_length=24)),
                ('inputs', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('failure', models.JSONField(blank=True, default=dict)),
                ('provider', models.JSONField(blank=True, default=dict)),
                ('usage', models.JSONField(blank=True, default=dict)),
                ('artifact', models.CharField(blank=True, default='', max_length=255)),
                ('fingerprint', models.CharField(blank=True, default='', max_length=64)),
                ('request_fingerprint', models.CharField(blank=True, default='', max_length=64)),
                ('rows', models.PositiveIntegerField(default=0)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('owner', models.CharField(blank=True, default='', max_length=255)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='overbae.workshoprun')),
            ],
        ),
        migrations.CreateModel(
            name='WorkshopRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_fingerprint', models.CharField(max_length=64)),
                ('seed_row', models.PositiveBigIntegerField()),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='overbae.workshoprun')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='overbae.workshopworkitem')),
            ],
        ),
        migrations.AddIndex(
            model_name='workshoprun',
            index=models.Index(fields=['dataset', 'kind', '-created_at'], name='workshop_dataset_kind'),
        ),
        migrations.AddConstraint(
            model_name='workshopworkitem',
            constraint=models.UniqueConstraint(fields=('run', 'key'), name='unique_workshop_work_key'),
        ),
        migrations.AddConstraint(
            model_name='workshoprecord',
            constraint=models.UniqueConstraint(fields=('run', 'content_fingerprint'), name='unique_workshop_generated_content'),
        ),
    ]
