# Generated by Django 6.0.8 on 2026-10-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("overbae", "0026_dataset_history"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatgptaccount",
            name="user",
        ),
        migrations.RemoveField(
            model_name="chatgptauthorization",
            name="account",
        ),
        migrations.RemoveField(
            model_name="chatgptauthorization",
            name="user",
        ),
        migrations.DeleteModel(
            name="ChatGPTInstallation",
        ),
        migrations.RemoveField(
            model_name="chatgptloginticket",
            name="user",
        ),
        migrations.AlterField(
            model_name="user",
            name="sign_on_method",
            field=models.CharField(
                choices=[("password", "Password"), ("google", "Google"), ("saml", "Saml")],
                default="password",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="ChatGPTAccount",
        ),
        migrations.DeleteModel(
            name="ChatGPTAuthorization",
        ),
        migrations.DeleteModel(
            name="ChatGPTLoginTicket",
        ),
    ]
