# Generated by Django 6.0.8 on 2026-10-09 03:32

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("overbae", "0028_operational_progress"),
    ]

    operations = [
        migrations.AddField(
            model_name="operationalrun",
            name="provider_state",
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name="InferenceRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("request_key", models.CharField(max_length=128)),
                ("fingerprint", models.CharField(max_length=64)),
                ("payload", models.JSONField(default=dict)),
                ("result", models.JSONField(default=dict)),
                ("state", models.CharField(db_index=True, default="queued", max_length=32)),
                ("remote_id", models.CharField(blank=True, max_length=100)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("is_cold", models.BooleanField(default=False)),
                ("claim", models.UUIDField(null=True)),
                ("claim_until", models.DateTimeField(null=True)),
                ("next_poll_at", models.DateTimeField(db_index=True)),
                ("deadline", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(null=True)),
                (
                    "deployment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="overbae.deployedmodel"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="overbae.project"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "request_key"), name="inference_request_key_unique"
                    )
                ],
            },
        ),
    ]
