# Generated by Django 6.0.8 on 2026-10-09 03:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("overbae", "0029_inference_requests"),
    ]

    operations = [
        migrations.AddField(
            model_name="operationalrun",
            name="collection",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="operationalrun",
            name="next_collection_at",
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
