# Generated by Django 6.0.8 on 2026-10-10 06:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overbae', '0032_datasetpipelinebinding_datasetpipelinepackage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingCheckpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=160)),
                ('attempt', models.PositiveIntegerField()),
                ('step', models.PositiveIntegerField()),
                ('state', models.CharField(max_length=24)),
                ('identity', models.CharField(max_length=64)),
                ('manifest', models.JSONField(default=dict)),
                ('verification', models.JSONField(default=dict)),
                ('metrics', models.JSONField(default=dict)),
                ('selected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retained_checkpoints', to='overbae.finetuningjob')),
            ],
            options={
                'db_table': 'overbae_trainingretainedcheckpoint',
                'constraints': [models.UniqueConstraint(fields=('job', 'key'), name='training_checkpoint_key')],
            },
        ),
        migrations.CreateModel(
            name='TrainingValidationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=160)),
                ('attempt', models.PositiveIntegerField()),
                ('stream', models.CharField(max_length=32)),
                ('step', models.PositiveIntegerField()),
                ('state', models.CharField(max_length=24)),
                ('policy_fingerprint', models.CharField(max_length=64)),
                ('sample_fingerprint', models.CharField(max_length=64)),
                ('receipt_fingerprint', models.CharField(blank=True, max_length=64)),
                ('started_at', models.DateTimeField(null=True)),
                ('observed_at', models.DateTimeField(null=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('metrics', models.JSONField(default=dict)),
                ('coverage', models.JSONField(default=dict)),
                ('facts', models.JSONField(default=dict)),
                ('failure', models.JSONField(default=dict)),
                ('evidence', models.FileField(blank=True, upload_to='training-monitoring/')),
                ('evidence_sha256', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_runs', to='overbae.finetuningjob')),
            ],
            options={
                'indexes': [models.Index(fields=['job', 'step', 'attempt'], name='training_check_step')],
                'constraints': [models.UniqueConstraint(fields=('job', 'key'), name='training_check_key')],
            },
        ),
    ]
