# Generated by Django 6.0.8 on 2026-10-10 22:40

from django.db import migrations, models


def archive_usage(apps, schema_editor):
    experiments = apps.get_model("overbae", "OptimizerExperiment").objects.using(
        schema_editor.connection.alias
    )
    for experiment in (
        experiments.exclude(cursor_usage={})
        .only("id", "state", "cursor_usage")
        .iterator(chunk_size=500)
    ):
        state = experiment.state
        if not isinstance(state, dict):
            raise RuntimeError(
                f"Cannot archive usage in non-object state: {experiment.pk}"
            )
        if "archived_cursor_usage" in state:
            raise RuntimeError(f"Cursor usage archive already exists: {experiment.pk}")
        experiments.filter(pk=experiment.pk).update(
            state={**state, "archived_cursor_usage": experiment.cursor_usage}
        )


def restore_usage(apps, schema_editor):
    experiments = apps.get_model("overbae", "OptimizerExperiment").objects.using(
        schema_editor.connection.alias
    )
    for experiment in (
        experiments.filter(state__has_key="archived_cursor_usage")
        .only("id", "state")
        .iterator(chunk_size=500)
    ):
        state = dict(experiment.state)
        usage = state.pop("archived_cursor_usage")
        experiments.filter(pk=experiment.pk).update(state=state, cursor_usage=usage)


class Migration(migrations.Migration):
    dependencies = [
        ("overbae", "0034_source_import_recovery"),
    ]

    operations = [
        migrations.RunPython(archive_usage, restore_usage),
        migrations.RemoveField(
            model_name="optimizerexperiment",
            name="cursor_usage",
        ),
        migrations.AlterField(
            model_name="billingtelemetry",
            name="service",
            field=models.CharField(
                choices=[
                    ("free-credits", "Free credits"),
                    ("stripe-topup", "Stripe top-up"),
                    ("finetuning-job", "Finetuning job"),
                    ("inference", "Inference"),
                    ("inference-ft-model", "Fine-tuned inference"),
                    ("data-workshop", "Data workshop"),
                    ("evaluation", "Evaluation"),
                ],
                max_length=32,
            ),
        ),
    ]
