"""Span attribute keys emitted by the Overmind CLI.

Mirrored from ``overmind/attrs.py`` in the claw repository — a key the server
interprets must be added there first and copied here verbatim.
"""

from __future__ import annotations

COMMAND = "overmind.command"
CLI_VERSION = "overmind.cli.version"


STATUS = "overmind.status"  # "running" | "success" | "failed" | "cancelled"
ERROR_TYPE = "overmind.error.type"
ERROR_MESSAGE = "overmind.error.message"
PROGRESS_PHASE = "overmind.progress.phase"
PROGRESS_CURRENT = "overmind.progress.current"
PROGRESS_TOTAL = "overmind.progress.total"
DURATION_SECONDS = "overmind.duration.seconds"

# Current SDKs stamp the bare key; older Python builds used the namespaced one.
CONVERSATION_ID = "conversation.id"
CONVERSATION_ID_LEGACY = "overmind.conversation.id"

CAPABILITY_ID = "overmind.capability.id"
PROJECT_ID = "overmind.project.id"
JOB_ID = "overmind.job.id"
ITERATION_ID = "overmind.iteration.id"
EXPERIMENT_ID = "overmind.experiment.id"

CAPABILITY_NAME = "overmind.capability.name"

INIT_ENV_PATH = "overmind.init.env_path"
INIT_HAS_OPENAI_KEY = "overmind.init.has_openai_key"
INIT_HAS_ANTHROPIC_KEY = "overmind.init.has_anthropic_key"
INIT_HAS_OVERMIND_TOKEN = "overmind.init.has_overmind_token"
INIT_ANALYZER_MODEL = "overmind.init.analyzer_model"
INIT_HAS_SYNTHETIC_DATAGEN_MODEL = "overmind.init.has_synthetic_datagen_model"


SETUP_FAST = "overmind.setup.fast"
SETUP_MODEL = "overmind.setup.model"
SETUP_HAS_POLICY = "overmind.setup.has_policy"
SETUP_HAS_SEED_DATA = "overmind.setup.has_seed_data"
SETUP_POLICY_PATH = "overmind.setup.policy_path"
SETUP_DATA_PATH = "overmind.setup.data_path"
SETUP_STORAGE_BACKEND = "overmind.setup.storage_backend"
SETUP_ENTRYPOINT_FN = "overmind.setup.entrypoint_fn"
SETUP_ANALYZER_MODEL = "overmind.setup.analyzer_model"
SETUP_PHASE = "overmind.setup.phase"
SETUP_EVAL_SPEC_FIELD_COUNT = "overmind.setup.eval_spec_field_count"
SETUP_EVAL_SPEC_HAS_TOOLS = "overmind.setup.eval_spec_has_tools"
SETUP_EVAL_SPEC_HAS_JUDGE = "overmind.setup.eval_spec_has_judge"
SETUP_EVAL_SPEC_HAS_POLICY = "overmind.setup.eval_spec_has_policy"
SETUP_EVAL_SPEC_STRUCTURE_WEIGHT = "overmind.setup.eval_spec_structure_weight"
SETUP_EVAL_SPEC_TOOL_COUNT = "overmind.setup.eval_spec_tool_count"
SETUP_EVAL_SPEC_CONSISTENCY_RULE_COUNT = "overmind.setup.eval_spec_consistency_rule_count"
SETUP_CRITERIA_SOURCE = "overmind.setup.criteria_source"
SETUP_POLICY_SOURCE = "overmind.setup.policy_source"
# Newer flows prefer these over the agent_policy_* keys above.
SETUP_POLICY_MARKDOWN = "overmind.setup.policy_markdown"
SETUP_EVAL_SPEC = "overmind.setup.eval_spec"  # JSON string
SETUP_PROPOSED_CRITERIA = "overmind.setup.proposed_criteria"
SETUP_TOOL_ANALYSIS = "overmind.setup.tool_analysis"
SETUP_INPUT_SCHEMA = "overmind.setup.input_schema"
SETUP_OUTPUT_SCHEMA = "overmind.setup.output_schema"
SETUP_CONSISTENCY_RULES = "overmind.setup.consistency_rules"
SETUP_TOOLS_SUMMARY = "overmind.setup.tools_summary"
SETUP_DECISION_LOGIC = "overmind.setup.decision_logic"
SETUP_SCOPE = "overmind.setup.scope"
SETUP_OPTIMIZABLE_ELEMENTS = "overmind.setup.optimizable_elements"
SETUP_FIXED_ELEMENTS = "overmind.setup.fixed_elements"

OPTIMIZE_FAST = "overmind.optimize.fast"
OPTIMIZE_ENTRYPOINT_FN = "overmind.optimize.entrypoint_fn"
OPTIMIZE_STORAGE_BACKEND = "overmind.optimize.storage_backend"
OPTIMIZE_ANALYZER_MODEL = "overmind.optimize.analyzer_model"
OPTIMIZE_LLM_JUDGE_MODEL = "overmind.optimize.llm_judge_model"
OPTIMIZE_ITERATIONS = "overmind.optimize.iterations"
OPTIMIZE_CANDIDATES_PER_ITERATION = "overmind.optimize.candidates_per_iteration"
OPTIMIZE_PARALLEL = "overmind.optimize.parallel"
OPTIMIZE_MAX_WORKERS = "overmind.optimize.max_workers"
OPTIMIZE_RUNS_PER_EVAL = "overmind.optimize.runs_per_eval"
OPTIMIZE_REGRESSION_THRESHOLD = "overmind.optimize.regression_threshold"
OPTIMIZE_HOLDOUT_RATIO = "overmind.optimize.holdout_ratio"
OPTIMIZE_HOLDOUT_ENFORCEMENT = "overmind.optimize.holdout_enforcement"
OPTIMIZE_EARLY_STOPPING_PATIENCE = "overmind.optimize.early_stopping_patience"
OPTIMIZE_CROSS_RUN_PERSISTENCE = "overmind.optimize.cross_run_persistence"
OPTIMIZE_FAILURE_CLUSTERING = "overmind.optimize.failure_clustering"
OPTIMIZE_ADAPTIVE_FOCUS = "overmind.optimize.adaptive_focus"
OPTIMIZE_MODEL_BACKTESTING = "overmind.optimize.model_backtesting"
OPTIMIZE_BACKTEST_MODELS = "overmind.optimize.backtest_models"
OPTIMIZE_EVAL_SPEC_PATH = "overmind.optimize.eval_spec_path"
OPTIMIZE_DATA_PATH = "overmind.optimize.data_path"
OPTIMIZE_EVAL_SPEC = "overmind.optimize.eval_spec"  # JSON string; refreshes Capability eval fields

OPTIMIZE_PHASE = "overmind.optimize.phase"
OPTIMIZE_DATASET_TOTAL = "overmind.optimize.dataset_total"
OPTIMIZE_DATASET_TRAIN = "overmind.optimize.dataset_train"
OPTIMIZE_DATASET_HOLDOUT = "overmind.optimize.dataset_holdout"
OPTIMIZE_BASELINE_SCORE = "overmind.optimize.baseline_score"
OPTIMIZE_ITERATION = "overmind.optimize.iteration"
OPTIMIZE_TOTAL_ITERATIONS = "overmind.optimize.total_iterations"
OPTIMIZE_BEST_SCORE_BEFORE = "overmind.optimize.best_score_before"
OPTIMIZE_STALL_COUNT = "overmind.optimize.stall_count"
OPTIMIZE_TEMPERATURE = "overmind.optimize.temperature"
OPTIMIZE_N_CANDIDATES_GENERATED = "overmind.optimize.n_candidates_generated"
OPTIMIZE_N_CANDIDATES_VALID = "overmind.optimize.n_candidates_valid"
OPTIMIZE_CANDIDATE_INDEX = "overmind.optimize.candidate_index"
OPTIMIZE_CANDIDATE_METHOD = "overmind.optimize.candidate_method"
OPTIMIZE_CANDIDATE_SCORE = "overmind.optimize.candidate_score"
OPTIMIZE_CANDIDATE_ADJUSTED_SCORE = "overmind.optimize.candidate_adjusted_score"
OPTIMIZE_COMPLEXITY_PENALTY = "overmind.optimize.complexity_penalty"
OPTIMIZE_ITERATION_DECISION = "overmind.optimize.iteration_decision"
OPTIMIZE_ITERATION_SCORE = "overmind.optimize.iteration_score"
OPTIMIZE_ITERATION_IMPROVEMENT = "overmind.optimize.iteration_improvement"
OPTIMIZE_ITERATION_REASON = "overmind.optimize.iteration_reason"
OPTIMIZE_STEP = "overmind.optimize.step"
OPTIMIZE_RUN_STATUS = "overmind.optimize.run_status"
# JSON — OTel attributes cannot carry nested dicts.
OPTIMIZE_ITERATION_DIMENSION_SCORES = "overmind.optimize.iteration_dimension_scores"
# → JobIteration.agent_code
OPTIMIZE_ITERATION_AGENT_CODE = "overmind.optimize.iteration_agent_code"
# JSON list of change summaries → JobIteration.description
OPTIMIZE_ITERATION_SUGGESTIONS = "overmind.optimize.iteration_suggestions"
OPTIMIZE_ACCEPTED = "overmind.optimize.accepted"
OPTIMIZE_FINAL_BEST_SCORE = "overmind.optimize.final_best_score"
OPTIMIZE_REPORT_MARKDOWN = "overmind.optimize.report_markdown"  # → Job.report_markdown
OPTIMIZE_BEST_AGENT_CODE = "overmind.optimize.best_agent_code"  # → Job.best_agent_code
OPTIMIZE_HOLDOUT_SCORE = "overmind.optimize.holdout_score"
OPTIMIZE_HOLDOUT_BASELINE_SCORE = "overmind.optimize.holdout_baseline_score"
OPTIMIZE_HOLDOUT_IMPROVEMENT = "overmind.optimize.holdout_improvement"
OPTIMIZE_BLENDED_IMPROVEMENT = "overmind.optimize.blended_improvement"
OPTIMIZE_HOLDOUT_REVERTED = "overmind.optimize.holdout_reverted"
OPTIMIZE_OVERFIT_GAP = "overmind.optimize.overfit_gap"
OPTIMIZE_TOTAL_ACCEPTED = "overmind.optimize.total_accepted"
OPTIMIZE_TOTAL_REJECTED = "overmind.optimize.total_rejected"
OPTIMIZE_REPORT_IMPROVEMENT = "overmind.optimize.report_improvement"
OPTIMIZE_BACKTEST_MODEL = "overmind.optimize.backtest_model"
OPTIMIZE_BACKTEST_SCORE = "overmind.optimize.backtest_score"

# Span EVENT names / event-attribute keys, not span attributes; payloads are JSON strings.
EVAL_SCHEMA_VERSION = "overmind.eval.schema_version"
EVAL_PAYLOAD = "overmind.eval.payload"
EVAL_EVENT_EXPECTATION = "overmind.eval.expectation"
EVAL_EVENT_CONTEXT = "overmind.eval.context"
EVAL_EVENT_CHECKPOINT = "overmind.eval.checkpoint"
EVAL_EVENT_CONVERSATION_END = "overmind.eval.conversation_end"
EVAL_EVENT_INTENT = "overmind.eval.intent"

# Stamped on LLM spans by ``opentelemetry-overmind`` when a PromptString is used.
PROMPT_TEMPLATE = "overmind.prompt.template"
PROMPT_KWARGS = "overmind.prompt.kwargs"  # JSON string

EVAL_BATCH_SIZE = "overmind.eval.batch_size"
EVAL_AVG_TOTAL = "overmind.eval.avg_total"
EVAL_USED_LLM_JUDGE = "overmind.eval.used_llm_judge"
EVAL_JUDGE_NEEDS_COUNT = "overmind.eval.judge_needs_count"
EVAL_JUDGE_FAIL_COUNT = "overmind.eval.judge_fail_count"
EVAL_JUDGE_FAIL_PCT = "overmind.eval.judge_fail_pct"
EVAL_AVG_CONFIDENCE = "overmind.eval.avg_confidence"
EVAL_SOURCE_SUMMARY = "overmind.eval.source_summary"
RUN_AGENT_RUN_NAME = "overmind.run.run_name"
RUN_AGENT_AGENT_PATH = "overmind.run.agent_path"
RUN_AGENT_CASES_TOTAL = "overmind.run.cases_total"
RUN_AGENT_CASES_SUCCEEDED = "overmind.run.cases_succeeded"
RUN_AGENT_CASES_FAILED = "overmind.run.cases_failed"
RUN_AGENT_CASES_WITH_PROVENANCE = "overmind.run.cases_with_provenance"
RUN_AGENT_PARALLEL = "overmind.run.parallel"
RUN_AGENT_MAX_WORKERS = "overmind.run.max_workers"
RUN_AGENT_BACKENDS = "overmind.run.backends"
RUN_AGENT_BACKEND_USED = "overmind.run.backend_used"
RUN_AGENT_AVG_SCORE = "overmind.run.avg_score"
RUN_AGENT_DIMENSION_SCORES = "overmind.run.dimension_scores"
RUN_AGENT_PASS_RATE = "overmind.run.pass_rate"
RUN_AGENT_DURATION_SECONDS = "overmind.run.duration_seconds"
RUN_AGENT_PER_CASE_SCORES = "overmind.run.per_case_scores"

RUN_CASE_RUN_NAME = "overmind.run.case.run_name"
RUN_CASE_INDEX = "overmind.run.case.index"
RUN_CASE_INPUT_KEYS = "overmind.run.case.input_keys"
RUN_CASE_INPUT_CHARS = "overmind.run.case.input_chars"
RUN_CASE_BACKEND_ATTEMPTS = "overmind.run.case.backend_attempts"
RUN_CASE_BACKENDS_TRIED = "overmind.run.case.backends_tried"
RUN_CASE_BACKEND_USED = "overmind.run.case.backend_used"
RUN_CASE_SUCCESS = "overmind.run.case.success"
RUN_CASE_RETURNCODE = "overmind.run.case.returncode"
RUN_CASE_ERROR = "overmind.run.case.error"
RUN_CASE_OUTPUT_CHARS = "overmind.run.case.output_chars"
RUN_CASE_DURATION_SECONDS = "overmind.run.case.duration_seconds"
RUN_CASE_PROVENANCE_COUNT = "overmind.run.case.provenance_count"
RUN_CASE_CONFIDENCE = "overmind.run.case.confidence"

OPTIMIZE_WORKTREE_RUN_NAME = "overmind.optimize.worktree.run_name"
OPTIMIZE_WORKTREE_ENTRY_PATH = "overmind.optimize.worktree.entry_path"
OPTIMIZE_WORKTREE_CASES_TOTAL = "overmind.optimize.worktree.cases_total"
OPTIMIZE_WORKTREE_AVG_SCORE = "overmind.optimize.worktree.avg_score"
OPTIMIZE_WORKTREE_DIMENSION_SCORES = "overmind.optimize.worktree.dimension_scores"
OPTIMIZE_WORKTREE_PASS_RATE = "overmind.optimize.worktree.pass_rate"
OPTIMIZE_WORKTREE_DURATION_SECONDS = "overmind.optimize.worktree.duration_seconds"

RUN_STATE_TOTAL_RUNS = "overmind.run_state.total_runs"
RUN_STATE_REGRESSION_CASES = "overmind.run_state.regression_cases"
RUN_STATE_FAILURE_CLUSTERS = "overmind.run_state.failure_clusters"
RUN_STATE_LATEST_BASELINE = "overmind.run_state.latest_baseline"
RUN_STATE_LATEST_FINAL = "overmind.run_state.latest_final"
RUN_STATE_LATEST_ACCEPTED = "overmind.run_state.latest_accepted"
RUN_STATE_LATEST_REJECTED = "overmind.run_state.latest_rejected"

CANDIDATES_REQUESTED = "overmind.candidates.requested"
CANDIDATES_PRODUCED = "overmind.candidates.produced"
CANDIDATES_METHODS = "overmind.candidates.methods"
CANDIDATES_HAS_DIAGNOSIS = "overmind.candidates.has_diagnosis"
CANDIDATES_USE_BUNDLE = "overmind.candidates.use_bundle"
CANDIDATES_HAS_ROOT_CAUSE = "overmind.candidates.has_root_cause"
CANDIDATES_FALLBACK = "overmind.candidates.fallback"

SEED_VALIDATION_TOTAL_CASES = "overmind.seed_validation.total_cases"
SEED_VALIDATION_VALID_COUNT = "overmind.seed_validation.valid_count"
SEED_VALIDATION_INVALID_COUNT = "overmind.seed_validation.invalid_count"
SEED_COVERAGE_QUALITY_SCORE = "overmind.seed_coverage.quality_score"
SEED_COVERAGE_CASE_COUNT = "overmind.seed_coverage.case_count"
SEED_COVERAGE_GAP_COUNT = "overmind.seed_coverage.gap_count"
SEED_COVERAGE_UNCOVERED_RULE_COUNT = "overmind.seed_coverage.uncovered_rule_count"
SEED_COVERAGE_SUGGESTED_ADDITIONAL_CASES = "overmind.seed_coverage.suggested_additional_cases"

CODING_AGENT_MODEL = "overmind.coding_agent.model"
CODING_AGENT_INPUT_FILE_COUNT = "overmind.coding_agent.input_file_count"
CODING_AGENT_MODIFIED_FILE_COUNT = "overmind.coding_agent.modified_file_count"
CODING_AGENT_STEPS_TAKEN = "overmind.coding_agent.steps_taken"
CODING_AGENT_MAX_STEPS = "overmind.coding_agent.max_steps"
CODING_AGENT_TOKENS_IN = "overmind.coding_agent.tokens_in"
CODING_AGENT_TOKENS_OUT = "overmind.coding_agent.tokens_out"
CODING_AGENT_LOOP_STEPS = "overmind.coding_agent.loop_steps"
CODING_AGENT_EXIT_REASON = "overmind.coding_agent.exit_reason"

LLM_MODEL = "genai.model"
LLM_RESPONSE_MODEL = "genai.response.model"
LLM_PROVIDER = "genai.provider"
LLM_PROMPT_TOKENS = "genai.prompt_tokens"
LLM_COMPLETION_TOKENS = "genai.completion_tokens"
LLM_TOTAL_TOKENS = "genai.total_tokens"
# Never folded into ``total_tokens`` (docs/tracing-attributes.md §3).
LLM_CACHE_READ_TOKENS = "genai.cache_read_tokens"
LLM_COST = "genai.cost"
LLM_ERROR = "genai.error"
LLM_ELAPSED_SECONDS = "genai.elapsed_seconds"
LLM_REQUEST_MESSAGE_COUNT = "genai.request.message_count"
LLM_REQUEST_MESSAGE_CHARS = "genai.request.message_chars"
LLM_REQUEST_TOOL_COUNT = "genai.request.tool_count"
LLM_REQUEST_KWARGS = "genai.request.kwargs"
LLM_REQUEST_TEMPERATURE = "genai.request.temperature"
LLM_REQUEST_MAX_TOKENS = "genai.request.max_tokens"
LLM_REQUEST_TOP_P = "genai.request.top_p"
LLM_RESPONSE_MESSAGE_CHARS = "genai.response.message_chars"
LLM_RESPONSE_FINISH_REASON = "genai.response.finish_reason"
LLM_STREAMING = "genai.streaming"
LLM_TTFT_SECONDS = "genai.time_to_first_token_seconds"
LLM_USAGE_PROMPT_TOKENS = "genai.usage.prompt_tokens"
LLM_USAGE_COMPLETION_TOKENS = "genai.usage.completion_tokens"
LLM_USAGE_TOTAL_TOKENS = "genai.usage.total_tokens"

TOOL_NAME = "tool.name"
TOOL_ARG_KEYS = "tool.arg_keys"
TOOL_ERROR = "tool.error"

RETRIEVAL_QUERY_CHARS = "overmind.retrieval.query_chars"
RETRIEVAL_RESULT_COUNT = "overmind.retrieval.result_count"

PROVENANCE = "overmind.provenance"  # user | agent | environment | harness
UNIT_KIND = "overmind.unit_kind"  # turn | run
DELIVERY = "overmind.delivery"  # true on the span carrying the terminal deliverable

INPUT_DATA = "overmind.input.data"
OUTPUT_DATA = "overmind.output.data"
SCORE = "overmind.score"
ERROR = "overmind.error"
SPAN_TYPE = "overmind.span.type"
